<?php
//namespace ;

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


final class status_reg {
  const active = 0;
  const inactive = 1;
  const stored = 2;
  const deleted = 3;
  static public $__names = array(
    0 => 'active',
    1 => 'inactive',
    2 => 'stored',
    3 => 'deleted',
  );
}

class TPR {
  static $_TSPEC;

  public $tpr_id = 0;
  public $tpr_name = "";
  public $tpr_year = 0;
  public $tpr_description = "";
  public $tpr_hot_id = 0;
  public $tpr_restriction = "";
  public $tpr_min_nights = 0;
  public $tpr_status_reg = null;
  public $tpr_updated_by = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'tpr_id',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'tpr_name',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'tpr_year',
          'type' => TType::I32,
          ),
        4 => array(
          'var' => 'tpr_description',
          'type' => TType::STRING,
          ),
        5 => array(
          'var' => 'tpr_hot_id',
          'type' => TType::I32,
          ),
        6 => array(
          'var' => 'tpr_restriction',
          'type' => TType::STRING,
          ),
        7 => array(
          'var' => 'tpr_min_nights',
          'type' => TType::I32,
          ),
        20 => array(
          'var' => 'tpr_status_reg',
          'type' => TType::I32,
          ),
        21 => array(
          'var' => 'tpr_updated_by',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['tpr_id'])) {
        $this->tpr_id = $vals['tpr_id'];
      }
      if (isset($vals['tpr_name'])) {
        $this->tpr_name = $vals['tpr_name'];
      }
      if (isset($vals['tpr_year'])) {
        $this->tpr_year = $vals['tpr_year'];
      }
      if (isset($vals['tpr_description'])) {
        $this->tpr_description = $vals['tpr_description'];
      }
      if (isset($vals['tpr_hot_id'])) {
        $this->tpr_hot_id = $vals['tpr_hot_id'];
      }
      if (isset($vals['tpr_restriction'])) {
        $this->tpr_restriction = $vals['tpr_restriction'];
      }
      if (isset($vals['tpr_min_nights'])) {
        $this->tpr_min_nights = $vals['tpr_min_nights'];
      }
      if (isset($vals['tpr_status_reg'])) {
        $this->tpr_status_reg = $vals['tpr_status_reg'];
      }
      if (isset($vals['tpr_updated_by'])) {
        $this->tpr_updated_by = $vals['tpr_updated_by'];
      }
    }
  }

  public function getName() {
    return 'TPR';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_year);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_description);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_hot_id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_restriction);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_min_nights);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 20:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_status_reg);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 21:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_updated_by);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('TPR');
    if ($this->tpr_id !== null) {
      $xfer += $output->writeFieldBegin('tpr_id', TType::I32, 1);
      $xfer += $output->writeI32($this->tpr_id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_name !== null) {
      $xfer += $output->writeFieldBegin('tpr_name', TType::STRING, 2);
      $xfer += $output->writeString($this->tpr_name);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_year !== null) {
      $xfer += $output->writeFieldBegin('tpr_year', TType::I32, 3);
      $xfer += $output->writeI32($this->tpr_year);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_description !== null) {
      $xfer += $output->writeFieldBegin('tpr_description', TType::STRING, 4);
      $xfer += $output->writeString($this->tpr_description);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_hot_id !== null) {
      $xfer += $output->writeFieldBegin('tpr_hot_id', TType::I32, 5);
      $xfer += $output->writeI32($this->tpr_hot_id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_restriction !== null) {
      $xfer += $output->writeFieldBegin('tpr_restriction', TType::STRING, 6);
      $xfer += $output->writeString($this->tpr_restriction);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_min_nights !== null) {
      $xfer += $output->writeFieldBegin('tpr_min_nights', TType::I32, 7);
      $xfer += $output->writeI32($this->tpr_min_nights);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_status_reg !== null) {
      $xfer += $output->writeFieldBegin('tpr_status_reg', TType::I32, 20);
      $xfer += $output->writeI32($this->tpr_status_reg);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_updated_by !== null) {
      $xfer += $output->writeFieldBegin('tpr_updated_by', TType::I32, 21);
      $xfer += $output->writeI32($this->tpr_updated_by);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


