<?php

// Load up all the thrift stuff
require_once 'Thrift.php';
require_once 'protocol/TBinaryProtocol.php';
require_once 'transport/TSocket.php';
require_once 'transport/TBufferedTransport.php';
 
// Load the package that we autogenerated for this tutorial
require_once 'gen-php/TPR/TPR_types.php';
 
// Several things might go wrong
try {
    // Create a thrift connection (Boiler plate)
    $socket = new TSocket('localhost', '4390');
    $transport = new TBufferedTransport($socket);
    $protocol = new TBinaryProtocol($transport);
 
    // Create a calculator client
    $rowTPR = new TPR(array('tpr_id' => 1));
 
    // Open up the connection
    $transport->open();
    print_r($rowTPR);
    $rowTPR->write($protocol);
    $transport->flush();
    $rowTPR->read($protocol);
    print_r($rowTPR);
 
    // And finally, we close the thrift connection
    $transport->close();
 /*
} catch (ArithmaticException $ae) {
    // performed an illegal operation, like 10/0
    echo "ArithmatixException: ".$ae->msg."\r\n";
 
} catch (MatrixException $mx) {
    // performed an illegal matrix operation
    echo "MatrixException: ".$mx->msg."\r\n";
 */
} catch (TException $tx) {
    // a general thrift exception, like no such server
    echo "ThriftException: ".$tx->getMessage()."\r\n";
}