<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


$GLOBALS['E_status_reg'] = array(
  'active' => 0,
  'inactive' => 1,
  'stored' => 2,
  'deleted' => 3,
);

final class status_reg {
  const active = 0;
  const inactive = 1;
  const stored = 2;
  const deleted = 3;
  static public $__names = array(
    0 => 'active',
    1 => 'inactive',
    2 => 'stored',
    3 => 'deleted',
  );
}

class TPR {
  static $_TSPEC;

  public $tpr_id = 0;
  public $tpr_name = 0;
  public $tpr_year = 0;
  public $tpr_description = 0;
  public $tpr_hot_id = 0;
  public $tpr_restriction = 0;
  public $tpr_min_nights = 0;
  public $tpr_data_5 = "";
  public $tpr_data_6 = "";
  public $tpr_data_7 = "";
  public $tpr_data_8 = "";
  public $tpr_data_9 = "";
  public $tpr_data_10 = "";
  public $tpr_data_11 = "";
  public $tpr_data_12 = "";
  public $tpr_data_1 = "";
  public $tpr_data_2 = "";
  public $tpr_data_3 = "";
  public $tpr_data_4 = "";
  public $tpr_status_reg = null;
  public $tpr_updated_by = null;
  public $tpr_updated = "";
  public $tpr_created = "";

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'tpr_id',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'tpr_name',
          'type' => TType::I32,
          ),
        3 => array(
          'var' => 'tpr_year',
          'type' => TType::I32,
          ),
        4 => array(
          'var' => 'tpr_description',
          'type' => TType::I32,
          ),
        5 => array(
          'var' => 'tpr_hot_id',
          'type' => TType::I32,
          ),
        6 => array(
          'var' => 'tpr_restriction',
          'type' => TType::I32,
          ),
        7 => array(
          'var' => 'tpr_min_nights',
          'type' => TType::I32,
          ),
        8 => array(
          'var' => 'tpr_data_5',
          'type' => TType::STRING,
          ),
        9 => array(
          'var' => 'tpr_data_6',
          'type' => TType::STRING,
          ),
        10 => array(
          'var' => 'tpr_data_7',
          'type' => TType::STRING,
          ),
        11 => array(
          'var' => 'tpr_data_8',
          'type' => TType::STRING,
          ),
        12 => array(
          'var' => 'tpr_data_9',
          'type' => TType::STRING,
          ),
        13 => array(
          'var' => 'tpr_data_10',
          'type' => TType::STRING,
          ),
        14 => array(
          'var' => 'tpr_data_11',
          'type' => TType::STRING,
          ),
        15 => array(
          'var' => 'tpr_data_12',
          'type' => TType::STRING,
          ),
        16 => array(
          'var' => 'tpr_data_1',
          'type' => TType::STRING,
          ),
        17 => array(
          'var' => 'tpr_data_2',
          'type' => TType::STRING,
          ),
        18 => array(
          'var' => 'tpr_data_3',
          'type' => TType::STRING,
          ),
        19 => array(
          'var' => 'tpr_data_4',
          'type' => TType::STRING,
          ),
        20 => array(
          'var' => 'tpr_status_reg',
          'type' => TType::I32,
          ),
        21 => array(
          'var' => 'tpr_updated_by',
          'type' => TType::I32,
          ),
        22 => array(
          'var' => 'tpr_updated',
          'type' => TType::STRING,
          ),
        23 => array(
          'var' => 'tpr_created',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['tpr_id'])) {
        $this->tpr_id = $vals['tpr_id'];
      }
      if (isset($vals['tpr_name'])) {
        $this->tpr_name = $vals['tpr_name'];
      }
      if (isset($vals['tpr_year'])) {
        $this->tpr_year = $vals['tpr_year'];
      }
      if (isset($vals['tpr_description'])) {
        $this->tpr_description = $vals['tpr_description'];
      }
      if (isset($vals['tpr_hot_id'])) {
        $this->tpr_hot_id = $vals['tpr_hot_id'];
      }
      if (isset($vals['tpr_restriction'])) {
        $this->tpr_restriction = $vals['tpr_restriction'];
      }
      if (isset($vals['tpr_min_nights'])) {
        $this->tpr_min_nights = $vals['tpr_min_nights'];
      }
      if (isset($vals['tpr_data_5'])) {
        $this->tpr_data_5 = $vals['tpr_data_5'];
      }
      if (isset($vals['tpr_data_6'])) {
        $this->tpr_data_6 = $vals['tpr_data_6'];
      }
      if (isset($vals['tpr_data_7'])) {
        $this->tpr_data_7 = $vals['tpr_data_7'];
      }
      if (isset($vals['tpr_data_8'])) {
        $this->tpr_data_8 = $vals['tpr_data_8'];
      }
      if (isset($vals['tpr_data_9'])) {
        $this->tpr_data_9 = $vals['tpr_data_9'];
      }
      if (isset($vals['tpr_data_10'])) {
        $this->tpr_data_10 = $vals['tpr_data_10'];
      }
      if (isset($vals['tpr_data_11'])) {
        $this->tpr_data_11 = $vals['tpr_data_11'];
      }
      if (isset($vals['tpr_data_12'])) {
        $this->tpr_data_12 = $vals['tpr_data_12'];
      }
      if (isset($vals['tpr_data_1'])) {
        $this->tpr_data_1 = $vals['tpr_data_1'];
      }
      if (isset($vals['tpr_data_2'])) {
        $this->tpr_data_2 = $vals['tpr_data_2'];
      }
      if (isset($vals['tpr_data_3'])) {
        $this->tpr_data_3 = $vals['tpr_data_3'];
      }
      if (isset($vals['tpr_data_4'])) {
        $this->tpr_data_4 = $vals['tpr_data_4'];
      }
      if (isset($vals['tpr_status_reg'])) {
        $this->tpr_status_reg = $vals['tpr_status_reg'];
      }
      if (isset($vals['tpr_updated_by'])) {
        $this->tpr_updated_by = $vals['tpr_updated_by'];
      }
      if (isset($vals['tpr_updated'])) {
        $this->tpr_updated = $vals['tpr_updated'];
      }
      if (isset($vals['tpr_created'])) {
        $this->tpr_created = $vals['tpr_created'];
      }
    }
  }

  public function getName() {
    return 'TPR';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_year);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_description);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_hot_id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_restriction);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_min_nights);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_5);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_6);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 10:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_7);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 11:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_8);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 12:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_9);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 13:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_10);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 14:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_11);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 15:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_12);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 16:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_1);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 17:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_2);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 18:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_3);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 19:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_data_4);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 20:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_status_reg);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 21:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->tpr_updated_by);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 22:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_updated);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 23:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->tpr_created);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('TPR');
    if ($this->tpr_id !== null) {
      $xfer += $output->writeFieldBegin('tpr_id', TType::I32, 1);
      $xfer += $output->writeI32($this->tpr_id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_name !== null) {
      $xfer += $output->writeFieldBegin('tpr_name', TType::I32, 2);
      $xfer += $output->writeI32($this->tpr_name);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_year !== null) {
      $xfer += $output->writeFieldBegin('tpr_year', TType::I32, 3);
      $xfer += $output->writeI32($this->tpr_year);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_description !== null) {
      $xfer += $output->writeFieldBegin('tpr_description', TType::I32, 4);
      $xfer += $output->writeI32($this->tpr_description);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_hot_id !== null) {
      $xfer += $output->writeFieldBegin('tpr_hot_id', TType::I32, 5);
      $xfer += $output->writeI32($this->tpr_hot_id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_restriction !== null) {
      $xfer += $output->writeFieldBegin('tpr_restriction', TType::I32, 6);
      $xfer += $output->writeI32($this->tpr_restriction);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_min_nights !== null) {
      $xfer += $output->writeFieldBegin('tpr_min_nights', TType::I32, 7);
      $xfer += $output->writeI32($this->tpr_min_nights);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_5 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_5', TType::STRING, 8);
      $xfer += $output->writeString($this->tpr_data_5);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_6 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_6', TType::STRING, 9);
      $xfer += $output->writeString($this->tpr_data_6);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_7 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_7', TType::STRING, 10);
      $xfer += $output->writeString($this->tpr_data_7);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_8 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_8', TType::STRING, 11);
      $xfer += $output->writeString($this->tpr_data_8);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_9 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_9', TType::STRING, 12);
      $xfer += $output->writeString($this->tpr_data_9);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_10 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_10', TType::STRING, 13);
      $xfer += $output->writeString($this->tpr_data_10);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_11 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_11', TType::STRING, 14);
      $xfer += $output->writeString($this->tpr_data_11);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_12 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_12', TType::STRING, 15);
      $xfer += $output->writeString($this->tpr_data_12);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_1 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_1', TType::STRING, 16);
      $xfer += $output->writeString($this->tpr_data_1);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_2 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_2', TType::STRING, 17);
      $xfer += $output->writeString($this->tpr_data_2);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_3 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_3', TType::STRING, 18);
      $xfer += $output->writeString($this->tpr_data_3);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_data_4 !== null) {
      $xfer += $output->writeFieldBegin('tpr_data_4', TType::STRING, 19);
      $xfer += $output->writeString($this->tpr_data_4);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_status_reg !== null) {
      $xfer += $output->writeFieldBegin('tpr_status_reg', TType::I32, 20);
      $xfer += $output->writeI32($this->tpr_status_reg);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_updated_by !== null) {
      $xfer += $output->writeFieldBegin('tpr_updated_by', TType::I32, 21);
      $xfer += $output->writeI32($this->tpr_updated_by);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_updated !== null) {
      $xfer += $output->writeFieldBegin('tpr_updated', TType::STRING, 22);
      $xfer += $output->writeString($this->tpr_updated);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->tpr_created !== null) {
      $xfer += $output->writeFieldBegin('tpr_created', TType::STRING, 23);
      $xfer += $output->writeString($this->tpr_created);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

?>
