{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.BAN where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type BAN  =
    (RecCons Ban_id Expr (Maybe Int)
     (RecCons Ban_name Expr String
      (RecCons Ban_pai_id Expr Int
       (RecCons Ban_status_reg Expr String
        (RecCons Ban_updated_by Expr Int
         (RecCons Ban_updated Expr (Maybe CalendarTime)
          (RecCons Ban_created Expr (Maybe CalendarTime) RecNil)))))))

type BAN _result =
    (RecCons Ban_id ((Maybe Int))
     (RecCons Ban_name (String)
      (RecCons Ban_pai_id (Int)
       (RecCons Ban_status_reg (String)
        (RecCons Ban_updated_by (Int)
         (RecCons Ban_updated ((Maybe CalendarTime))
          (RecCons Ban_created ((Maybe CalendarTime)) RecNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
bAN :: Table BAN
bAN = baseTable "BAN" $
      hdbMakeEntry Ban_id #
      hdbMakeEntry Ban_name #
      hdbMakeEntry Ban_pai_id #
      hdbMakeEntry Ban_status_reg #
      hdbMakeEntry Ban_updated_by #
      hdbMakeEntry Ban_updated #
      hdbMakeEntry Ban_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ban_id Field
---------------------------------------------------------------------------

data Ban_id = Ban_id

instance FieldTag Ban_id where fieldName _ = "ban_id"

ban_id :: Attr Ban_id (Maybe Int)
ban_id = mkAttr Ban_id

---------------------------------------------------------------------------
-- Ban_name Field
---------------------------------------------------------------------------

data Ban_name = Ban_name

instance FieldTag Ban_name where fieldName _ = "ban_name"

ban_name :: Attr Ban_name String
ban_name = mkAttr Ban_name

---------------------------------------------------------------------------
-- Ban_pai_id Field
---------------------------------------------------------------------------

data Ban_pai_id = Ban_pai_id

instance FieldTag Ban_pai_id where fieldName _ = "ban_pai_id"

ban_pai_id :: Attr Ban_pai_id Int
ban_pai_id = mkAttr Ban_pai_id

---------------------------------------------------------------------------
-- Ban_status_reg Field
---------------------------------------------------------------------------

data Ban_status_reg = Ban_status_reg

instance FieldTag Ban_status_reg where
    fieldName _ = "ban_status_reg"

ban_status_reg :: Attr Ban_status_reg String
ban_status_reg = mkAttr Ban_status_reg

---------------------------------------------------------------------------
-- Ban_updated_by Field
---------------------------------------------------------------------------

data Ban_updated_by = Ban_updated_by

instance FieldTag Ban_updated_by where
    fieldName _ = "ban_updated_by"

ban_updated_by :: Attr Ban_updated_by Int
ban_updated_by = mkAttr Ban_updated_by

---------------------------------------------------------------------------
-- Ban_updated Field
---------------------------------------------------------------------------

data Ban_updated = Ban_updated

instance FieldTag Ban_updated where fieldName _ = "ban_updated"

ban_updated :: Attr Ban_updated (Maybe CalendarTime)
ban_updated = mkAttr Ban_updated

---------------------------------------------------------------------------
-- Ban_created Field
---------------------------------------------------------------------------

data Ban_created = Ban_created

instance FieldTag Ban_created where fieldName _ = "ban_created"

ban_created :: Attr Ban_created (Maybe CalendarTime)
ban_created = mkAttr Ban_created
