{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack52 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.CBA where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type CBA  =
    (RecCons Cba_id Expr (Maybe Int)
     (RecCons Cba_name Expr String
      (RecCons Cba_number Expr String
       (RecCons Cba_ban_id Expr Int
        (RecCons Cba_owner Expr String
         (RecCons Cba_obs Expr String
          (RecCons Cba_address Expr String
           (RecCons Cba_hot_id Expr (Maybe Int)
            (RecCons Cba_status_reg Expr String
             (RecCons Cba_updated_by Expr Int
              (RecCons Cba_updated Expr (Maybe CalendarTime)
               (RecCons Cba_created Expr (Maybe CalendarTime) RecNil))))))))))))

type CBA _result =
    (RecCons Cba_id ((Maybe Int))
     (RecCons Cba_name (String)
      (RecCons Cba_number (String)
       (RecCons Cba_ban_id (Int)
        (RecCons Cba_owner (String)
         (RecCons Cba_obs (String)
          (RecCons Cba_address (String)
           (RecCons Cba_hot_id ((Maybe Int))
            (RecCons Cba_status_reg (String)
             (RecCons Cba_updated_by (Int)
              (RecCons Cba_updated ((Maybe CalendarTime))
               (RecCons Cba_created ((Maybe CalendarTime)) RecNil))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
cBA :: Table CBA
cBA = baseTable "CBA" $
      hdbMakeEntry Cba_id #
      hdbMakeEntry Cba_name #
      hdbMakeEntry Cba_number #
      hdbMakeEntry Cba_ban_id #
      hdbMakeEntry Cba_owner #
      hdbMakeEntry Cba_obs #
      hdbMakeEntry Cba_address #
      hdbMakeEntry Cba_hot_id #
      hdbMakeEntry Cba_status_reg #
      hdbMakeEntry Cba_updated_by #
      hdbMakeEntry Cba_updated #
      hdbMakeEntry Cba_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Cba_id Field
---------------------------------------------------------------------------

data Cba_id = Cba_id

instance FieldTag Cba_id where fieldName _ = "cba_id"

cba_id :: Attr Cba_id (Maybe Int)
cba_id = mkAttr Cba_id

---------------------------------------------------------------------------
-- Cba_name Field
---------------------------------------------------------------------------

data Cba_name = Cba_name

instance FieldTag Cba_name where fieldName _ = "cba_name"

cba_name :: Attr Cba_name String
cba_name = mkAttr Cba_name

---------------------------------------------------------------------------
-- Cba_number Field
---------------------------------------------------------------------------

data Cba_number = Cba_number

instance FieldTag Cba_number where fieldName _ = "cba_number"

cba_number :: Attr Cba_number String
cba_number = mkAttr Cba_number

---------------------------------------------------------------------------
-- Cba_ban_id Field
---------------------------------------------------------------------------

data Cba_ban_id = Cba_ban_id

instance FieldTag Cba_ban_id where fieldName _ = "cba_ban_id"

cba_ban_id :: Attr Cba_ban_id Int
cba_ban_id = mkAttr Cba_ban_id

---------------------------------------------------------------------------
-- Cba_owner Field
---------------------------------------------------------------------------

data Cba_owner = Cba_owner

instance FieldTag Cba_owner where fieldName _ = "cba_owner"

cba_owner :: Attr Cba_owner String
cba_owner = mkAttr Cba_owner

---------------------------------------------------------------------------
-- Cba_obs Field
---------------------------------------------------------------------------

data Cba_obs = Cba_obs

instance FieldTag Cba_obs where fieldName _ = "cba_obs"

cba_obs :: Attr Cba_obs String
cba_obs = mkAttr Cba_obs

---------------------------------------------------------------------------
-- Cba_address Field
---------------------------------------------------------------------------

data Cba_address = Cba_address

instance FieldTag Cba_address where fieldName _ = "cba_address"

cba_address :: Attr Cba_address String
cba_address = mkAttr Cba_address

---------------------------------------------------------------------------
-- Cba_hot_id Field
---------------------------------------------------------------------------

data Cba_hot_id = Cba_hot_id

instance FieldTag Cba_hot_id where fieldName _ = "cba_hot_id"

cba_hot_id :: Attr Cba_hot_id (Maybe Int)
cba_hot_id = mkAttr Cba_hot_id

---------------------------------------------------------------------------
-- Cba_status_reg Field
---------------------------------------------------------------------------

data Cba_status_reg = Cba_status_reg

instance FieldTag Cba_status_reg where
    fieldName _ = "cba_status_reg"

cba_status_reg :: Attr Cba_status_reg String
cba_status_reg = mkAttr Cba_status_reg

---------------------------------------------------------------------------
-- Cba_updated_by Field
---------------------------------------------------------------------------

data Cba_updated_by = Cba_updated_by

instance FieldTag Cba_updated_by where
    fieldName _ = "cba_updated_by"

cba_updated_by :: Attr Cba_updated_by Int
cba_updated_by = mkAttr Cba_updated_by

---------------------------------------------------------------------------
-- Cba_updated Field
---------------------------------------------------------------------------

data Cba_updated = Cba_updated

instance FieldTag Cba_updated where fieldName _ = "cba_updated"

cba_updated :: Attr Cba_updated (Maybe CalendarTime)
cba_updated = mkAttr Cba_updated

---------------------------------------------------------------------------
-- Cba_created Field
---------------------------------------------------------------------------

data Cba_created = Cba_created

instance FieldTag Cba_created where fieldName _ = "cba_created"

cba_created :: Attr Cba_created (Maybe CalendarTime)
cba_created = mkAttr Cba_created
