{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack46 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.CDN where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type CDN  =
    (RecCons Cdn_id Expr (Maybe Int)
     (RecCons Cdn_name Expr String
      (RecCons Cdn_status_reg Expr String
       (RecCons Cdn_updated_by Expr Int
        (RecCons Cdn_updated Expr (Maybe CalendarTime)
         (RecCons Cdn_created Expr (Maybe CalendarTime) RecNil))))))

type CDN _result =
    (RecCons Cdn_id ((Maybe Int))
     (RecCons Cdn_name (String)
      (RecCons Cdn_status_reg (String)
       (RecCons Cdn_updated_by (Int)
        (RecCons Cdn_updated ((Maybe CalendarTime))
         (RecCons Cdn_created ((Maybe CalendarTime)) RecNil))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
cDN :: Table CDN
cDN = baseTable "CDN" $
      hdbMakeEntry Cdn_id #
      hdbMakeEntry Cdn_name #
      hdbMakeEntry Cdn_status_reg #
      hdbMakeEntry Cdn_updated_by #
      hdbMakeEntry Cdn_updated #
      hdbMakeEntry Cdn_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Cdn_id Field
---------------------------------------------------------------------------

data Cdn_id = Cdn_id

instance FieldTag Cdn_id where fieldName _ = "cdn_id"

cdn_id :: Attr Cdn_id (Maybe Int)
cdn_id = mkAttr Cdn_id

---------------------------------------------------------------------------
-- Cdn_name Field
---------------------------------------------------------------------------

data Cdn_name = Cdn_name

instance FieldTag Cdn_name where fieldName _ = "cdn_name"

cdn_name :: Attr Cdn_name String
cdn_name = mkAttr Cdn_name

---------------------------------------------------------------------------
-- Cdn_status_reg Field
---------------------------------------------------------------------------

data Cdn_status_reg = Cdn_status_reg

instance FieldTag Cdn_status_reg where
    fieldName _ = "cdn_status_reg"

cdn_status_reg :: Attr Cdn_status_reg String
cdn_status_reg = mkAttr Cdn_status_reg

---------------------------------------------------------------------------
-- Cdn_updated_by Field
---------------------------------------------------------------------------

data Cdn_updated_by = Cdn_updated_by

instance FieldTag Cdn_updated_by where
    fieldName _ = "cdn_updated_by"

cdn_updated_by :: Attr Cdn_updated_by Int
cdn_updated_by = mkAttr Cdn_updated_by

---------------------------------------------------------------------------
-- Cdn_updated Field
---------------------------------------------------------------------------

data Cdn_updated = Cdn_updated

instance FieldTag Cdn_updated where fieldName _ = "cdn_updated"

cdn_updated :: Attr Cdn_updated (Maybe CalendarTime)
cdn_updated = mkAttr Cdn_updated

---------------------------------------------------------------------------
-- Cdn_created Field
---------------------------------------------------------------------------

data Cdn_created = Cdn_created

instance FieldTag Cdn_created where fieldName _ = "cdn_created"

cdn_created :: Attr Cdn_created (Maybe CalendarTime)
cdn_created = mkAttr Cdn_created
