{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack56 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.CLI where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type CLI  =
    (RecCons Cli_id Expr (Maybe Int)
     (RecCons Cli_name Expr String
      (RecCons Cli_first_name Expr String
       (RecCons Cli_last_name Expr String
        (RecCons Cli_ci Expr String
         (RecCons Cli_cellphone Expr String
          (RecCons Cli_phone Expr String
           (RecCons Cli_email Expr String
            (RecCons Cli_type Expr String
             (RecCons Cli_obs Expr (Maybe String)
              (RecCons Cli_hot_id Expr Int
               (RecCons Cli_usr_id Expr (Maybe Int)
                (RecCons Cli_status_reg Expr String
                 (RecCons Cli_updated_by Expr Int
                  (RecCons Cli_updated Expr (Maybe CalendarTime)
                   (RecCons Cli_created Expr (Maybe CalendarTime) RecNil))))))))))))))))

type CLI _result =
    (RecCons Cli_id ((Maybe Int))
     (RecCons Cli_name (String)
      (RecCons Cli_first_name (String)
       (RecCons Cli_last_name (String)
        (RecCons Cli_ci (String)
         (RecCons Cli_cellphone (String)
          (RecCons Cli_phone (String)
           (RecCons Cli_email (String)
            (RecCons Cli_type (String)
             (RecCons Cli_obs ((Maybe String))
              (RecCons Cli_hot_id (Int)
               (RecCons Cli_usr_id ((Maybe Int))
                (RecCons Cli_status_reg (String)
                 (RecCons Cli_updated_by (Int)
                  (RecCons Cli_updated ((Maybe CalendarTime))
                   (RecCons Cli_created ((Maybe CalendarTime)) RecNil))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
cLI :: Table CLI
cLI = baseTable "CLI" $
      hdbMakeEntry Cli_id #
      hdbMakeEntry Cli_name #
      hdbMakeEntry Cli_first_name #
      hdbMakeEntry Cli_last_name #
      hdbMakeEntry Cli_ci #
      hdbMakeEntry Cli_cellphone #
      hdbMakeEntry Cli_phone #
      hdbMakeEntry Cli_email #
      hdbMakeEntry Cli_type #
      hdbMakeEntry Cli_obs #
      hdbMakeEntry Cli_hot_id #
      hdbMakeEntry Cli_usr_id #
      hdbMakeEntry Cli_status_reg #
      hdbMakeEntry Cli_updated_by #
      hdbMakeEntry Cli_updated #
      hdbMakeEntry Cli_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Cli_id Field
---------------------------------------------------------------------------

data Cli_id = Cli_id

instance FieldTag Cli_id where fieldName _ = "cli_id"

cli_id :: Attr Cli_id (Maybe Int)
cli_id = mkAttr Cli_id

---------------------------------------------------------------------------
-- Cli_name Field
---------------------------------------------------------------------------

data Cli_name = Cli_name

instance FieldTag Cli_name where fieldName _ = "cli_name"

cli_name :: Attr Cli_name String
cli_name = mkAttr Cli_name

---------------------------------------------------------------------------
-- Cli_first_name Field
---------------------------------------------------------------------------

data Cli_first_name = Cli_first_name

instance FieldTag Cli_first_name where
    fieldName _ = "cli_first_name"

cli_first_name :: Attr Cli_first_name String
cli_first_name = mkAttr Cli_first_name

---------------------------------------------------------------------------
-- Cli_last_name Field
---------------------------------------------------------------------------

data Cli_last_name = Cli_last_name

instance FieldTag Cli_last_name where
    fieldName _ = "cli_last_name"

cli_last_name :: Attr Cli_last_name String
cli_last_name = mkAttr Cli_last_name

---------------------------------------------------------------------------
-- Cli_ci Field
---------------------------------------------------------------------------

data Cli_ci = Cli_ci

instance FieldTag Cli_ci where fieldName _ = "cli_ci"

cli_ci :: Attr Cli_ci String
cli_ci = mkAttr Cli_ci

---------------------------------------------------------------------------
-- Cli_cellphone Field
---------------------------------------------------------------------------

data Cli_cellphone = Cli_cellphone

instance FieldTag Cli_cellphone where
    fieldName _ = "cli_cellphone"

cli_cellphone :: Attr Cli_cellphone String
cli_cellphone = mkAttr Cli_cellphone

---------------------------------------------------------------------------
-- Cli_phone Field
---------------------------------------------------------------------------

data Cli_phone = Cli_phone

instance FieldTag Cli_phone where fieldName _ = "cli_phone"

cli_phone :: Attr Cli_phone String
cli_phone = mkAttr Cli_phone

---------------------------------------------------------------------------
-- Cli_email Field
---------------------------------------------------------------------------

data Cli_email = Cli_email

instance FieldTag Cli_email where fieldName _ = "cli_email"

cli_email :: Attr Cli_email String
cli_email = mkAttr Cli_email

---------------------------------------------------------------------------
-- Cli_type Field
---------------------------------------------------------------------------

data Cli_type = Cli_type

instance FieldTag Cli_type where fieldName _ = "cli_type"

cli_type :: Attr Cli_type String
cli_type = mkAttr Cli_type

---------------------------------------------------------------------------
-- Cli_obs Field
---------------------------------------------------------------------------

data Cli_obs = Cli_obs

instance FieldTag Cli_obs where fieldName _ = "cli_obs"

cli_obs :: Attr Cli_obs (Maybe String)
cli_obs = mkAttr Cli_obs

---------------------------------------------------------------------------
-- Cli_hot_id Field
---------------------------------------------------------------------------

data Cli_hot_id = Cli_hot_id

instance FieldTag Cli_hot_id where fieldName _ = "cli_hot_id"

cli_hot_id :: Attr Cli_hot_id Int
cli_hot_id = mkAttr Cli_hot_id

---------------------------------------------------------------------------
-- Cli_usr_id Field
---------------------------------------------------------------------------

data Cli_usr_id = Cli_usr_id

instance FieldTag Cli_usr_id where fieldName _ = "cli_usr_id"

cli_usr_id :: Attr Cli_usr_id (Maybe Int)
cli_usr_id = mkAttr Cli_usr_id

---------------------------------------------------------------------------
-- Cli_status_reg Field
---------------------------------------------------------------------------

data Cli_status_reg = Cli_status_reg

instance FieldTag Cli_status_reg where
    fieldName _ = "cli_status_reg"

cli_status_reg :: Attr Cli_status_reg String
cli_status_reg = mkAttr Cli_status_reg

---------------------------------------------------------------------------
-- Cli_updated_by Field
---------------------------------------------------------------------------

data Cli_updated_by = Cli_updated_by

instance FieldTag Cli_updated_by where
    fieldName _ = "cli_updated_by"

cli_updated_by :: Attr Cli_updated_by Int
cli_updated_by = mkAttr Cli_updated_by

---------------------------------------------------------------------------
-- Cli_updated Field
---------------------------------------------------------------------------

data Cli_updated = Cli_updated

instance FieldTag Cli_updated where fieldName _ = "cli_updated"

cli_updated :: Attr Cli_updated (Maybe CalendarTime)
cli_updated = mkAttr Cli_updated

---------------------------------------------------------------------------
-- Cli_created Field
---------------------------------------------------------------------------

data Cli_created = Cli_created

instance FieldTag Cli_created where fieldName _ = "cli_created"

cli_created :: Attr Cli_created (Maybe CalendarTime)
cli_created = mkAttr Cli_created
