{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack52 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.CUP where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type CUP  =
    (RecCons Cup_id Expr (Maybe Int)
     (RecCons Cup_tha_id Expr Int
      (RecCons Cup_day Expr Int
       (RecCons Cup_glo_tot Expr Int
        (RecCons Cup_reg_res Expr Int
         (RecCons Cup_web_tot Expr Int
          (RecCons Cup_web_res Expr Int
           (RecCons Cup_ids_tot Expr Int
            (RecCons Cup_ids_res Expr Int
             (RecCons Cup_updated_by Expr Int
              (RecCons Cup_updated Expr (Maybe CalendarTime)
               (RecCons Cup_created Expr (Maybe CalendarTime) RecNil))))))))))))

type CUP _result =
    (RecCons Cup_id ((Maybe Int))
     (RecCons Cup_tha_id (Int)
      (RecCons Cup_day (Int)
       (RecCons Cup_glo_tot (Int)
        (RecCons Cup_reg_res (Int)
         (RecCons Cup_web_tot (Int)
          (RecCons Cup_web_res (Int)
           (RecCons Cup_ids_tot (Int)
            (RecCons Cup_ids_res (Int)
             (RecCons Cup_updated_by (Int)
              (RecCons Cup_updated ((Maybe CalendarTime))
               (RecCons Cup_created ((Maybe CalendarTime)) RecNil))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
cUP :: Table CUP
cUP = baseTable "CUP" $
      hdbMakeEntry Cup_id #
      hdbMakeEntry Cup_tha_id #
      hdbMakeEntry Cup_day #
      hdbMakeEntry Cup_glo_tot #
      hdbMakeEntry Cup_reg_res #
      hdbMakeEntry Cup_web_tot #
      hdbMakeEntry Cup_web_res #
      hdbMakeEntry Cup_ids_tot #
      hdbMakeEntry Cup_ids_res #
      hdbMakeEntry Cup_updated_by #
      hdbMakeEntry Cup_updated #
      hdbMakeEntry Cup_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Cup_id Field
---------------------------------------------------------------------------

data Cup_id = Cup_id

instance FieldTag Cup_id where fieldName _ = "cup_id"

cup_id :: Attr Cup_id (Maybe Int)
cup_id = mkAttr Cup_id

---------------------------------------------------------------------------
-- Cup_tha_id Field
---------------------------------------------------------------------------

data Cup_tha_id = Cup_tha_id

instance FieldTag Cup_tha_id where fieldName _ = "cup_tha_id"

cup_tha_id :: Attr Cup_tha_id Int
cup_tha_id = mkAttr Cup_tha_id

---------------------------------------------------------------------------
-- Cup_day Field
---------------------------------------------------------------------------

data Cup_day = Cup_day

instance FieldTag Cup_day where fieldName _ = "cup_day"

cup_day :: Attr Cup_day Int
cup_day = mkAttr Cup_day

---------------------------------------------------------------------------
-- Cup_glo_tot Field
---------------------------------------------------------------------------

data Cup_glo_tot = Cup_glo_tot

instance FieldTag Cup_glo_tot where fieldName _ = "cup_glo_tot"

cup_glo_tot :: Attr Cup_glo_tot Int
cup_glo_tot = mkAttr Cup_glo_tot

---------------------------------------------------------------------------
-- Cup_reg_res Field
---------------------------------------------------------------------------

data Cup_reg_res = Cup_reg_res

instance FieldTag Cup_reg_res where fieldName _ = "cup_reg_res"

cup_reg_res :: Attr Cup_reg_res Int
cup_reg_res = mkAttr Cup_reg_res

---------------------------------------------------------------------------
-- Cup_web_tot Field
---------------------------------------------------------------------------

data Cup_web_tot = Cup_web_tot

instance FieldTag Cup_web_tot where fieldName _ = "cup_web_tot"

cup_web_tot :: Attr Cup_web_tot Int
cup_web_tot = mkAttr Cup_web_tot

---------------------------------------------------------------------------
-- Cup_web_res Field
---------------------------------------------------------------------------

data Cup_web_res = Cup_web_res

instance FieldTag Cup_web_res where fieldName _ = "cup_web_res"

cup_web_res :: Attr Cup_web_res Int
cup_web_res = mkAttr Cup_web_res

---------------------------------------------------------------------------
-- Cup_ids_tot Field
---------------------------------------------------------------------------

data Cup_ids_tot = Cup_ids_tot

instance FieldTag Cup_ids_tot where fieldName _ = "cup_ids_tot"

cup_ids_tot :: Attr Cup_ids_tot Int
cup_ids_tot = mkAttr Cup_ids_tot

---------------------------------------------------------------------------
-- Cup_ids_res Field
---------------------------------------------------------------------------

data Cup_ids_res = Cup_ids_res

instance FieldTag Cup_ids_res where fieldName _ = "cup_ids_res"

cup_ids_res :: Attr Cup_ids_res Int
cup_ids_res = mkAttr Cup_ids_res

---------------------------------------------------------------------------
-- Cup_updated_by Field
---------------------------------------------------------------------------

data Cup_updated_by = Cup_updated_by

instance FieldTag Cup_updated_by where
    fieldName _ = "cup_updated_by"

cup_updated_by :: Attr Cup_updated_by Int
cup_updated_by = mkAttr Cup_updated_by

---------------------------------------------------------------------------
-- Cup_updated Field
---------------------------------------------------------------------------

data Cup_updated = Cup_updated

instance FieldTag Cup_updated where fieldName _ = "cup_updated"

cup_updated :: Attr Cup_updated (Maybe CalendarTime)
cup_updated = mkAttr Cup_updated

---------------------------------------------------------------------------
-- Cup_created Field
---------------------------------------------------------------------------

data Cup_created = Cup_created

instance FieldTag Cup_created where fieldName _ = "cup_created"

cup_created :: Attr Cup_created (Maybe CalendarTime)
cup_created = mkAttr Cup_created
