{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack57 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.CVI where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type CVI  =
    (RecCons Cvi_id Expr (Maybe Int)
     (RecCons Cvi_usr_id Expr Int
      (RecCons Cvi_trip_purpose Expr String
       (RecCons Cvi_near_transport Expr Int
        (RecCons Cvi_near_restaurant Expr Int
         (RecCons Cvi_near_commercial Expr Int
          (RecCons Cvi_staff_quality Expr Int
           (RecCons Cvi_luxury Expr Int
            (RecCons Cvi_comfort Expr Int
             (RecCons Cvi_quiescence Expr Int
              (RecCons Cvi_restaurant_quality Expr Int
               (RecCons Cvi_breakfast_included Expr Int
                (RecCons Cvi_all_included Expr Int
                 (RecCons Cvi_status_reg Expr String
                  (RecCons Cvi_updated_by Expr Int
                   (RecCons Cvi_updated Expr (Maybe CalendarTime)
                    (RecCons Cvi_created Expr (Maybe CalendarTime) RecNil)))))))))))))))))

type CVI _result =
    (RecCons Cvi_id ((Maybe Int))
     (RecCons Cvi_usr_id (Int)
      (RecCons Cvi_trip_purpose (String)
       (RecCons Cvi_near_transport (Int)
        (RecCons Cvi_near_restaurant (Int)
         (RecCons Cvi_near_commercial (Int)
          (RecCons Cvi_staff_quality (Int)
           (RecCons Cvi_luxury (Int)
            (RecCons Cvi_comfort (Int)
             (RecCons Cvi_quiescence (Int)
              (RecCons Cvi_restaurant_quality (Int)
               (RecCons Cvi_breakfast_included (Int)
                (RecCons Cvi_all_included (Int)
                 (RecCons Cvi_status_reg (String)
                  (RecCons Cvi_updated_by (Int)
                   (RecCons Cvi_updated ((Maybe CalendarTime))
                    (RecCons Cvi_created ((Maybe CalendarTime)) RecNil)))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
cVI :: Table CVI
cVI = baseTable "CVI" $
      hdbMakeEntry Cvi_id #
      hdbMakeEntry Cvi_usr_id #
      hdbMakeEntry Cvi_trip_purpose #
      hdbMakeEntry Cvi_near_transport #
      hdbMakeEntry Cvi_near_restaurant #
      hdbMakeEntry Cvi_near_commercial #
      hdbMakeEntry Cvi_staff_quality #
      hdbMakeEntry Cvi_luxury #
      hdbMakeEntry Cvi_comfort #
      hdbMakeEntry Cvi_quiescence #
      hdbMakeEntry Cvi_restaurant_quality #
      hdbMakeEntry Cvi_breakfast_included #
      hdbMakeEntry Cvi_all_included #
      hdbMakeEntry Cvi_status_reg #
      hdbMakeEntry Cvi_updated_by #
      hdbMakeEntry Cvi_updated #
      hdbMakeEntry Cvi_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Cvi_id Field
---------------------------------------------------------------------------

data Cvi_id = Cvi_id

instance FieldTag Cvi_id where fieldName _ = "cvi_id"

cvi_id :: Attr Cvi_id (Maybe Int)
cvi_id = mkAttr Cvi_id

---------------------------------------------------------------------------
-- Cvi_usr_id Field
---------------------------------------------------------------------------

data Cvi_usr_id = Cvi_usr_id

instance FieldTag Cvi_usr_id where fieldName _ = "cvi_usr_id"

cvi_usr_id :: Attr Cvi_usr_id Int
cvi_usr_id = mkAttr Cvi_usr_id

---------------------------------------------------------------------------
-- Cvi_trip_purpose Field
---------------------------------------------------------------------------

data Cvi_trip_purpose = Cvi_trip_purpose

instance FieldTag Cvi_trip_purpose where
    fieldName _ = "cvi_trip_purpose"

cvi_trip_purpose :: Attr Cvi_trip_purpose String
cvi_trip_purpose = mkAttr Cvi_trip_purpose

---------------------------------------------------------------------------
-- Cvi_near_transport Field
---------------------------------------------------------------------------

data Cvi_near_transport = Cvi_near_transport

instance FieldTag Cvi_near_transport where
    fieldName _ = "cvi_near_transport"

cvi_near_transport :: Attr Cvi_near_transport Int
cvi_near_transport = mkAttr Cvi_near_transport

---------------------------------------------------------------------------
-- Cvi_near_restaurant Field
---------------------------------------------------------------------------

data Cvi_near_restaurant = Cvi_near_restaurant

instance FieldTag Cvi_near_restaurant where
    fieldName _ = "cvi_near_restaurant"

cvi_near_restaurant :: Attr Cvi_near_restaurant Int
cvi_near_restaurant = mkAttr Cvi_near_restaurant

---------------------------------------------------------------------------
-- Cvi_near_commercial Field
---------------------------------------------------------------------------

data Cvi_near_commercial = Cvi_near_commercial

instance FieldTag Cvi_near_commercial where
    fieldName _ = "cvi_near_commercial"

cvi_near_commercial :: Attr Cvi_near_commercial Int
cvi_near_commercial = mkAttr Cvi_near_commercial

---------------------------------------------------------------------------
-- Cvi_staff_quality Field
---------------------------------------------------------------------------

data Cvi_staff_quality = Cvi_staff_quality

instance FieldTag Cvi_staff_quality where
    fieldName _ = "cvi_staff_quality"

cvi_staff_quality :: Attr Cvi_staff_quality Int
cvi_staff_quality = mkAttr Cvi_staff_quality

---------------------------------------------------------------------------
-- Cvi_luxury Field
---------------------------------------------------------------------------

data Cvi_luxury = Cvi_luxury

instance FieldTag Cvi_luxury where fieldName _ = "cvi_luxury"

cvi_luxury :: Attr Cvi_luxury Int
cvi_luxury = mkAttr Cvi_luxury

---------------------------------------------------------------------------
-- Cvi_comfort Field
---------------------------------------------------------------------------

data Cvi_comfort = Cvi_comfort

instance FieldTag Cvi_comfort where fieldName _ = "cvi_comfort"

cvi_comfort :: Attr Cvi_comfort Int
cvi_comfort = mkAttr Cvi_comfort

---------------------------------------------------------------------------
-- Cvi_quiescence Field
---------------------------------------------------------------------------

data Cvi_quiescence = Cvi_quiescence

instance FieldTag Cvi_quiescence where
    fieldName _ = "cvi_quiescence"

cvi_quiescence :: Attr Cvi_quiescence Int
cvi_quiescence = mkAttr Cvi_quiescence

---------------------------------------------------------------------------
-- Cvi_restaurant_quality Field
---------------------------------------------------------------------------

data Cvi_restaurant_quality = Cvi_restaurant_quality

instance FieldTag Cvi_restaurant_quality where
    fieldName _ = "cvi_restaurant_quality"

cvi_restaurant_quality :: Attr Cvi_restaurant_quality Int
cvi_restaurant_quality = mkAttr Cvi_restaurant_quality

---------------------------------------------------------------------------
-- Cvi_breakfast_included Field
---------------------------------------------------------------------------

data Cvi_breakfast_included = Cvi_breakfast_included

instance FieldTag Cvi_breakfast_included where
    fieldName _ = "cvi_breakfast_included"

cvi_breakfast_included :: Attr Cvi_breakfast_included Int
cvi_breakfast_included = mkAttr Cvi_breakfast_included

---------------------------------------------------------------------------
-- Cvi_all_included Field
---------------------------------------------------------------------------

data Cvi_all_included = Cvi_all_included

instance FieldTag Cvi_all_included where
    fieldName _ = "cvi_all_included"

cvi_all_included :: Attr Cvi_all_included Int
cvi_all_included = mkAttr Cvi_all_included

---------------------------------------------------------------------------
-- Cvi_status_reg Field
---------------------------------------------------------------------------

data Cvi_status_reg = Cvi_status_reg

instance FieldTag Cvi_status_reg where
    fieldName _ = "cvi_status_reg"

cvi_status_reg :: Attr Cvi_status_reg String
cvi_status_reg = mkAttr Cvi_status_reg

---------------------------------------------------------------------------
-- Cvi_updated_by Field
---------------------------------------------------------------------------

data Cvi_updated_by = Cvi_updated_by

instance FieldTag Cvi_updated_by where
    fieldName _ = "cvi_updated_by"

cvi_updated_by :: Attr Cvi_updated_by Int
cvi_updated_by = mkAttr Cvi_updated_by

---------------------------------------------------------------------------
-- Cvi_updated Field
---------------------------------------------------------------------------

data Cvi_updated = Cvi_updated

instance FieldTag Cvi_updated where fieldName _ = "cvi_updated"

cvi_updated :: Attr Cvi_updated (Maybe CalendarTime)
cvi_updated = mkAttr Cvi_updated

---------------------------------------------------------------------------
-- Cvi_created Field
---------------------------------------------------------------------------

data Cvi_created = Cvi_created

instance FieldTag Cvi_created where fieldName _ = "cvi_created"

cvi_created :: Attr Cvi_created (Maybe CalendarTime)
cvi_created = mkAttr Cvi_created
