{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.DES where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type DES  =
    (RecCons Des_id Expr (Maybe Int)
     (RecCons Des_name Expr String
      (RecCons Des_pai_id Expr Int
       (RecCons Des_approval Expr String
        (RecCons Des_status_reg Expr String
         (RecCons Des_updated_by Expr Int
          (RecCons Des_updated Expr (Maybe CalendarTime)
           (RecCons Des_created Expr (Maybe CalendarTime) RecNil))))))))

type DES _result =
    (RecCons Des_id ((Maybe Int))
     (RecCons Des_name (String)
      (RecCons Des_pai_id (Int)
       (RecCons Des_approval (String)
        (RecCons Des_status_reg (String)
         (RecCons Des_updated_by (Int)
          (RecCons Des_updated ((Maybe CalendarTime))
           (RecCons Des_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
dES :: Table DES
dES = baseTable "DES" $
      hdbMakeEntry Des_id #
      hdbMakeEntry Des_name #
      hdbMakeEntry Des_pai_id #
      hdbMakeEntry Des_approval #
      hdbMakeEntry Des_status_reg #
      hdbMakeEntry Des_updated_by #
      hdbMakeEntry Des_updated #
      hdbMakeEntry Des_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Des_id Field
---------------------------------------------------------------------------

data Des_id = Des_id

instance FieldTag Des_id where fieldName _ = "des_id"

des_id :: Attr Des_id (Maybe Int)
des_id = mkAttr Des_id

---------------------------------------------------------------------------
-- Des_name Field
---------------------------------------------------------------------------

data Des_name = Des_name

instance FieldTag Des_name where fieldName _ = "des_name"

des_name :: Attr Des_name String
des_name = mkAttr Des_name

---------------------------------------------------------------------------
-- Des_pai_id Field
---------------------------------------------------------------------------

data Des_pai_id = Des_pai_id

instance FieldTag Des_pai_id where fieldName _ = "des_pai_id"

des_pai_id :: Attr Des_pai_id Int
des_pai_id = mkAttr Des_pai_id

---------------------------------------------------------------------------
-- Des_approval Field
---------------------------------------------------------------------------

data Des_approval = Des_approval

instance FieldTag Des_approval where fieldName _ = "des_approval"

des_approval :: Attr Des_approval String
des_approval = mkAttr Des_approval

---------------------------------------------------------------------------
-- Des_status_reg Field
---------------------------------------------------------------------------

data Des_status_reg = Des_status_reg

instance FieldTag Des_status_reg where
    fieldName _ = "des_status_reg"

des_status_reg :: Attr Des_status_reg String
des_status_reg = mkAttr Des_status_reg

---------------------------------------------------------------------------
-- Des_updated_by Field
---------------------------------------------------------------------------

data Des_updated_by = Des_updated_by

instance FieldTag Des_updated_by where
    fieldName _ = "des_updated_by"

des_updated_by :: Attr Des_updated_by Int
des_updated_by = mkAttr Des_updated_by

---------------------------------------------------------------------------
-- Des_updated Field
---------------------------------------------------------------------------

data Des_updated = Des_updated

instance FieldTag Des_updated where fieldName _ = "des_updated"

des_updated :: Attr Des_updated (Maybe CalendarTime)
des_updated = mkAttr Des_updated

---------------------------------------------------------------------------
-- Des_created Field
---------------------------------------------------------------------------

data Des_created = Des_created

instance FieldTag Des_created where fieldName _ = "des_created"

des_created :: Attr Des_created (Maybe CalendarTime)
des_created = mkAttr Des_created
