{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.EDO where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type EDO  =
    (RecCons Edo_id Expr (Maybe Int)
     (RecCons Edo_pai_id Expr Int
      (RecCons Edo_name Expr String
       (RecCons Edo_approval Expr String
        (RecCons Edo_status_reg Expr String
         (RecCons Edo_updated_by Expr Int
          (RecCons Edo_updated Expr (Maybe CalendarTime)
           (RecCons Edo_created Expr (Maybe CalendarTime) RecNil))))))))

type EDO _result =
    (RecCons Edo_id ((Maybe Int))
     (RecCons Edo_pai_id (Int)
      (RecCons Edo_name (String)
       (RecCons Edo_approval (String)
        (RecCons Edo_status_reg (String)
         (RecCons Edo_updated_by (Int)
          (RecCons Edo_updated ((Maybe CalendarTime))
           (RecCons Edo_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
eDO :: Table EDO
eDO = baseTable "EDO" $
      hdbMakeEntry Edo_id #
      hdbMakeEntry Edo_pai_id #
      hdbMakeEntry Edo_name #
      hdbMakeEntry Edo_approval #
      hdbMakeEntry Edo_status_reg #
      hdbMakeEntry Edo_updated_by #
      hdbMakeEntry Edo_updated #
      hdbMakeEntry Edo_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Edo_id Field
---------------------------------------------------------------------------

data Edo_id = Edo_id

instance FieldTag Edo_id where fieldName _ = "edo_id"

edo_id :: Attr Edo_id (Maybe Int)
edo_id = mkAttr Edo_id

---------------------------------------------------------------------------
-- Edo_pai_id Field
---------------------------------------------------------------------------

data Edo_pai_id = Edo_pai_id

instance FieldTag Edo_pai_id where fieldName _ = "edo_pai_id"

edo_pai_id :: Attr Edo_pai_id Int
edo_pai_id = mkAttr Edo_pai_id

---------------------------------------------------------------------------
-- Edo_name Field
---------------------------------------------------------------------------

data Edo_name = Edo_name

instance FieldTag Edo_name where fieldName _ = "edo_name"

edo_name :: Attr Edo_name String
edo_name = mkAttr Edo_name

---------------------------------------------------------------------------
-- Edo_approval Field
---------------------------------------------------------------------------

data Edo_approval = Edo_approval

instance FieldTag Edo_approval where fieldName _ = "edo_approval"

edo_approval :: Attr Edo_approval String
edo_approval = mkAttr Edo_approval

---------------------------------------------------------------------------
-- Edo_status_reg Field
---------------------------------------------------------------------------

data Edo_status_reg = Edo_status_reg

instance FieldTag Edo_status_reg where
    fieldName _ = "edo_status_reg"

edo_status_reg :: Attr Edo_status_reg String
edo_status_reg = mkAttr Edo_status_reg

---------------------------------------------------------------------------
-- Edo_updated_by Field
---------------------------------------------------------------------------

data Edo_updated_by = Edo_updated_by

instance FieldTag Edo_updated_by where
    fieldName _ = "edo_updated_by"

edo_updated_by :: Attr Edo_updated_by Int
edo_updated_by = mkAttr Edo_updated_by

---------------------------------------------------------------------------
-- Edo_updated Field
---------------------------------------------------------------------------

data Edo_updated = Edo_updated

instance FieldTag Edo_updated where fieldName _ = "edo_updated"

edo_updated :: Attr Edo_updated (Maybe CalendarTime)
edo_updated = mkAttr Edo_updated

---------------------------------------------------------------------------
-- Edo_created Field
---------------------------------------------------------------------------

data Edo_created = Edo_created

instance FieldTag Edo_created where fieldName _ = "edo_created"

edo_created :: Attr Edo_created (Maybe CalendarTime)
edo_created = mkAttr Edo_created
