{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack60 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.EPH where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type EPH  =
    (RecCons Eph_id Expr (Maybe Int)
     (RecCons Eph_hot_id Expr Int
      (RecCons Eph_fac_id Expr (Maybe Int)
       (RecCons Eph_type Expr String
        (RecCons Eph_mon_id Expr Int
         (RecCons Eph_amount Expr Integer
          (RecCons Eph_amount_fac Expr Integer
           (RecCons Eph_sum Expr Integer
            (RecCons Eph_payoff Expr (Maybe Int)
             (RecCons Eph_payoff_date Expr (Maybe String)
              (RecCons Eph_reverse Expr (Maybe Int)
               (RecCons Eph_pag_id Expr (Maybe Int)
                (RecCons Eph_plc_id Expr (Maybe Int)
                 (RecCons Eph_res_id Expr (Maybe Int)
                  (RecCons Eph_covered Expr (Maybe Int)
                   (RecCons Eph_confirmed Expr (Maybe String)
                    (RecCons Eph_status_reg Expr String
                     (RecCons Eph_updated_by Expr Int
                      (RecCons Eph_updated Expr (Maybe CalendarTime)
                       (RecCons Eph_created Expr (Maybe CalendarTime) RecNil))))))))))))))))))))

type EPH _result =
    (RecCons Eph_id ((Maybe Int))
     (RecCons Eph_hot_id (Int)
      (RecCons Eph_fac_id ((Maybe Int))
       (RecCons Eph_type (String)
        (RecCons Eph_mon_id (Int)
         (RecCons Eph_amount (Integer)
          (RecCons Eph_amount_fac (Integer)
           (RecCons Eph_sum (Integer)
            (RecCons Eph_payoff ((Maybe Int))
             (RecCons Eph_payoff_date ((Maybe String))
              (RecCons Eph_reverse ((Maybe Int))
               (RecCons Eph_pag_id ((Maybe Int))
                (RecCons Eph_plc_id ((Maybe Int))
                 (RecCons Eph_res_id ((Maybe Int))
                  (RecCons Eph_covered ((Maybe Int))
                   (RecCons Eph_confirmed ((Maybe String))
                    (RecCons Eph_status_reg (String)
                     (RecCons Eph_updated_by (Int)
                      (RecCons Eph_updated ((Maybe CalendarTime))
                       (RecCons Eph_created ((Maybe CalendarTime)) RecNil))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
ePH :: Table EPH
ePH = baseTable "EPH" $
      hdbMakeEntry Eph_id #
      hdbMakeEntry Eph_hot_id #
      hdbMakeEntry Eph_fac_id #
      hdbMakeEntry Eph_type #
      hdbMakeEntry Eph_mon_id #
      hdbMakeEntry Eph_amount #
      hdbMakeEntry Eph_amount_fac #
      hdbMakeEntry Eph_sum #
      hdbMakeEntry Eph_payoff #
      hdbMakeEntry Eph_payoff_date #
      hdbMakeEntry Eph_reverse #
      hdbMakeEntry Eph_pag_id #
      hdbMakeEntry Eph_plc_id #
      hdbMakeEntry Eph_res_id #
      hdbMakeEntry Eph_covered #
      hdbMakeEntry Eph_confirmed #
      hdbMakeEntry Eph_status_reg #
      hdbMakeEntry Eph_updated_by #
      hdbMakeEntry Eph_updated #
      hdbMakeEntry Eph_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Eph_id Field
---------------------------------------------------------------------------

data Eph_id = Eph_id

instance FieldTag Eph_id where fieldName _ = "eph_id"

eph_id :: Attr Eph_id (Maybe Int)
eph_id = mkAttr Eph_id

---------------------------------------------------------------------------
-- Eph_hot_id Field
---------------------------------------------------------------------------

data Eph_hot_id = Eph_hot_id

instance FieldTag Eph_hot_id where fieldName _ = "eph_hot_id"

eph_hot_id :: Attr Eph_hot_id Int
eph_hot_id = mkAttr Eph_hot_id

---------------------------------------------------------------------------
-- Eph_fac_id Field
---------------------------------------------------------------------------

data Eph_fac_id = Eph_fac_id

instance FieldTag Eph_fac_id where fieldName _ = "eph_fac_id"

eph_fac_id :: Attr Eph_fac_id (Maybe Int)
eph_fac_id = mkAttr Eph_fac_id

---------------------------------------------------------------------------
-- Eph_type Field
---------------------------------------------------------------------------

data Eph_type = Eph_type

instance FieldTag Eph_type where fieldName _ = "eph_type"

eph_type :: Attr Eph_type String
eph_type = mkAttr Eph_type

---------------------------------------------------------------------------
-- Eph_mon_id Field
---------------------------------------------------------------------------

data Eph_mon_id = Eph_mon_id

instance FieldTag Eph_mon_id where fieldName _ = "eph_mon_id"

eph_mon_id :: Attr Eph_mon_id Int
eph_mon_id = mkAttr Eph_mon_id

---------------------------------------------------------------------------
-- Eph_amount Field
---------------------------------------------------------------------------

data Eph_amount = Eph_amount

instance FieldTag Eph_amount where fieldName _ = "eph_amount"

eph_amount :: Attr Eph_amount Integer
eph_amount = mkAttr Eph_amount

---------------------------------------------------------------------------
-- Eph_amount_fac Field
---------------------------------------------------------------------------

data Eph_amount_fac = Eph_amount_fac

instance FieldTag Eph_amount_fac where
    fieldName _ = "eph_amount_fac"

eph_amount_fac :: Attr Eph_amount_fac Integer
eph_amount_fac = mkAttr Eph_amount_fac

---------------------------------------------------------------------------
-- Eph_sum Field
---------------------------------------------------------------------------

data Eph_sum = Eph_sum

instance FieldTag Eph_sum where fieldName _ = "eph_sum"

eph_sum :: Attr Eph_sum Integer
eph_sum = mkAttr Eph_sum

---------------------------------------------------------------------------
-- Eph_payoff Field
---------------------------------------------------------------------------

data Eph_payoff = Eph_payoff

instance FieldTag Eph_payoff where fieldName _ = "eph_payoff"

eph_payoff :: Attr Eph_payoff (Maybe Int)
eph_payoff = mkAttr Eph_payoff

---------------------------------------------------------------------------
-- Eph_payoff_date Field
---------------------------------------------------------------------------

data Eph_payoff_date = Eph_payoff_date

instance FieldTag Eph_payoff_date where
    fieldName _ = "eph_payoff_date"

eph_payoff_date :: Attr Eph_payoff_date (Maybe String)
eph_payoff_date = mkAttr Eph_payoff_date

---------------------------------------------------------------------------
-- Eph_reverse Field
---------------------------------------------------------------------------

data Eph_reverse = Eph_reverse

instance FieldTag Eph_reverse where fieldName _ = "eph_reverse"

eph_reverse :: Attr Eph_reverse (Maybe Int)
eph_reverse = mkAttr Eph_reverse

---------------------------------------------------------------------------
-- Eph_pag_id Field
---------------------------------------------------------------------------

data Eph_pag_id = Eph_pag_id

instance FieldTag Eph_pag_id where fieldName _ = "eph_pag_id"

eph_pag_id :: Attr Eph_pag_id (Maybe Int)
eph_pag_id = mkAttr Eph_pag_id

---------------------------------------------------------------------------
-- Eph_plc_id Field
---------------------------------------------------------------------------

data Eph_plc_id = Eph_plc_id

instance FieldTag Eph_plc_id where fieldName _ = "eph_plc_id"

eph_plc_id :: Attr Eph_plc_id (Maybe Int)
eph_plc_id = mkAttr Eph_plc_id

---------------------------------------------------------------------------
-- Eph_res_id Field
---------------------------------------------------------------------------

data Eph_res_id = Eph_res_id

instance FieldTag Eph_res_id where fieldName _ = "eph_res_id"

eph_res_id :: Attr Eph_res_id (Maybe Int)
eph_res_id = mkAttr Eph_res_id

---------------------------------------------------------------------------
-- Eph_covered Field
---------------------------------------------------------------------------

data Eph_covered = Eph_covered

instance FieldTag Eph_covered where fieldName _ = "eph_covered"

eph_covered :: Attr Eph_covered (Maybe Int)
eph_covered = mkAttr Eph_covered

---------------------------------------------------------------------------
-- Eph_confirmed Field
---------------------------------------------------------------------------

data Eph_confirmed = Eph_confirmed

instance FieldTag Eph_confirmed where
    fieldName _ = "eph_confirmed"

eph_confirmed :: Attr Eph_confirmed (Maybe String)
eph_confirmed = mkAttr Eph_confirmed

---------------------------------------------------------------------------
-- Eph_status_reg Field
---------------------------------------------------------------------------

data Eph_status_reg = Eph_status_reg

instance FieldTag Eph_status_reg where
    fieldName _ = "eph_status_reg"

eph_status_reg :: Attr Eph_status_reg String
eph_status_reg = mkAttr Eph_status_reg

---------------------------------------------------------------------------
-- Eph_updated_by Field
---------------------------------------------------------------------------

data Eph_updated_by = Eph_updated_by

instance FieldTag Eph_updated_by where
    fieldName _ = "eph_updated_by"

eph_updated_by :: Attr Eph_updated_by Int
eph_updated_by = mkAttr Eph_updated_by

---------------------------------------------------------------------------
-- Eph_updated Field
---------------------------------------------------------------------------

data Eph_updated = Eph_updated

instance FieldTag Eph_updated where fieldName _ = "eph_updated"

eph_updated :: Attr Eph_updated (Maybe CalendarTime)
eph_updated = mkAttr Eph_updated

---------------------------------------------------------------------------
-- Eph_created Field
---------------------------------------------------------------------------

data Eph_created = Eph_created

instance FieldTag Eph_created where fieldName _ = "eph_created"

eph_created :: Attr Eph_created (Maybe CalendarTime)
eph_created = mkAttr Eph_created
