{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack50 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.EXR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type EXR  =
    (RecCons Exr_id Expr (Maybe Int)
     (RecCons Exr_res_id Expr Int
      (RecCons Exr_ext_id Expr Int
       (RecCons Exr_mon_id Expr Int
        (RecCons Exr_quantity Expr Int
         (RecCons Exr_cost Expr Double
          (RecCons Exr_status_reg Expr String
           (RecCons Exr_updated_by Expr Int
            (RecCons Exr_updated Expr (Maybe CalendarTime)
             (RecCons Exr_created Expr (Maybe CalendarTime) RecNil))))))))))

type EXR _result =
    (RecCons Exr_id ((Maybe Int))
     (RecCons Exr_res_id (Int)
      (RecCons Exr_ext_id (Int)
       (RecCons Exr_mon_id (Int)
        (RecCons Exr_quantity (Int)
         (RecCons Exr_cost (Double)
          (RecCons Exr_status_reg (String)
           (RecCons Exr_updated_by (Int)
            (RecCons Exr_updated ((Maybe CalendarTime))
             (RecCons Exr_created ((Maybe CalendarTime)) RecNil))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
eXR :: Table EXR
eXR = baseTable "EXR" $
      hdbMakeEntry Exr_id #
      hdbMakeEntry Exr_res_id #
      hdbMakeEntry Exr_ext_id #
      hdbMakeEntry Exr_mon_id #
      hdbMakeEntry Exr_quantity #
      hdbMakeEntry Exr_cost #
      hdbMakeEntry Exr_status_reg #
      hdbMakeEntry Exr_updated_by #
      hdbMakeEntry Exr_updated #
      hdbMakeEntry Exr_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Exr_id Field
---------------------------------------------------------------------------

data Exr_id = Exr_id

instance FieldTag Exr_id where fieldName _ = "exr_id"

exr_id :: Attr Exr_id (Maybe Int)
exr_id = mkAttr Exr_id

---------------------------------------------------------------------------
-- Exr_res_id Field
---------------------------------------------------------------------------

data Exr_res_id = Exr_res_id

instance FieldTag Exr_res_id where fieldName _ = "exr_res_id"

exr_res_id :: Attr Exr_res_id Int
exr_res_id = mkAttr Exr_res_id

---------------------------------------------------------------------------
-- Exr_ext_id Field
---------------------------------------------------------------------------

data Exr_ext_id = Exr_ext_id

instance FieldTag Exr_ext_id where fieldName _ = "exr_ext_id"

exr_ext_id :: Attr Exr_ext_id Int
exr_ext_id = mkAttr Exr_ext_id

---------------------------------------------------------------------------
-- Exr_mon_id Field
---------------------------------------------------------------------------

data Exr_mon_id = Exr_mon_id

instance FieldTag Exr_mon_id where fieldName _ = "exr_mon_id"

exr_mon_id :: Attr Exr_mon_id Int
exr_mon_id = mkAttr Exr_mon_id

---------------------------------------------------------------------------
-- Exr_quantity Field
---------------------------------------------------------------------------

data Exr_quantity = Exr_quantity

instance FieldTag Exr_quantity where fieldName _ = "exr_quantity"

exr_quantity :: Attr Exr_quantity Int
exr_quantity = mkAttr Exr_quantity

---------------------------------------------------------------------------
-- Exr_cost Field
---------------------------------------------------------------------------

data Exr_cost = Exr_cost

instance FieldTag Exr_cost where fieldName _ = "exr_cost"

exr_cost :: Attr Exr_cost Double
exr_cost = mkAttr Exr_cost

---------------------------------------------------------------------------
-- Exr_status_reg Field
---------------------------------------------------------------------------

data Exr_status_reg = Exr_status_reg

instance FieldTag Exr_status_reg where
    fieldName _ = "exr_status_reg"

exr_status_reg :: Attr Exr_status_reg String
exr_status_reg = mkAttr Exr_status_reg

---------------------------------------------------------------------------
-- Exr_updated_by Field
---------------------------------------------------------------------------

data Exr_updated_by = Exr_updated_by

instance FieldTag Exr_updated_by where
    fieldName _ = "exr_updated_by"

exr_updated_by :: Attr Exr_updated_by Int
exr_updated_by = mkAttr Exr_updated_by

---------------------------------------------------------------------------
-- Exr_updated Field
---------------------------------------------------------------------------

data Exr_updated = Exr_updated

instance FieldTag Exr_updated where fieldName _ = "exr_updated"

exr_updated :: Attr Exr_updated (Maybe CalendarTime)
exr_updated = mkAttr Exr_updated

---------------------------------------------------------------------------
-- Exr_created Field
---------------------------------------------------------------------------

data Exr_created = Exr_created

instance FieldTag Exr_created where fieldName _ = "exr_created"

exr_created :: Attr Exr_created (Maybe CalendarTime)
exr_created = mkAttr Exr_created
