{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack52 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.EXT where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type EXT  =
    (RecCons Ext_id Expr (Maybe Int)
     (RecCons Ext_name Expr String
      (RecCons Ext_hot_id Expr Int
       (RecCons Ext_mon1 Expr Int
        (RecCons Ext_cost1 Expr Double
         (RecCons Ext_mon2 Expr (Maybe Int)
          (RecCons Ext_cost2 Expr (Maybe Double)
           (RecCons Ext_desc Expr String
            (RecCons Ext_status_reg Expr String
             (RecCons Ext_updated_by Expr Int
              (RecCons Ext_updated Expr (Maybe CalendarTime)
               (RecCons Ext_created Expr (Maybe CalendarTime) RecNil))))))))))))

type EXT _result =
    (RecCons Ext_id ((Maybe Int))
     (RecCons Ext_name (String)
      (RecCons Ext_hot_id (Int)
       (RecCons Ext_mon1 (Int)
        (RecCons Ext_cost1 (Double)
         (RecCons Ext_mon2 ((Maybe Int))
          (RecCons Ext_cost2 ((Maybe Double))
           (RecCons Ext_desc (String)
            (RecCons Ext_status_reg (String)
             (RecCons Ext_updated_by (Int)
              (RecCons Ext_updated ((Maybe CalendarTime))
               (RecCons Ext_created ((Maybe CalendarTime)) RecNil))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
eXT :: Table EXT
eXT = baseTable "EXT" $
      hdbMakeEntry Ext_id #
      hdbMakeEntry Ext_name #
      hdbMakeEntry Ext_hot_id #
      hdbMakeEntry Ext_mon1 #
      hdbMakeEntry Ext_cost1 #
      hdbMakeEntry Ext_mon2 #
      hdbMakeEntry Ext_cost2 #
      hdbMakeEntry Ext_desc #
      hdbMakeEntry Ext_status_reg #
      hdbMakeEntry Ext_updated_by #
      hdbMakeEntry Ext_updated #
      hdbMakeEntry Ext_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ext_id Field
---------------------------------------------------------------------------

data Ext_id = Ext_id

instance FieldTag Ext_id where fieldName _ = "ext_id"

ext_id :: Attr Ext_id (Maybe Int)
ext_id = mkAttr Ext_id

---------------------------------------------------------------------------
-- Ext_name Field
---------------------------------------------------------------------------

data Ext_name = Ext_name

instance FieldTag Ext_name where fieldName _ = "ext_name"

ext_name :: Attr Ext_name String
ext_name = mkAttr Ext_name

---------------------------------------------------------------------------
-- Ext_hot_id Field
---------------------------------------------------------------------------

data Ext_hot_id = Ext_hot_id

instance FieldTag Ext_hot_id where fieldName _ = "ext_hot_id"

ext_hot_id :: Attr Ext_hot_id Int
ext_hot_id = mkAttr Ext_hot_id

---------------------------------------------------------------------------
-- Ext_mon1 Field
---------------------------------------------------------------------------

data Ext_mon1 = Ext_mon1

instance FieldTag Ext_mon1 where fieldName _ = "ext_mon1"

ext_mon1 :: Attr Ext_mon1 Int
ext_mon1 = mkAttr Ext_mon1

---------------------------------------------------------------------------
-- Ext_cost1 Field
---------------------------------------------------------------------------

data Ext_cost1 = Ext_cost1

instance FieldTag Ext_cost1 where fieldName _ = "ext_cost1"

ext_cost1 :: Attr Ext_cost1 Double
ext_cost1 = mkAttr Ext_cost1

---------------------------------------------------------------------------
-- Ext_mon2 Field
---------------------------------------------------------------------------

data Ext_mon2 = Ext_mon2

instance FieldTag Ext_mon2 where fieldName _ = "ext_mon2"

ext_mon2 :: Attr Ext_mon2 (Maybe Int)
ext_mon2 = mkAttr Ext_mon2

---------------------------------------------------------------------------
-- Ext_cost2 Field
---------------------------------------------------------------------------

data Ext_cost2 = Ext_cost2

instance FieldTag Ext_cost2 where fieldName _ = "ext_cost2"

ext_cost2 :: Attr Ext_cost2 (Maybe Double)
ext_cost2 = mkAttr Ext_cost2

---------------------------------------------------------------------------
-- Ext_desc Field
---------------------------------------------------------------------------

data Ext_desc = Ext_desc

instance FieldTag Ext_desc where fieldName _ = "ext_desc"

ext_desc :: Attr Ext_desc String
ext_desc = mkAttr Ext_desc

---------------------------------------------------------------------------
-- Ext_status_reg Field
---------------------------------------------------------------------------

data Ext_status_reg = Ext_status_reg

instance FieldTag Ext_status_reg where
    fieldName _ = "ext_status_reg"

ext_status_reg :: Attr Ext_status_reg String
ext_status_reg = mkAttr Ext_status_reg

---------------------------------------------------------------------------
-- Ext_updated_by Field
---------------------------------------------------------------------------

data Ext_updated_by = Ext_updated_by

instance FieldTag Ext_updated_by where
    fieldName _ = "ext_updated_by"

ext_updated_by :: Attr Ext_updated_by Int
ext_updated_by = mkAttr Ext_updated_by

---------------------------------------------------------------------------
-- Ext_updated Field
---------------------------------------------------------------------------

data Ext_updated = Ext_updated

instance FieldTag Ext_updated where fieldName _ = "ext_updated"

ext_updated :: Attr Ext_updated (Maybe CalendarTime)
ext_updated = mkAttr Ext_updated

---------------------------------------------------------------------------
-- Ext_created Field
---------------------------------------------------------------------------

data Ext_created = Ext_created

instance FieldTag Ext_created where fieldName _ = "ext_created"

ext_created :: Attr Ext_created (Maybe CalendarTime)
ext_created = mkAttr Ext_created
