{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack50 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.FAC where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type FAC  =
    (RecCons Fac_id Expr (Maybe Int)
     (RecCons Fac_hot_id Expr Int
      (RecCons Fac_date Expr String
       (RecCons Fac_number Expr (Maybe Int)
        (RecCons Fac_total Expr Integer
         (RecCons Fac_mon_id Expr Int
          (RecCons Fac_status_reg Expr String
           (RecCons Fac_updated_by Expr Int
            (RecCons Fac_updated Expr (Maybe CalendarTime)
             (RecCons Fac_created Expr (Maybe CalendarTime) RecNil))))))))))

type FAC _result =
    (RecCons Fac_id ((Maybe Int))
     (RecCons Fac_hot_id (Int)
      (RecCons Fac_date (String)
       (RecCons Fac_number ((Maybe Int))
        (RecCons Fac_total (Integer)
         (RecCons Fac_mon_id (Int)
          (RecCons Fac_status_reg (String)
           (RecCons Fac_updated_by (Int)
            (RecCons Fac_updated ((Maybe CalendarTime))
             (RecCons Fac_created ((Maybe CalendarTime)) RecNil))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
fAC :: Table FAC
fAC = baseTable "FAC" $
      hdbMakeEntry Fac_id #
      hdbMakeEntry Fac_hot_id #
      hdbMakeEntry Fac_date #
      hdbMakeEntry Fac_number #
      hdbMakeEntry Fac_total #
      hdbMakeEntry Fac_mon_id #
      hdbMakeEntry Fac_status_reg #
      hdbMakeEntry Fac_updated_by #
      hdbMakeEntry Fac_updated #
      hdbMakeEntry Fac_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Fac_id Field
---------------------------------------------------------------------------

data Fac_id = Fac_id

instance FieldTag Fac_id where fieldName _ = "fac_id"

fac_id :: Attr Fac_id (Maybe Int)
fac_id = mkAttr Fac_id

---------------------------------------------------------------------------
-- Fac_hot_id Field
---------------------------------------------------------------------------

data Fac_hot_id = Fac_hot_id

instance FieldTag Fac_hot_id where fieldName _ = "fac_hot_id"

fac_hot_id :: Attr Fac_hot_id Int
fac_hot_id = mkAttr Fac_hot_id

---------------------------------------------------------------------------
-- Fac_date Field
---------------------------------------------------------------------------

data Fac_date = Fac_date

instance FieldTag Fac_date where fieldName _ = "fac_date"

fac_date :: Attr Fac_date String
fac_date = mkAttr Fac_date

---------------------------------------------------------------------------
-- Fac_number Field
---------------------------------------------------------------------------

data Fac_number = Fac_number

instance FieldTag Fac_number where fieldName _ = "fac_number"

fac_number :: Attr Fac_number (Maybe Int)
fac_number = mkAttr Fac_number

---------------------------------------------------------------------------
-- Fac_total Field
---------------------------------------------------------------------------

data Fac_total = Fac_total

instance FieldTag Fac_total where fieldName _ = "fac_total"

fac_total :: Attr Fac_total Integer
fac_total = mkAttr Fac_total

---------------------------------------------------------------------------
-- Fac_mon_id Field
---------------------------------------------------------------------------

data Fac_mon_id = Fac_mon_id

instance FieldTag Fac_mon_id where fieldName _ = "fac_mon_id"

fac_mon_id :: Attr Fac_mon_id Int
fac_mon_id = mkAttr Fac_mon_id

---------------------------------------------------------------------------
-- Fac_status_reg Field
---------------------------------------------------------------------------

data Fac_status_reg = Fac_status_reg

instance FieldTag Fac_status_reg where
    fieldName _ = "fac_status_reg"

fac_status_reg :: Attr Fac_status_reg String
fac_status_reg = mkAttr Fac_status_reg

---------------------------------------------------------------------------
-- Fac_updated_by Field
---------------------------------------------------------------------------

data Fac_updated_by = Fac_updated_by

instance FieldTag Fac_updated_by where
    fieldName _ = "fac_updated_by"

fac_updated_by :: Attr Fac_updated_by Int
fac_updated_by = mkAttr Fac_updated_by

---------------------------------------------------------------------------
-- Fac_updated Field
---------------------------------------------------------------------------

data Fac_updated = Fac_updated

instance FieldTag Fac_updated where fieldName _ = "fac_updated"

fac_updated :: Attr Fac_updated (Maybe CalendarTime)
fac_updated = mkAttr Fac_updated

---------------------------------------------------------------------------
-- Fac_created Field
---------------------------------------------------------------------------

data Fac_created = Fac_created

instance FieldTag Fac_created where fieldName _ = "fac_created"

fac_created :: Attr Fac_created (Maybe CalendarTime)
fac_created = mkAttr Fac_created
