{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HAB where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HAB  =
    (RecCons Hab_id Expr (Maybe Int)
     (RecCons Hab_name Expr String
      (RecCons Hab_tha_id Expr Int
       (RecCons Hab_status_reg Expr String
        (RecCons Hab_updated_by Expr Int
         (RecCons Hab_updated Expr (Maybe CalendarTime)
          (RecCons Hab_created Expr (Maybe CalendarTime) RecNil)))))))

type HAB _result =
    (RecCons Hab_id ((Maybe Int))
     (RecCons Hab_name (String)
      (RecCons Hab_tha_id (Int)
       (RecCons Hab_status_reg (String)
        (RecCons Hab_updated_by (Int)
         (RecCons Hab_updated ((Maybe CalendarTime))
          (RecCons Hab_created ((Maybe CalendarTime)) RecNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hAB :: Table HAB
hAB = baseTable "HAB" $
      hdbMakeEntry Hab_id #
      hdbMakeEntry Hab_name #
      hdbMakeEntry Hab_tha_id #
      hdbMakeEntry Hab_status_reg #
      hdbMakeEntry Hab_updated_by #
      hdbMakeEntry Hab_updated #
      hdbMakeEntry Hab_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hab_id Field
---------------------------------------------------------------------------

data Hab_id = Hab_id

instance FieldTag Hab_id where fieldName _ = "hab_id"

hab_id :: Attr Hab_id (Maybe Int)
hab_id = mkAttr Hab_id

---------------------------------------------------------------------------
-- Hab_name Field
---------------------------------------------------------------------------

data Hab_name = Hab_name

instance FieldTag Hab_name where fieldName _ = "hab_name"

hab_name :: Attr Hab_name String
hab_name = mkAttr Hab_name

---------------------------------------------------------------------------
-- Hab_tha_id Field
---------------------------------------------------------------------------

data Hab_tha_id = Hab_tha_id

instance FieldTag Hab_tha_id where fieldName _ = "hab_tha_id"

hab_tha_id :: Attr Hab_tha_id Int
hab_tha_id = mkAttr Hab_tha_id

---------------------------------------------------------------------------
-- Hab_status_reg Field
---------------------------------------------------------------------------

data Hab_status_reg = Hab_status_reg

instance FieldTag Hab_status_reg where
    fieldName _ = "hab_status_reg"

hab_status_reg :: Attr Hab_status_reg String
hab_status_reg = mkAttr Hab_status_reg

---------------------------------------------------------------------------
-- Hab_updated_by Field
---------------------------------------------------------------------------

data Hab_updated_by = Hab_updated_by

instance FieldTag Hab_updated_by where
    fieldName _ = "hab_updated_by"

hab_updated_by :: Attr Hab_updated_by Int
hab_updated_by = mkAttr Hab_updated_by

---------------------------------------------------------------------------
-- Hab_updated Field
---------------------------------------------------------------------------

data Hab_updated = Hab_updated

instance FieldTag Hab_updated where fieldName _ = "hab_updated"

hab_updated :: Attr Hab_updated (Maybe CalendarTime)
hab_updated = mkAttr Hab_updated

---------------------------------------------------------------------------
-- Hab_created Field
---------------------------------------------------------------------------

data Hab_created = Hab_created

instance FieldTag Hab_created where fieldName _ = "hab_created"

hab_created :: Attr Hab_created (Maybe CalendarTime)
hab_created = mkAttr Hab_created
