{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack58 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HAR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HAR  =
    (RecCons Har_id Expr (Maybe Int)
     (RecCons Har_in Expr CalendarTime
      (RecCons Har_out Expr CalendarTime
       (RecCons Har_hab_id Expr (Maybe Int)
        (RecCons Har_tha_id Expr Int
         (RecCons Har_res_id Expr Int
          (RecCons Har_pla_id Expr Int
           (RecCons Har_cli_id Expr (Maybe Int)
            (RecCons Har_hot_id Expr Int
             (RecCons Har_adults Expr Int
              (RecCons Har_children Expr Int
               (RecCons Har_seniors Expr Int
                (RecCons Har_canc_reason Expr String
                 (RecCons Har_cost Expr Double
                  (RecCons Har_status_reg Expr String
                   (RecCons Har_updated_by Expr Int
                    (RecCons Har_updated Expr (Maybe CalendarTime)
                     (RecCons Har_created Expr (Maybe CalendarTime) RecNil))))))))))))))))))

type HAR _result =
    (RecCons Har_id ((Maybe Int))
     (RecCons Har_in (CalendarTime)
      (RecCons Har_out (CalendarTime)
       (RecCons Har_hab_id ((Maybe Int))
        (RecCons Har_tha_id (Int)
         (RecCons Har_res_id (Int)
          (RecCons Har_pla_id (Int)
           (RecCons Har_cli_id ((Maybe Int))
            (RecCons Har_hot_id (Int)
             (RecCons Har_adults (Int)
              (RecCons Har_children (Int)
               (RecCons Har_seniors (Int)
                (RecCons Har_canc_reason (String)
                 (RecCons Har_cost (Double)
                  (RecCons Har_status_reg (String)
                   (RecCons Har_updated_by (Int)
                    (RecCons Har_updated ((Maybe CalendarTime))
                     (RecCons Har_created ((Maybe CalendarTime)) RecNil))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hAR :: Table HAR
hAR = baseTable "HAR" $
      hdbMakeEntry Har_id #
      hdbMakeEntry Har_in #
      hdbMakeEntry Har_out #
      hdbMakeEntry Har_hab_id #
      hdbMakeEntry Har_tha_id #
      hdbMakeEntry Har_res_id #
      hdbMakeEntry Har_pla_id #
      hdbMakeEntry Har_cli_id #
      hdbMakeEntry Har_hot_id #
      hdbMakeEntry Har_adults #
      hdbMakeEntry Har_children #
      hdbMakeEntry Har_seniors #
      hdbMakeEntry Har_canc_reason #
      hdbMakeEntry Har_cost #
      hdbMakeEntry Har_status_reg #
      hdbMakeEntry Har_updated_by #
      hdbMakeEntry Har_updated #
      hdbMakeEntry Har_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Har_id Field
---------------------------------------------------------------------------

data Har_id = Har_id

instance FieldTag Har_id where fieldName _ = "har_id"

har_id :: Attr Har_id (Maybe Int)
har_id = mkAttr Har_id

---------------------------------------------------------------------------
-- Har_in Field
---------------------------------------------------------------------------

data Har_in = Har_in

instance FieldTag Har_in where fieldName _ = "har_in"

har_in :: Attr Har_in CalendarTime
har_in = mkAttr Har_in

---------------------------------------------------------------------------
-- Har_out Field
---------------------------------------------------------------------------

data Har_out = Har_out

instance FieldTag Har_out where fieldName _ = "har_out"

har_out :: Attr Har_out CalendarTime
har_out = mkAttr Har_out

---------------------------------------------------------------------------
-- Har_hab_id Field
---------------------------------------------------------------------------

data Har_hab_id = Har_hab_id

instance FieldTag Har_hab_id where fieldName _ = "har_hab_id"

har_hab_id :: Attr Har_hab_id (Maybe Int)
har_hab_id = mkAttr Har_hab_id

---------------------------------------------------------------------------
-- Har_tha_id Field
---------------------------------------------------------------------------

data Har_tha_id = Har_tha_id

instance FieldTag Har_tha_id where fieldName _ = "har_tha_id"

har_tha_id :: Attr Har_tha_id Int
har_tha_id = mkAttr Har_tha_id

---------------------------------------------------------------------------
-- Har_res_id Field
---------------------------------------------------------------------------

data Har_res_id = Har_res_id

instance FieldTag Har_res_id where fieldName _ = "har_res_id"

har_res_id :: Attr Har_res_id Int
har_res_id = mkAttr Har_res_id

---------------------------------------------------------------------------
-- Har_pla_id Field
---------------------------------------------------------------------------

data Har_pla_id = Har_pla_id

instance FieldTag Har_pla_id where fieldName _ = "har_pla_id"

har_pla_id :: Attr Har_pla_id Int
har_pla_id = mkAttr Har_pla_id

---------------------------------------------------------------------------
-- Har_cli_id Field
---------------------------------------------------------------------------

data Har_cli_id = Har_cli_id

instance FieldTag Har_cli_id where fieldName _ = "har_cli_id"

har_cli_id :: Attr Har_cli_id (Maybe Int)
har_cli_id = mkAttr Har_cli_id

---------------------------------------------------------------------------
-- Har_hot_id Field
---------------------------------------------------------------------------

data Har_hot_id = Har_hot_id

instance FieldTag Har_hot_id where fieldName _ = "har_hot_id"

har_hot_id :: Attr Har_hot_id Int
har_hot_id = mkAttr Har_hot_id

---------------------------------------------------------------------------
-- Har_adults Field
---------------------------------------------------------------------------

data Har_adults = Har_adults

instance FieldTag Har_adults where fieldName _ = "har_adults"

har_adults :: Attr Har_adults Int
har_adults = mkAttr Har_adults

---------------------------------------------------------------------------
-- Har_children Field
---------------------------------------------------------------------------

data Har_children = Har_children

instance FieldTag Har_children where fieldName _ = "har_children"

har_children :: Attr Har_children Int
har_children = mkAttr Har_children

---------------------------------------------------------------------------
-- Har_seniors Field
---------------------------------------------------------------------------

data Har_seniors = Har_seniors

instance FieldTag Har_seniors where fieldName _ = "har_seniors"

har_seniors :: Attr Har_seniors Int
har_seniors = mkAttr Har_seniors

---------------------------------------------------------------------------
-- Har_canc_reason Field
---------------------------------------------------------------------------

data Har_canc_reason = Har_canc_reason

instance FieldTag Har_canc_reason where
    fieldName _ = "har_canc_reason"

har_canc_reason :: Attr Har_canc_reason String
har_canc_reason = mkAttr Har_canc_reason

---------------------------------------------------------------------------
-- Har_cost Field
---------------------------------------------------------------------------

data Har_cost = Har_cost

instance FieldTag Har_cost where fieldName _ = "har_cost"

har_cost :: Attr Har_cost Double
har_cost = mkAttr Har_cost

---------------------------------------------------------------------------
-- Har_status_reg Field
---------------------------------------------------------------------------

data Har_status_reg = Har_status_reg

instance FieldTag Har_status_reg where
    fieldName _ = "har_status_reg"

har_status_reg :: Attr Har_status_reg String
har_status_reg = mkAttr Har_status_reg

---------------------------------------------------------------------------
-- Har_updated_by Field
---------------------------------------------------------------------------

data Har_updated_by = Har_updated_by

instance FieldTag Har_updated_by where
    fieldName _ = "har_updated_by"

har_updated_by :: Attr Har_updated_by Int
har_updated_by = mkAttr Har_updated_by

---------------------------------------------------------------------------
-- Har_updated Field
---------------------------------------------------------------------------

data Har_updated = Har_updated

instance FieldTag Har_updated where fieldName _ = "har_updated"

har_updated :: Attr Har_updated (Maybe CalendarTime)
har_updated = mkAttr Har_updated

---------------------------------------------------------------------------
-- Har_created Field
---------------------------------------------------------------------------

data Har_created = Har_created

instance FieldTag Har_created where fieldName _ = "har_created"

har_created :: Attr Har_created (Maybe CalendarTime)
har_created = mkAttr Har_created
