{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HOC where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HOC  =
    (RecCons Hoc_id Expr (Maybe Int)
     (RecCons Hoc_hot_id Expr Int
      (RecCons Hoc_type Expr String
       (RecCons Hoc_desc Expr String
        (RecCons Hoc_status_reg Expr String
         (RecCons Hoc_updated_by Expr Int
          (RecCons Hoc_updated Expr (Maybe CalendarTime)
           (RecCons Hoc_created Expr (Maybe CalendarTime) RecNil))))))))

type HOC _result =
    (RecCons Hoc_id ((Maybe Int))
     (RecCons Hoc_hot_id (Int)
      (RecCons Hoc_type (String)
       (RecCons Hoc_desc (String)
        (RecCons Hoc_status_reg (String)
         (RecCons Hoc_updated_by (Int)
          (RecCons Hoc_updated ((Maybe CalendarTime))
           (RecCons Hoc_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hOC :: Table HOC
hOC = baseTable "HOC" $
      hdbMakeEntry Hoc_id #
      hdbMakeEntry Hoc_hot_id #
      hdbMakeEntry Hoc_type #
      hdbMakeEntry Hoc_desc #
      hdbMakeEntry Hoc_status_reg #
      hdbMakeEntry Hoc_updated_by #
      hdbMakeEntry Hoc_updated #
      hdbMakeEntry Hoc_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hoc_id Field
---------------------------------------------------------------------------

data Hoc_id = Hoc_id

instance FieldTag Hoc_id where fieldName _ = "hoc_id"

hoc_id :: Attr Hoc_id (Maybe Int)
hoc_id = mkAttr Hoc_id

---------------------------------------------------------------------------
-- Hoc_hot_id Field
---------------------------------------------------------------------------

data Hoc_hot_id = Hoc_hot_id

instance FieldTag Hoc_hot_id where fieldName _ = "hoc_hot_id"

hoc_hot_id :: Attr Hoc_hot_id Int
hoc_hot_id = mkAttr Hoc_hot_id

---------------------------------------------------------------------------
-- Hoc_type Field
---------------------------------------------------------------------------

data Hoc_type = Hoc_type

instance FieldTag Hoc_type where fieldName _ = "hoc_type"

hoc_type :: Attr Hoc_type String
hoc_type = mkAttr Hoc_type

---------------------------------------------------------------------------
-- Hoc_desc Field
---------------------------------------------------------------------------

data Hoc_desc = Hoc_desc

instance FieldTag Hoc_desc where fieldName _ = "hoc_desc"

hoc_desc :: Attr Hoc_desc String
hoc_desc = mkAttr Hoc_desc

---------------------------------------------------------------------------
-- Hoc_status_reg Field
---------------------------------------------------------------------------

data Hoc_status_reg = Hoc_status_reg

instance FieldTag Hoc_status_reg where
    fieldName _ = "hoc_status_reg"

hoc_status_reg :: Attr Hoc_status_reg String
hoc_status_reg = mkAttr Hoc_status_reg

---------------------------------------------------------------------------
-- Hoc_updated_by Field
---------------------------------------------------------------------------

data Hoc_updated_by = Hoc_updated_by

instance FieldTag Hoc_updated_by where
    fieldName _ = "hoc_updated_by"

hoc_updated_by :: Attr Hoc_updated_by Int
hoc_updated_by = mkAttr Hoc_updated_by

---------------------------------------------------------------------------
-- Hoc_updated Field
---------------------------------------------------------------------------

data Hoc_updated = Hoc_updated

instance FieldTag Hoc_updated where fieldName _ = "hoc_updated"

hoc_updated :: Attr Hoc_updated (Maybe CalendarTime)
hoc_updated = mkAttr Hoc_updated

---------------------------------------------------------------------------
-- Hoc_created Field
---------------------------------------------------------------------------

data Hoc_created = Hoc_created

instance FieldTag Hoc_created where fieldName _ = "hoc_created"

hoc_created :: Attr Hoc_created (Maybe CalendarTime)
hoc_created = mkAttr Hoc_created
