{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack56 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HOE where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HOE  =
    (RecCons Hoe_id Expr (Maybe Int)
     (RecCons Hoe_hot_id Expr Int
      (RecCons Hoe_usr_id Expr Int
       (RecCons Hoe_near_transport Expr Int
        (RecCons Hoe_near_restaurant Expr Int
         (RecCons Hoe_near_commercial Expr Int
          (RecCons Hoe_staff_quality Expr Int
           (RecCons Hoe_price_value Expr Int
            (RecCons Hoe_luxury Expr Int
             (RecCons Hoe_comfort Expr Int
              (RecCons Hoe_quiescence Expr Int
               (RecCons Hoe_restaurant_quality Expr Int
                (RecCons Hoe_status_reg Expr String
                 (RecCons Hoe_updated_by Expr Int
                  (RecCons Hoe_updated Expr (Maybe CalendarTime)
                   (RecCons Hoe_created Expr (Maybe CalendarTime) RecNil))))))))))))))))

type HOE _result =
    (RecCons Hoe_id ((Maybe Int))
     (RecCons Hoe_hot_id (Int)
      (RecCons Hoe_usr_id (Int)
       (RecCons Hoe_near_transport (Int)
        (RecCons Hoe_near_restaurant (Int)
         (RecCons Hoe_near_commercial (Int)
          (RecCons Hoe_staff_quality (Int)
           (RecCons Hoe_price_value (Int)
            (RecCons Hoe_luxury (Int)
             (RecCons Hoe_comfort (Int)
              (RecCons Hoe_quiescence (Int)
               (RecCons Hoe_restaurant_quality (Int)
                (RecCons Hoe_status_reg (String)
                 (RecCons Hoe_updated_by (Int)
                  (RecCons Hoe_updated ((Maybe CalendarTime))
                   (RecCons Hoe_created ((Maybe CalendarTime)) RecNil))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hOE :: Table HOE
hOE = baseTable "HOE" $
      hdbMakeEntry Hoe_id #
      hdbMakeEntry Hoe_hot_id #
      hdbMakeEntry Hoe_usr_id #
      hdbMakeEntry Hoe_near_transport #
      hdbMakeEntry Hoe_near_restaurant #
      hdbMakeEntry Hoe_near_commercial #
      hdbMakeEntry Hoe_staff_quality #
      hdbMakeEntry Hoe_price_value #
      hdbMakeEntry Hoe_luxury #
      hdbMakeEntry Hoe_comfort #
      hdbMakeEntry Hoe_quiescence #
      hdbMakeEntry Hoe_restaurant_quality #
      hdbMakeEntry Hoe_status_reg #
      hdbMakeEntry Hoe_updated_by #
      hdbMakeEntry Hoe_updated #
      hdbMakeEntry Hoe_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hoe_id Field
---------------------------------------------------------------------------

data Hoe_id = Hoe_id

instance FieldTag Hoe_id where fieldName _ = "hoe_id"

hoe_id :: Attr Hoe_id (Maybe Int)
hoe_id = mkAttr Hoe_id

---------------------------------------------------------------------------
-- Hoe_hot_id Field
---------------------------------------------------------------------------

data Hoe_hot_id = Hoe_hot_id

instance FieldTag Hoe_hot_id where fieldName _ = "hoe_hot_id"

hoe_hot_id :: Attr Hoe_hot_id Int
hoe_hot_id = mkAttr Hoe_hot_id

---------------------------------------------------------------------------
-- Hoe_usr_id Field
---------------------------------------------------------------------------

data Hoe_usr_id = Hoe_usr_id

instance FieldTag Hoe_usr_id where fieldName _ = "hoe_usr_id"

hoe_usr_id :: Attr Hoe_usr_id Int
hoe_usr_id = mkAttr Hoe_usr_id

---------------------------------------------------------------------------
-- Hoe_near_transport Field
---------------------------------------------------------------------------

data Hoe_near_transport = Hoe_near_transport

instance FieldTag Hoe_near_transport where
    fieldName _ = "hoe_near_transport"

hoe_near_transport :: Attr Hoe_near_transport Int
hoe_near_transport = mkAttr Hoe_near_transport

---------------------------------------------------------------------------
-- Hoe_near_restaurant Field
---------------------------------------------------------------------------

data Hoe_near_restaurant = Hoe_near_restaurant

instance FieldTag Hoe_near_restaurant where
    fieldName _ = "hoe_near_restaurant"

hoe_near_restaurant :: Attr Hoe_near_restaurant Int
hoe_near_restaurant = mkAttr Hoe_near_restaurant

---------------------------------------------------------------------------
-- Hoe_near_commercial Field
---------------------------------------------------------------------------

data Hoe_near_commercial = Hoe_near_commercial

instance FieldTag Hoe_near_commercial where
    fieldName _ = "hoe_near_commercial"

hoe_near_commercial :: Attr Hoe_near_commercial Int
hoe_near_commercial = mkAttr Hoe_near_commercial

---------------------------------------------------------------------------
-- Hoe_staff_quality Field
---------------------------------------------------------------------------

data Hoe_staff_quality = Hoe_staff_quality

instance FieldTag Hoe_staff_quality where
    fieldName _ = "hoe_staff_quality"

hoe_staff_quality :: Attr Hoe_staff_quality Int
hoe_staff_quality = mkAttr Hoe_staff_quality

---------------------------------------------------------------------------
-- Hoe_price_value Field
---------------------------------------------------------------------------

data Hoe_price_value = Hoe_price_value

instance FieldTag Hoe_price_value where
    fieldName _ = "hoe_price_value"

hoe_price_value :: Attr Hoe_price_value Int
hoe_price_value = mkAttr Hoe_price_value

---------------------------------------------------------------------------
-- Hoe_luxury Field
---------------------------------------------------------------------------

data Hoe_luxury = Hoe_luxury

instance FieldTag Hoe_luxury where fieldName _ = "hoe_luxury"

hoe_luxury :: Attr Hoe_luxury Int
hoe_luxury = mkAttr Hoe_luxury

---------------------------------------------------------------------------
-- Hoe_comfort Field
---------------------------------------------------------------------------

data Hoe_comfort = Hoe_comfort

instance FieldTag Hoe_comfort where fieldName _ = "hoe_comfort"

hoe_comfort :: Attr Hoe_comfort Int
hoe_comfort = mkAttr Hoe_comfort

---------------------------------------------------------------------------
-- Hoe_quiescence Field
---------------------------------------------------------------------------

data Hoe_quiescence = Hoe_quiescence

instance FieldTag Hoe_quiescence where
    fieldName _ = "hoe_quiescence"

hoe_quiescence :: Attr Hoe_quiescence Int
hoe_quiescence = mkAttr Hoe_quiescence

---------------------------------------------------------------------------
-- Hoe_restaurant_quality Field
---------------------------------------------------------------------------

data Hoe_restaurant_quality = Hoe_restaurant_quality

instance FieldTag Hoe_restaurant_quality where
    fieldName _ = "hoe_restaurant_quality"

hoe_restaurant_quality :: Attr Hoe_restaurant_quality Int
hoe_restaurant_quality = mkAttr Hoe_restaurant_quality

---------------------------------------------------------------------------
-- Hoe_status_reg Field
---------------------------------------------------------------------------

data Hoe_status_reg = Hoe_status_reg

instance FieldTag Hoe_status_reg where
    fieldName _ = "hoe_status_reg"

hoe_status_reg :: Attr Hoe_status_reg String
hoe_status_reg = mkAttr Hoe_status_reg

---------------------------------------------------------------------------
-- Hoe_updated_by Field
---------------------------------------------------------------------------

data Hoe_updated_by = Hoe_updated_by

instance FieldTag Hoe_updated_by where
    fieldName _ = "hoe_updated_by"

hoe_updated_by :: Attr Hoe_updated_by Int
hoe_updated_by = mkAttr Hoe_updated_by

---------------------------------------------------------------------------
-- Hoe_updated Field
---------------------------------------------------------------------------

data Hoe_updated = Hoe_updated

instance FieldTag Hoe_updated where fieldName _ = "hoe_updated"

hoe_updated :: Attr Hoe_updated (Maybe CalendarTime)
hoe_updated = mkAttr Hoe_updated

---------------------------------------------------------------------------
-- Hoe_created Field
---------------------------------------------------------------------------

data Hoe_created = Hoe_created

instance FieldTag Hoe_created where fieldName _ = "hoe_created"

hoe_created :: Attr Hoe_created (Maybe CalendarTime)
hoe_created = mkAttr Hoe_created
