{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack51 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HOI where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HOI  =
    (RecCons Hoi_id Expr (Maybe Int)
     (RecCons Hoi_hot_id Expr Int
      (RecCons Hoi_tha_id Expr (Maybe Int)
       (RecCons Hoi_hash Expr String
        (RecCons Hoi_type Expr String
         (RecCons Hoi_order Expr Int
          (RecCons Hoi_caption Expr (Maybe String)
           (RecCons Hoi_status_reg Expr String
            (RecCons Hoi_updated_by Expr Int
             (RecCons Hoi_updated Expr (Maybe CalendarTime)
              (RecCons Hoi_created Expr (Maybe CalendarTime) RecNil)))))))))))

type HOI _result =
    (RecCons Hoi_id ((Maybe Int))
     (RecCons Hoi_hot_id (Int)
      (RecCons Hoi_tha_id ((Maybe Int))
       (RecCons Hoi_hash (String)
        (RecCons Hoi_type (String)
         (RecCons Hoi_order (Int)
          (RecCons Hoi_caption ((Maybe String))
           (RecCons Hoi_status_reg (String)
            (RecCons Hoi_updated_by (Int)
             (RecCons Hoi_updated ((Maybe CalendarTime))
              (RecCons Hoi_created ((Maybe CalendarTime)) RecNil)))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hOI :: Table HOI
hOI = baseTable "HOI" $
      hdbMakeEntry Hoi_id #
      hdbMakeEntry Hoi_hot_id #
      hdbMakeEntry Hoi_tha_id #
      hdbMakeEntry Hoi_hash #
      hdbMakeEntry Hoi_type #
      hdbMakeEntry Hoi_order #
      hdbMakeEntry Hoi_caption #
      hdbMakeEntry Hoi_status_reg #
      hdbMakeEntry Hoi_updated_by #
      hdbMakeEntry Hoi_updated #
      hdbMakeEntry Hoi_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hoi_id Field
---------------------------------------------------------------------------

data Hoi_id = Hoi_id

instance FieldTag Hoi_id where fieldName _ = "hoi_id"

hoi_id :: Attr Hoi_id (Maybe Int)
hoi_id = mkAttr Hoi_id

---------------------------------------------------------------------------
-- Hoi_hot_id Field
---------------------------------------------------------------------------

data Hoi_hot_id = Hoi_hot_id

instance FieldTag Hoi_hot_id where fieldName _ = "hoi_hot_id"

hoi_hot_id :: Attr Hoi_hot_id Int
hoi_hot_id = mkAttr Hoi_hot_id

---------------------------------------------------------------------------
-- Hoi_tha_id Field
---------------------------------------------------------------------------

data Hoi_tha_id = Hoi_tha_id

instance FieldTag Hoi_tha_id where fieldName _ = "hoi_tha_id"

hoi_tha_id :: Attr Hoi_tha_id (Maybe Int)
hoi_tha_id = mkAttr Hoi_tha_id

---------------------------------------------------------------------------
-- Hoi_hash Field
---------------------------------------------------------------------------

data Hoi_hash = Hoi_hash

instance FieldTag Hoi_hash where fieldName _ = "hoi_hash"

hoi_hash :: Attr Hoi_hash String
hoi_hash = mkAttr Hoi_hash

---------------------------------------------------------------------------
-- Hoi_type Field
---------------------------------------------------------------------------

data Hoi_type = Hoi_type

instance FieldTag Hoi_type where fieldName _ = "hoi_type"

hoi_type :: Attr Hoi_type String
hoi_type = mkAttr Hoi_type

---------------------------------------------------------------------------
-- Hoi_order Field
---------------------------------------------------------------------------

data Hoi_order = Hoi_order

instance FieldTag Hoi_order where fieldName _ = "hoi_order"

hoi_order :: Attr Hoi_order Int
hoi_order = mkAttr Hoi_order

---------------------------------------------------------------------------
-- Hoi_caption Field
---------------------------------------------------------------------------

data Hoi_caption = Hoi_caption

instance FieldTag Hoi_caption where fieldName _ = "hoi_caption"

hoi_caption :: Attr Hoi_caption (Maybe String)
hoi_caption = mkAttr Hoi_caption

---------------------------------------------------------------------------
-- Hoi_status_reg Field
---------------------------------------------------------------------------

data Hoi_status_reg = Hoi_status_reg

instance FieldTag Hoi_status_reg where
    fieldName _ = "hoi_status_reg"

hoi_status_reg :: Attr Hoi_status_reg String
hoi_status_reg = mkAttr Hoi_status_reg

---------------------------------------------------------------------------
-- Hoi_updated_by Field
---------------------------------------------------------------------------

data Hoi_updated_by = Hoi_updated_by

instance FieldTag Hoi_updated_by where
    fieldName _ = "hoi_updated_by"

hoi_updated_by :: Attr Hoi_updated_by Int
hoi_updated_by = mkAttr Hoi_updated_by

---------------------------------------------------------------------------
-- Hoi_updated Field
---------------------------------------------------------------------------

data Hoi_updated = Hoi_updated

instance FieldTag Hoi_updated where fieldName _ = "hoi_updated"

hoi_updated :: Attr Hoi_updated (Maybe CalendarTime)
hoi_updated = mkAttr Hoi_updated

---------------------------------------------------------------------------
-- Hoi_created Field
---------------------------------------------------------------------------

data Hoi_created = Hoi_created

instance FieldTag Hoi_created where fieldName _ = "hoi_created"

hoi_created :: Attr Hoi_created (Maybe CalendarTime)
hoi_created = mkAttr Hoi_created
