{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack56 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HOR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HOR  =
    (RecCons Hor_id Expr (Maybe Int)
     (RecCons Hor_hot_id Expr Int
      (RecCons Hor_near_transport Expr Int
       (RecCons Hor_near_restaurant Expr Int
        (RecCons Hor_near_commercial Expr Int
         (RecCons Hor_staff_quality Expr Int
          (RecCons Hor_luxury Expr Int
           (RecCons Hor_comfort Expr Int
            (RecCons Hor_quiescence Expr Int
             (RecCons Hor_restaurant_quality Expr Int
              (RecCons Hor_breakfast_included Expr Bool
               (RecCons Hor_all_included Expr Bool
                (RecCons Hor_status_reg Expr String
                 (RecCons Hor_updated_by Expr Int
                  (RecCons Hor_updated Expr (Maybe CalendarTime)
                   (RecCons Hor_created Expr (Maybe CalendarTime) RecNil))))))))))))))))

type HOR _result =
    (RecCons Hor_id ((Maybe Int))
     (RecCons Hor_hot_id (Int)
      (RecCons Hor_near_transport (Int)
       (RecCons Hor_near_restaurant (Int)
        (RecCons Hor_near_commercial (Int)
         (RecCons Hor_staff_quality (Int)
          (RecCons Hor_luxury (Int)
           (RecCons Hor_comfort (Int)
            (RecCons Hor_quiescence (Int)
             (RecCons Hor_restaurant_quality (Int)
              (RecCons Hor_breakfast_included (Bool)
               (RecCons Hor_all_included (Bool)
                (RecCons Hor_status_reg (String)
                 (RecCons Hor_updated_by (Int)
                  (RecCons Hor_updated ((Maybe CalendarTime))
                   (RecCons Hor_created ((Maybe CalendarTime)) RecNil))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hOR :: Table HOR
hOR = baseTable "HOR" $
      hdbMakeEntry Hor_id #
      hdbMakeEntry Hor_hot_id #
      hdbMakeEntry Hor_near_transport #
      hdbMakeEntry Hor_near_restaurant #
      hdbMakeEntry Hor_near_commercial #
      hdbMakeEntry Hor_staff_quality #
      hdbMakeEntry Hor_luxury #
      hdbMakeEntry Hor_comfort #
      hdbMakeEntry Hor_quiescence #
      hdbMakeEntry Hor_restaurant_quality #
      hdbMakeEntry Hor_breakfast_included #
      hdbMakeEntry Hor_all_included #
      hdbMakeEntry Hor_status_reg #
      hdbMakeEntry Hor_updated_by #
      hdbMakeEntry Hor_updated #
      hdbMakeEntry Hor_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hor_id Field
---------------------------------------------------------------------------

data Hor_id = Hor_id

instance FieldTag Hor_id where fieldName _ = "hor_id"

hor_id :: Attr Hor_id (Maybe Int)
hor_id = mkAttr Hor_id

---------------------------------------------------------------------------
-- Hor_hot_id Field
---------------------------------------------------------------------------

data Hor_hot_id = Hor_hot_id

instance FieldTag Hor_hot_id where fieldName _ = "hor_hot_id"

hor_hot_id :: Attr Hor_hot_id Int
hor_hot_id = mkAttr Hor_hot_id

---------------------------------------------------------------------------
-- Hor_near_transport Field
---------------------------------------------------------------------------

data Hor_near_transport = Hor_near_transport

instance FieldTag Hor_near_transport where
    fieldName _ = "hor_near_transport"

hor_near_transport :: Attr Hor_near_transport Int
hor_near_transport = mkAttr Hor_near_transport

---------------------------------------------------------------------------
-- Hor_near_restaurant Field
---------------------------------------------------------------------------

data Hor_near_restaurant = Hor_near_restaurant

instance FieldTag Hor_near_restaurant where
    fieldName _ = "hor_near_restaurant"

hor_near_restaurant :: Attr Hor_near_restaurant Int
hor_near_restaurant = mkAttr Hor_near_restaurant

---------------------------------------------------------------------------
-- Hor_near_commercial Field
---------------------------------------------------------------------------

data Hor_near_commercial = Hor_near_commercial

instance FieldTag Hor_near_commercial where
    fieldName _ = "hor_near_commercial"

hor_near_commercial :: Attr Hor_near_commercial Int
hor_near_commercial = mkAttr Hor_near_commercial

---------------------------------------------------------------------------
-- Hor_staff_quality Field
---------------------------------------------------------------------------

data Hor_staff_quality = Hor_staff_quality

instance FieldTag Hor_staff_quality where
    fieldName _ = "hor_staff_quality"

hor_staff_quality :: Attr Hor_staff_quality Int
hor_staff_quality = mkAttr Hor_staff_quality

---------------------------------------------------------------------------
-- Hor_luxury Field
---------------------------------------------------------------------------

data Hor_luxury = Hor_luxury

instance FieldTag Hor_luxury where fieldName _ = "hor_luxury"

hor_luxury :: Attr Hor_luxury Int
hor_luxury = mkAttr Hor_luxury

---------------------------------------------------------------------------
-- Hor_comfort Field
---------------------------------------------------------------------------

data Hor_comfort = Hor_comfort

instance FieldTag Hor_comfort where fieldName _ = "hor_comfort"

hor_comfort :: Attr Hor_comfort Int
hor_comfort = mkAttr Hor_comfort

---------------------------------------------------------------------------
-- Hor_quiescence Field
---------------------------------------------------------------------------

data Hor_quiescence = Hor_quiescence

instance FieldTag Hor_quiescence where
    fieldName _ = "hor_quiescence"

hor_quiescence :: Attr Hor_quiescence Int
hor_quiescence = mkAttr Hor_quiescence

---------------------------------------------------------------------------
-- Hor_restaurant_quality Field
---------------------------------------------------------------------------

data Hor_restaurant_quality = Hor_restaurant_quality

instance FieldTag Hor_restaurant_quality where
    fieldName _ = "hor_restaurant_quality"

hor_restaurant_quality :: Attr Hor_restaurant_quality Int
hor_restaurant_quality = mkAttr Hor_restaurant_quality

---------------------------------------------------------------------------
-- Hor_breakfast_included Field
---------------------------------------------------------------------------

data Hor_breakfast_included = Hor_breakfast_included

instance FieldTag Hor_breakfast_included where
    fieldName _ = "hor_breakfast_included"

hor_breakfast_included :: Attr Hor_breakfast_included Bool
hor_breakfast_included = mkAttr Hor_breakfast_included

---------------------------------------------------------------------------
-- Hor_all_included Field
---------------------------------------------------------------------------

data Hor_all_included = Hor_all_included

instance FieldTag Hor_all_included where
    fieldName _ = "hor_all_included"

hor_all_included :: Attr Hor_all_included Bool
hor_all_included = mkAttr Hor_all_included

---------------------------------------------------------------------------
-- Hor_status_reg Field
---------------------------------------------------------------------------

data Hor_status_reg = Hor_status_reg

instance FieldTag Hor_status_reg where
    fieldName _ = "hor_status_reg"

hor_status_reg :: Attr Hor_status_reg String
hor_status_reg = mkAttr Hor_status_reg

---------------------------------------------------------------------------
-- Hor_updated_by Field
---------------------------------------------------------------------------

data Hor_updated_by = Hor_updated_by

instance FieldTag Hor_updated_by where
    fieldName _ = "hor_updated_by"

hor_updated_by :: Attr Hor_updated_by Int
hor_updated_by = mkAttr Hor_updated_by

---------------------------------------------------------------------------
-- Hor_updated Field
---------------------------------------------------------------------------

data Hor_updated = Hor_updated

instance FieldTag Hor_updated where fieldName _ = "hor_updated"

hor_updated :: Attr Hor_updated (Maybe CalendarTime)
hor_updated = mkAttr Hor_updated

---------------------------------------------------------------------------
-- Hor_created Field
---------------------------------------------------------------------------

data Hor_created = Hor_created

instance FieldTag Hor_created where fieldName _ = "hor_created"

hor_created :: Attr Hor_created (Maybe CalendarTime)
hor_created = mkAttr Hor_created
