{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack131 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HOT where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HOT  =
    (RecCons Hot_id Expr (Maybe Int)
     (RecCons Hot_name Expr String
      (RecCons Hot_description Expr (Maybe String)
       (RecCons Hot_address Expr (Maybe String)
        (RecCons Hot_alternative_address Expr (Maybe String)
         (RecCons Hot_type Expr (Maybe String)
          (RecCons Hot_category_level Expr (Maybe String)
           (RecCons Hot_master_usr_id Expr Int
            (RecCons Hot_email_1 Expr String
             (RecCons Hot_email_2 Expr (Maybe String)
              (RecCons Hot_email_3 Expr (Maybe String)
               (RecCons Hot_phone_1 Expr String
                (RecCons Hot_phone_2 Expr (Maybe String)
                 (RecCons Hot_phone_3 Expr (Maybe String)
                  (RecCons Hot_fax Expr (Maybe String)
                   (RecCons Hot_web_page_url Expr (Maybe String)
                    (RecCons Hot_logo Expr (Maybe String)
                     (RecCons Hot_slogan Expr (Maybe String)
                      (RecCons Hot_theme Expr String
                       (RecCons Hot_pai_id Expr Int
                        (RecCons Hot_edo_id Expr Int
                         (RecCons Hot_lug_id Expr Int
                          (RecCons Hot_des_id Expr (Maybe Int)
                           (RecCons Hot_plc_id Expr Int
                            (RecCons Hot_plc_id_new Expr (Maybe Int)
                             (RecCons Hot_gmaps Expr (Maybe Bool)
                              (RecCons Hot_gmaps_url Expr (Maybe String)
                               (RecCons Hot_map Expr (Maybe Bool)
                                (RecCons Hot_map_hash Expr (Maybe String)
                                 (RecCons Hot_section_config Expr (Maybe String)
                                  (RecCons Hot_languages Expr (Maybe String)
                                   (RecCons Hot_base_lang Expr (Maybe String)
                                    (RecCons Hot_fac_rest Expr (Maybe Bool)
                                     (RecCons Hot_fac_bar Expr (Maybe Bool)
                                      (RecCons Hot_fac_pool Expr (Maybe Bool)
                                       (RecCons Hot_fac_children_pool Expr (Maybe Bool)
                                        (RecCons Hot_fac_tv Expr (Maybe Bool)
                                         (RecCons Hot_fac_wifi Expr (Maybe Bool)
                                          (RecCons Hot_fac_casino Expr (Maybe Bool)
                                           (RecCons Hot_fac_lounge Expr (Maybe Bool)
                                            (RecCons Hot_fac_business_center Expr (Maybe Bool)
                                             (RecCons Hot_fac_gym Expr (Maybe Bool)
                                              (RecCons Hot_fac_spa Expr (Maybe Bool)
                                               (RecCons Hot_fac_hairdressing Expr (Maybe Bool)
                                                (RecCons Hot_fac_crib Expr (Maybe Bool)
                                                 (RecCons Hot_fac_laundry Expr (Maybe Bool)
                                                  (RecCons Hot_fac_store Expr (Maybe Bool)
                                                   (RecCons Hot_fac_fax Expr (Maybe Bool)
                                                    (RecCons Hot_fac_alarm_clock Expr (Maybe Bool)
                                                     (RecCons Hot_fac_handicap_access Expr (Maybe Bool)
                                                      (RecCons Hot_fac_entertainment Expr (Maybe Bool)
                                                       (RecCons Hot_fac_playroom Expr (Maybe Bool)
                                                        (RecCons Hot_fac_atm Expr (Maybe Bool)
                                                         (RecCons Hot_fac_power_plant Expr (Maybe Bool)
                                                          (RecCons Hot_fac_parking Expr (Maybe Bool)
                                                           (RecCons Hot_fac_extra Expr (Maybe String)
                                                            (RecCons Hot_fac_parking_other Expr (Maybe String)
                                                             (RecCons Hot_time_checkin_min Expr (Maybe CalendarTime)
                                                              (RecCons Hot_time_checkin_max Expr (Maybe CalendarTime)
                                                               (RecCons Hot_time_checkout_min Expr (Maybe CalendarTime)
                                                                (RecCons Hot_time_checkout_max Expr (Maybe CalendarTime)
                                                                 (RecCons Hot_pets Expr (Maybe Bool)
                                                                  (RecCons Hot_pets_info Expr (Maybe String)
                                                                   (RecCons Hot_pax_complete_info Expr (Maybe Bool)
                                                                    (RecCons Hot_pax_adults_info Expr (Maybe Bool)
                                                                     (RecCons Hot_pax_children_info Expr (Maybe Bool)
                                                                      (RecCons Hot_pax_seniors_info Expr (Maybe Bool)
                                                                       (RecCons Hot_pax_ci Expr (Maybe Bool)
                                                                        (RecCons Hot_pax_phone Expr (Maybe Bool)
                                                                         (RecCons Hot_pax_email Expr (Maybe Bool)
                                                                          (RecCons Hot_children_max_age Expr Int
                                                                           (RecCons Hot_children_min_age Expr Int
                                                                            (RecCons Hot_senior_min_age Expr Int
                                                                             (RecCons Hot_additional_field_1 Expr (Maybe String)
                                                                              (RecCons Hot_total_rooms Expr Int
                                                                               (RecCons Hot_mon_rate_1 Expr (Maybe Int)
                                                                                (RecCons Hot_mon_source_1 Expr (Maybe Int)
                                                                                 (RecCons Hot_mon_id_1 Expr Int
                                                                                  (RecCons Hot_mon_id_2 Expr (Maybe Int)
                                                                                   (RecCons Hot_mon_rate_2 Expr (Maybe Int)
                                                                                    (RecCons Hot_mon_source_2 Expr (Maybe Int)
                                                                                     (RecCons Hot_skype Expr (Maybe String)
                                                                                      (RecCons Hot_facebook Expr (Maybe String)
                                                                                       (RecCons Hot_twitter Expr (Maybe String)
                                                                                        (RecCons Hot_google_plus Expr (Maybe String)
                                                                                         (RecCons Hot_observation Expr (Maybe String)
                                                                                          (RecCons Hot_cdn_id Expr (Maybe Int)
                                                                                           (RecCons Hot_status_reg Expr String
                                                                                            (RecCons Hot_updated_by Expr Int
                                                                                             (RecCons Hot_updated Expr (Maybe CalendarTime)
                                                                                              (RecCons Hot_created Expr (Maybe CalendarTime) RecNil)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

type HOT _result =
    (RecCons Hot_id ((Maybe Int))
     (RecCons Hot_name (String)
      (RecCons Hot_description ((Maybe String))
       (RecCons Hot_address ((Maybe String))
        (RecCons Hot_alternative_address ((Maybe String))
         (RecCons Hot_type ((Maybe String))
          (RecCons Hot_category_level ((Maybe String))
           (RecCons Hot_master_usr_id (Int)
            (RecCons Hot_email_1 (String)
             (RecCons Hot_email_2 ((Maybe String))
              (RecCons Hot_email_3 ((Maybe String))
               (RecCons Hot_phone_1 (String)
                (RecCons Hot_phone_2 ((Maybe String))
                 (RecCons Hot_phone_3 ((Maybe String))
                  (RecCons Hot_fax ((Maybe String))
                   (RecCons Hot_web_page_url ((Maybe String))
                    (RecCons Hot_logo ((Maybe String))
                     (RecCons Hot_slogan ((Maybe String))
                      (RecCons Hot_theme (String)
                       (RecCons Hot_pai_id (Int)
                        (RecCons Hot_edo_id (Int)
                         (RecCons Hot_lug_id (Int)
                          (RecCons Hot_des_id ((Maybe Int))
                           (RecCons Hot_plc_id (Int)
                            (RecCons Hot_plc_id_new ((Maybe Int))
                             (RecCons Hot_gmaps ((Maybe Bool))
                              (RecCons Hot_gmaps_url ((Maybe String))
                               (RecCons Hot_map ((Maybe Bool))
                                (RecCons Hot_map_hash ((Maybe String))
                                 (RecCons Hot_section_config ((Maybe String))
                                  (RecCons Hot_languages ((Maybe String))
                                   (RecCons Hot_base_lang ((Maybe String))
                                    (RecCons Hot_fac_rest ((Maybe Bool))
                                     (RecCons Hot_fac_bar ((Maybe Bool))
                                      (RecCons Hot_fac_pool ((Maybe Bool))
                                       (RecCons Hot_fac_children_pool ((Maybe Bool))
                                        (RecCons Hot_fac_tv ((Maybe Bool))
                                         (RecCons Hot_fac_wifi ((Maybe Bool))
                                          (RecCons Hot_fac_casino ((Maybe Bool))
                                           (RecCons Hot_fac_lounge ((Maybe Bool))
                                            (RecCons Hot_fac_business_center ((Maybe Bool))
                                             (RecCons Hot_fac_gym ((Maybe Bool))
                                              (RecCons Hot_fac_spa ((Maybe Bool))
                                               (RecCons Hot_fac_hairdressing ((Maybe Bool))
                                                (RecCons Hot_fac_crib ((Maybe Bool))
                                                 (RecCons Hot_fac_laundry ((Maybe Bool))
                                                  (RecCons Hot_fac_store ((Maybe Bool))
                                                   (RecCons Hot_fac_fax ((Maybe Bool))
                                                    (RecCons Hot_fac_alarm_clock ((Maybe Bool))
                                                     (RecCons Hot_fac_handicap_access ((Maybe Bool))
                                                      (RecCons Hot_fac_entertainment ((Maybe Bool))
                                                       (RecCons Hot_fac_playroom ((Maybe Bool))
                                                        (RecCons Hot_fac_atm ((Maybe Bool))
                                                         (RecCons Hot_fac_power_plant ((Maybe Bool))
                                                          (RecCons Hot_fac_parking ((Maybe Bool))
                                                           (RecCons Hot_fac_extra ((Maybe String))
                                                            (RecCons Hot_fac_parking_other ((Maybe String))
                                                             (RecCons Hot_time_checkin_min ((Maybe CalendarTime))
                                                              (RecCons Hot_time_checkin_max ((Maybe CalendarTime))
                                                               (RecCons Hot_time_checkout_min ((Maybe CalendarTime))
                                                                (RecCons Hot_time_checkout_max ((Maybe CalendarTime))
                                                                 (RecCons Hot_pets ((Maybe Bool))
                                                                  (RecCons Hot_pets_info ((Maybe String))
                                                                   (RecCons Hot_pax_complete_info ((Maybe Bool))
                                                                    (RecCons Hot_pax_adults_info ((Maybe Bool))
                                                                     (RecCons Hot_pax_children_info ((Maybe Bool))
                                                                      (RecCons Hot_pax_seniors_info ((Maybe Bool))
                                                                       (RecCons Hot_pax_ci ((Maybe Bool))
                                                                        (RecCons Hot_pax_phone ((Maybe Bool))
                                                                         (RecCons Hot_pax_email ((Maybe Bool))
                                                                          (RecCons Hot_children_max_age (Int)
                                                                           (RecCons Hot_children_min_age (Int)
                                                                            (RecCons Hot_senior_min_age (Int)
                                                                             (RecCons Hot_additional_field_1 ((Maybe String))
                                                                              (RecCons Hot_total_rooms (Int)
                                                                               (RecCons Hot_mon_rate_1 ((Maybe Int))
                                                                                (RecCons Hot_mon_source_1 ((Maybe Int))
                                                                                 (RecCons Hot_mon_id_1 (Int)
                                                                                  (RecCons Hot_mon_id_2 ((Maybe Int))
                                                                                   (RecCons Hot_mon_rate_2 ((Maybe Int))
                                                                                    (RecCons Hot_mon_source_2 ((Maybe Int))
                                                                                     (RecCons Hot_skype ((Maybe String))
                                                                                      (RecCons Hot_facebook ((Maybe String))
                                                                                       (RecCons Hot_twitter ((Maybe String))
                                                                                        (RecCons Hot_google_plus ((Maybe String))
                                                                                         (RecCons Hot_observation ((Maybe String))
                                                                                          (RecCons Hot_cdn_id ((Maybe Int))
                                                                                           (RecCons Hot_status_reg (String)
                                                                                            (RecCons Hot_updated_by (Int)
                                                                                             (RecCons Hot_updated ((Maybe CalendarTime))
                                                                                              (RecCons Hot_created ((Maybe CalendarTime)) RecNil)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hOT :: Table HOT
hOT = baseTable "HOT" $
      hdbMakeEntry Hot_id #
      hdbMakeEntry Hot_name #
      hdbMakeEntry Hot_description #
      hdbMakeEntry Hot_address #
      hdbMakeEntry Hot_alternative_address #
      hdbMakeEntry Hot_type #
      hdbMakeEntry Hot_category_level #
      hdbMakeEntry Hot_master_usr_id #
      hdbMakeEntry Hot_email_1 #
      hdbMakeEntry Hot_email_2 #
      hdbMakeEntry Hot_email_3 #
      hdbMakeEntry Hot_phone_1 #
      hdbMakeEntry Hot_phone_2 #
      hdbMakeEntry Hot_phone_3 #
      hdbMakeEntry Hot_fax #
      hdbMakeEntry Hot_web_page_url #
      hdbMakeEntry Hot_logo #
      hdbMakeEntry Hot_slogan #
      hdbMakeEntry Hot_theme #
      hdbMakeEntry Hot_pai_id #
      hdbMakeEntry Hot_edo_id #
      hdbMakeEntry Hot_lug_id #
      hdbMakeEntry Hot_des_id #
      hdbMakeEntry Hot_plc_id #
      hdbMakeEntry Hot_plc_id_new #
      hdbMakeEntry Hot_gmaps #
      hdbMakeEntry Hot_gmaps_url #
      hdbMakeEntry Hot_map #
      hdbMakeEntry Hot_map_hash #
      hdbMakeEntry Hot_section_config #
      hdbMakeEntry Hot_languages #
      hdbMakeEntry Hot_base_lang #
      hdbMakeEntry Hot_fac_rest #
      hdbMakeEntry Hot_fac_bar #
      hdbMakeEntry Hot_fac_pool #
      hdbMakeEntry Hot_fac_children_pool #
      hdbMakeEntry Hot_fac_tv #
      hdbMakeEntry Hot_fac_wifi #
      hdbMakeEntry Hot_fac_casino #
      hdbMakeEntry Hot_fac_lounge #
      hdbMakeEntry Hot_fac_business_center #
      hdbMakeEntry Hot_fac_gym #
      hdbMakeEntry Hot_fac_spa #
      hdbMakeEntry Hot_fac_hairdressing #
      hdbMakeEntry Hot_fac_crib #
      hdbMakeEntry Hot_fac_laundry #
      hdbMakeEntry Hot_fac_store #
      hdbMakeEntry Hot_fac_fax #
      hdbMakeEntry Hot_fac_alarm_clock #
      hdbMakeEntry Hot_fac_handicap_access #
      hdbMakeEntry Hot_fac_entertainment #
      hdbMakeEntry Hot_fac_playroom #
      hdbMakeEntry Hot_fac_atm #
      hdbMakeEntry Hot_fac_power_plant #
      hdbMakeEntry Hot_fac_parking #
      hdbMakeEntry Hot_fac_extra #
      hdbMakeEntry Hot_fac_parking_other #
      hdbMakeEntry Hot_time_checkin_min #
      hdbMakeEntry Hot_time_checkin_max #
      hdbMakeEntry Hot_time_checkout_min #
      hdbMakeEntry Hot_time_checkout_max #
      hdbMakeEntry Hot_pets #
      hdbMakeEntry Hot_pets_info #
      hdbMakeEntry Hot_pax_complete_info #
      hdbMakeEntry Hot_pax_adults_info #
      hdbMakeEntry Hot_pax_children_info #
      hdbMakeEntry Hot_pax_seniors_info #
      hdbMakeEntry Hot_pax_ci #
      hdbMakeEntry Hot_pax_phone #
      hdbMakeEntry Hot_pax_email #
      hdbMakeEntry Hot_children_max_age #
      hdbMakeEntry Hot_children_min_age #
      hdbMakeEntry Hot_senior_min_age #
      hdbMakeEntry Hot_additional_field_1 #
      hdbMakeEntry Hot_total_rooms #
      hdbMakeEntry Hot_mon_rate_1 #
      hdbMakeEntry Hot_mon_source_1 #
      hdbMakeEntry Hot_mon_id_1 #
      hdbMakeEntry Hot_mon_id_2 #
      hdbMakeEntry Hot_mon_rate_2 #
      hdbMakeEntry Hot_mon_source_2 #
      hdbMakeEntry Hot_skype #
      hdbMakeEntry Hot_facebook #
      hdbMakeEntry Hot_twitter #
      hdbMakeEntry Hot_google_plus #
      hdbMakeEntry Hot_observation #
      hdbMakeEntry Hot_cdn_id #
      hdbMakeEntry Hot_status_reg #
      hdbMakeEntry Hot_updated_by #
      hdbMakeEntry Hot_updated #
      hdbMakeEntry Hot_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hot_id Field
---------------------------------------------------------------------------

data Hot_id = Hot_id

instance FieldTag Hot_id where fieldName _ = "hot_id"

hot_id :: Attr Hot_id (Maybe Int)
hot_id = mkAttr Hot_id

---------------------------------------------------------------------------
-- Hot_name Field
---------------------------------------------------------------------------

data Hot_name = Hot_name

instance FieldTag Hot_name where fieldName _ = "hot_name"

hot_name :: Attr Hot_name String
hot_name = mkAttr Hot_name

---------------------------------------------------------------------------
-- Hot_description Field
---------------------------------------------------------------------------

data Hot_description = Hot_description

instance FieldTag Hot_description where
    fieldName _ = "hot_description"

hot_description :: Attr Hot_description (Maybe String)
hot_description = mkAttr Hot_description

---------------------------------------------------------------------------
-- Hot_address Field
---------------------------------------------------------------------------

data Hot_address = Hot_address

instance FieldTag Hot_address where fieldName _ = "hot_address"

hot_address :: Attr Hot_address (Maybe String)
hot_address = mkAttr Hot_address

---------------------------------------------------------------------------
-- Hot_alternative_address Field
---------------------------------------------------------------------------

data Hot_alternative_address = Hot_alternative_address

instance FieldTag Hot_alternative_address where
    fieldName _ = "hot_alternative_address"

hot_alternative_address :: Attr Hot_alternative_address (Maybe String)
hot_alternative_address = mkAttr Hot_alternative_address

---------------------------------------------------------------------------
-- Hot_type Field
---------------------------------------------------------------------------

data Hot_type = Hot_type

instance FieldTag Hot_type where fieldName _ = "hot_type"

hot_type :: Attr Hot_type (Maybe String)
hot_type = mkAttr Hot_type

---------------------------------------------------------------------------
-- Hot_category_level Field
---------------------------------------------------------------------------

data Hot_category_level = Hot_category_level

instance FieldTag Hot_category_level where
    fieldName _ = "hot_category_level"

hot_category_level :: Attr Hot_category_level (Maybe String)
hot_category_level = mkAttr Hot_category_level

---------------------------------------------------------------------------
-- Hot_master_usr_id Field
---------------------------------------------------------------------------

data Hot_master_usr_id = Hot_master_usr_id

instance FieldTag Hot_master_usr_id where
    fieldName _ = "hot_master_usr_id"

hot_master_usr_id :: Attr Hot_master_usr_id Int
hot_master_usr_id = mkAttr Hot_master_usr_id

---------------------------------------------------------------------------
-- Hot_email_1 Field
---------------------------------------------------------------------------

data Hot_email_1 = Hot_email_1

instance FieldTag Hot_email_1 where fieldName _ = "hot_email_1"

hot_email_1 :: Attr Hot_email_1 String
hot_email_1 = mkAttr Hot_email_1

---------------------------------------------------------------------------
-- Hot_email_2 Field
---------------------------------------------------------------------------

data Hot_email_2 = Hot_email_2

instance FieldTag Hot_email_2 where fieldName _ = "hot_email_2"

hot_email_2 :: Attr Hot_email_2 (Maybe String)
hot_email_2 = mkAttr Hot_email_2

---------------------------------------------------------------------------
-- Hot_email_3 Field
---------------------------------------------------------------------------

data Hot_email_3 = Hot_email_3

instance FieldTag Hot_email_3 where fieldName _ = "hot_email_3"

hot_email_3 :: Attr Hot_email_3 (Maybe String)
hot_email_3 = mkAttr Hot_email_3

---------------------------------------------------------------------------
-- Hot_phone_1 Field
---------------------------------------------------------------------------

data Hot_phone_1 = Hot_phone_1

instance FieldTag Hot_phone_1 where fieldName _ = "hot_phone_1"

hot_phone_1 :: Attr Hot_phone_1 String
hot_phone_1 = mkAttr Hot_phone_1

---------------------------------------------------------------------------
-- Hot_phone_2 Field
---------------------------------------------------------------------------

data Hot_phone_2 = Hot_phone_2

instance FieldTag Hot_phone_2 where fieldName _ = "hot_phone_2"

hot_phone_2 :: Attr Hot_phone_2 (Maybe String)
hot_phone_2 = mkAttr Hot_phone_2

---------------------------------------------------------------------------
-- Hot_phone_3 Field
---------------------------------------------------------------------------

data Hot_phone_3 = Hot_phone_3

instance FieldTag Hot_phone_3 where fieldName _ = "hot_phone_3"

hot_phone_3 :: Attr Hot_phone_3 (Maybe String)
hot_phone_3 = mkAttr Hot_phone_3

---------------------------------------------------------------------------
-- Hot_fax Field
---------------------------------------------------------------------------

data Hot_fax = Hot_fax

instance FieldTag Hot_fax where fieldName _ = "hot_fax"

hot_fax :: Attr Hot_fax (Maybe String)
hot_fax = mkAttr Hot_fax

---------------------------------------------------------------------------
-- Hot_web_page_url Field
---------------------------------------------------------------------------

data Hot_web_page_url = Hot_web_page_url

instance FieldTag Hot_web_page_url where
    fieldName _ = "hot_web_page_url"

hot_web_page_url :: Attr Hot_web_page_url (Maybe String)
hot_web_page_url = mkAttr Hot_web_page_url

---------------------------------------------------------------------------
-- Hot_logo Field
---------------------------------------------------------------------------

data Hot_logo = Hot_logo

instance FieldTag Hot_logo where fieldName _ = "hot_logo"

hot_logo :: Attr Hot_logo (Maybe String)
hot_logo = mkAttr Hot_logo

---------------------------------------------------------------------------
-- Hot_slogan Field
---------------------------------------------------------------------------

data Hot_slogan = Hot_slogan

instance FieldTag Hot_slogan where fieldName _ = "hot_slogan"

hot_slogan :: Attr Hot_slogan (Maybe String)
hot_slogan = mkAttr Hot_slogan

---------------------------------------------------------------------------
-- Hot_theme Field
---------------------------------------------------------------------------

data Hot_theme = Hot_theme

instance FieldTag Hot_theme where fieldName _ = "hot_theme"

hot_theme :: Attr Hot_theme String
hot_theme = mkAttr Hot_theme

---------------------------------------------------------------------------
-- Hot_pai_id Field
---------------------------------------------------------------------------

data Hot_pai_id = Hot_pai_id

instance FieldTag Hot_pai_id where fieldName _ = "hot_pai_id"

hot_pai_id :: Attr Hot_pai_id Int
hot_pai_id = mkAttr Hot_pai_id

---------------------------------------------------------------------------
-- Hot_edo_id Field
---------------------------------------------------------------------------

data Hot_edo_id = Hot_edo_id

instance FieldTag Hot_edo_id where fieldName _ = "hot_edo_id"

hot_edo_id :: Attr Hot_edo_id Int
hot_edo_id = mkAttr Hot_edo_id

---------------------------------------------------------------------------
-- Hot_lug_id Field
---------------------------------------------------------------------------

data Hot_lug_id = Hot_lug_id

instance FieldTag Hot_lug_id where fieldName _ = "hot_lug_id"

hot_lug_id :: Attr Hot_lug_id Int
hot_lug_id = mkAttr Hot_lug_id

---------------------------------------------------------------------------
-- Hot_des_id Field
---------------------------------------------------------------------------

data Hot_des_id = Hot_des_id

instance FieldTag Hot_des_id where fieldName _ = "hot_des_id"

hot_des_id :: Attr Hot_des_id (Maybe Int)
hot_des_id = mkAttr Hot_des_id

---------------------------------------------------------------------------
-- Hot_plc_id Field
---------------------------------------------------------------------------

data Hot_plc_id = Hot_plc_id

instance FieldTag Hot_plc_id where fieldName _ = "hot_plc_id"

hot_plc_id :: Attr Hot_plc_id Int
hot_plc_id = mkAttr Hot_plc_id

---------------------------------------------------------------------------
-- Hot_plc_id_new Field
---------------------------------------------------------------------------

data Hot_plc_id_new = Hot_plc_id_new

instance FieldTag Hot_plc_id_new where
    fieldName _ = "hot_plc_id_new"

hot_plc_id_new :: Attr Hot_plc_id_new (Maybe Int)
hot_plc_id_new = mkAttr Hot_plc_id_new

---------------------------------------------------------------------------
-- Hot_gmaps Field
---------------------------------------------------------------------------

data Hot_gmaps = Hot_gmaps

instance FieldTag Hot_gmaps where fieldName _ = "hot_gmaps"

hot_gmaps :: Attr Hot_gmaps (Maybe Bool)
hot_gmaps = mkAttr Hot_gmaps

---------------------------------------------------------------------------
-- Hot_gmaps_url Field
---------------------------------------------------------------------------

data Hot_gmaps_url = Hot_gmaps_url

instance FieldTag Hot_gmaps_url where
    fieldName _ = "hot_gmaps_url"

hot_gmaps_url :: Attr Hot_gmaps_url (Maybe String)
hot_gmaps_url = mkAttr Hot_gmaps_url

---------------------------------------------------------------------------
-- Hot_map Field
---------------------------------------------------------------------------

data Hot_map = Hot_map

instance FieldTag Hot_map where fieldName _ = "hot_map"

hot_map :: Attr Hot_map (Maybe Bool)
hot_map = mkAttr Hot_map

---------------------------------------------------------------------------
-- Hot_map_hash Field
---------------------------------------------------------------------------

data Hot_map_hash = Hot_map_hash

instance FieldTag Hot_map_hash where fieldName _ = "hot_map_hash"

hot_map_hash :: Attr Hot_map_hash (Maybe String)
hot_map_hash = mkAttr Hot_map_hash

---------------------------------------------------------------------------
-- Hot_section_config Field
---------------------------------------------------------------------------

data Hot_section_config = Hot_section_config

instance FieldTag Hot_section_config where
    fieldName _ = "hot_section_config"

hot_section_config :: Attr Hot_section_config (Maybe String)
hot_section_config = mkAttr Hot_section_config

---------------------------------------------------------------------------
-- Hot_languages Field
---------------------------------------------------------------------------

data Hot_languages = Hot_languages

instance FieldTag Hot_languages where
    fieldName _ = "hot_languages"

hot_languages :: Attr Hot_languages (Maybe String)
hot_languages = mkAttr Hot_languages

---------------------------------------------------------------------------
-- Hot_base_lang Field
---------------------------------------------------------------------------

data Hot_base_lang = Hot_base_lang

instance FieldTag Hot_base_lang where
    fieldName _ = "hot_base_lang"

hot_base_lang :: Attr Hot_base_lang (Maybe String)
hot_base_lang = mkAttr Hot_base_lang

---------------------------------------------------------------------------
-- Hot_fac_rest Field
---------------------------------------------------------------------------

data Hot_fac_rest = Hot_fac_rest

instance FieldTag Hot_fac_rest where fieldName _ = "hot_fac_rest"

hot_fac_rest :: Attr Hot_fac_rest (Maybe Bool)
hot_fac_rest = mkAttr Hot_fac_rest

---------------------------------------------------------------------------
-- Hot_fac_bar Field
---------------------------------------------------------------------------

data Hot_fac_bar = Hot_fac_bar

instance FieldTag Hot_fac_bar where fieldName _ = "hot_fac_bar"

hot_fac_bar :: Attr Hot_fac_bar (Maybe Bool)
hot_fac_bar = mkAttr Hot_fac_bar

---------------------------------------------------------------------------
-- Hot_fac_pool Field
---------------------------------------------------------------------------

data Hot_fac_pool = Hot_fac_pool

instance FieldTag Hot_fac_pool where fieldName _ = "hot_fac_pool"

hot_fac_pool :: Attr Hot_fac_pool (Maybe Bool)
hot_fac_pool = mkAttr Hot_fac_pool

---------------------------------------------------------------------------
-- Hot_fac_children_pool Field
---------------------------------------------------------------------------

data Hot_fac_children_pool = Hot_fac_children_pool

instance FieldTag Hot_fac_children_pool where
    fieldName _ = "hot_fac_children_pool"

hot_fac_children_pool :: Attr Hot_fac_children_pool (Maybe Bool)
hot_fac_children_pool = mkAttr Hot_fac_children_pool

---------------------------------------------------------------------------
-- Hot_fac_tv Field
---------------------------------------------------------------------------

data Hot_fac_tv = Hot_fac_tv

instance FieldTag Hot_fac_tv where fieldName _ = "hot_fac_tv"

hot_fac_tv :: Attr Hot_fac_tv (Maybe Bool)
hot_fac_tv = mkAttr Hot_fac_tv

---------------------------------------------------------------------------
-- Hot_fac_wifi Field
---------------------------------------------------------------------------

data Hot_fac_wifi = Hot_fac_wifi

instance FieldTag Hot_fac_wifi where fieldName _ = "hot_fac_wifi"

hot_fac_wifi :: Attr Hot_fac_wifi (Maybe Bool)
hot_fac_wifi = mkAttr Hot_fac_wifi

---------------------------------------------------------------------------
-- Hot_fac_casino Field
---------------------------------------------------------------------------

data Hot_fac_casino = Hot_fac_casino

instance FieldTag Hot_fac_casino where
    fieldName _ = "hot_fac_casino"

hot_fac_casino :: Attr Hot_fac_casino (Maybe Bool)
hot_fac_casino = mkAttr Hot_fac_casino

---------------------------------------------------------------------------
-- Hot_fac_lounge Field
---------------------------------------------------------------------------

data Hot_fac_lounge = Hot_fac_lounge

instance FieldTag Hot_fac_lounge where
    fieldName _ = "hot_fac_lounge"

hot_fac_lounge :: Attr Hot_fac_lounge (Maybe Bool)
hot_fac_lounge = mkAttr Hot_fac_lounge

---------------------------------------------------------------------------
-- Hot_fac_business_center Field
---------------------------------------------------------------------------

data Hot_fac_business_center = Hot_fac_business_center

instance FieldTag Hot_fac_business_center where
    fieldName _ = "hot_fac_business_center"

hot_fac_business_center :: Attr Hot_fac_business_center (Maybe Bool)
hot_fac_business_center = mkAttr Hot_fac_business_center

---------------------------------------------------------------------------
-- Hot_fac_gym Field
---------------------------------------------------------------------------

data Hot_fac_gym = Hot_fac_gym

instance FieldTag Hot_fac_gym where fieldName _ = "hot_fac_gym"

hot_fac_gym :: Attr Hot_fac_gym (Maybe Bool)
hot_fac_gym = mkAttr Hot_fac_gym

---------------------------------------------------------------------------
-- Hot_fac_spa Field
---------------------------------------------------------------------------

data Hot_fac_spa = Hot_fac_spa

instance FieldTag Hot_fac_spa where fieldName _ = "hot_fac_spa"

hot_fac_spa :: Attr Hot_fac_spa (Maybe Bool)
hot_fac_spa = mkAttr Hot_fac_spa

---------------------------------------------------------------------------
-- Hot_fac_hairdressing Field
---------------------------------------------------------------------------

data Hot_fac_hairdressing = Hot_fac_hairdressing

instance FieldTag Hot_fac_hairdressing where
    fieldName _ = "hot_fac_hairdressing"

hot_fac_hairdressing :: Attr Hot_fac_hairdressing (Maybe Bool)
hot_fac_hairdressing = mkAttr Hot_fac_hairdressing

---------------------------------------------------------------------------
-- Hot_fac_crib Field
---------------------------------------------------------------------------

data Hot_fac_crib = Hot_fac_crib

instance FieldTag Hot_fac_crib where fieldName _ = "hot_fac_crib"

hot_fac_crib :: Attr Hot_fac_crib (Maybe Bool)
hot_fac_crib = mkAttr Hot_fac_crib

---------------------------------------------------------------------------
-- Hot_fac_laundry Field
---------------------------------------------------------------------------

data Hot_fac_laundry = Hot_fac_laundry

instance FieldTag Hot_fac_laundry where
    fieldName _ = "hot_fac_laundry"

hot_fac_laundry :: Attr Hot_fac_laundry (Maybe Bool)
hot_fac_laundry = mkAttr Hot_fac_laundry

---------------------------------------------------------------------------
-- Hot_fac_store Field
---------------------------------------------------------------------------

data Hot_fac_store = Hot_fac_store

instance FieldTag Hot_fac_store where
    fieldName _ = "hot_fac_store"

hot_fac_store :: Attr Hot_fac_store (Maybe Bool)
hot_fac_store = mkAttr Hot_fac_store

---------------------------------------------------------------------------
-- Hot_fac_fax Field
---------------------------------------------------------------------------

data Hot_fac_fax = Hot_fac_fax

instance FieldTag Hot_fac_fax where fieldName _ = "hot_fac_fax"

hot_fac_fax :: Attr Hot_fac_fax (Maybe Bool)
hot_fac_fax = mkAttr Hot_fac_fax

---------------------------------------------------------------------------
-- Hot_fac_alarm_clock Field
---------------------------------------------------------------------------

data Hot_fac_alarm_clock = Hot_fac_alarm_clock

instance FieldTag Hot_fac_alarm_clock where
    fieldName _ = "hot_fac_alarm_clock"

hot_fac_alarm_clock :: Attr Hot_fac_alarm_clock (Maybe Bool)
hot_fac_alarm_clock = mkAttr Hot_fac_alarm_clock

---------------------------------------------------------------------------
-- Hot_fac_handicap_access Field
---------------------------------------------------------------------------

data Hot_fac_handicap_access = Hot_fac_handicap_access

instance FieldTag Hot_fac_handicap_access where
    fieldName _ = "hot_fac_handicap_access"

hot_fac_handicap_access :: Attr Hot_fac_handicap_access (Maybe Bool)
hot_fac_handicap_access = mkAttr Hot_fac_handicap_access

---------------------------------------------------------------------------
-- Hot_fac_entertainment Field
---------------------------------------------------------------------------

data Hot_fac_entertainment = Hot_fac_entertainment

instance FieldTag Hot_fac_entertainment where
    fieldName _ = "hot_fac_entertainment"

hot_fac_entertainment :: Attr Hot_fac_entertainment (Maybe Bool)
hot_fac_entertainment = mkAttr Hot_fac_entertainment

---------------------------------------------------------------------------
-- Hot_fac_playroom Field
---------------------------------------------------------------------------

data Hot_fac_playroom = Hot_fac_playroom

instance FieldTag Hot_fac_playroom where
    fieldName _ = "hot_fac_playroom"

hot_fac_playroom :: Attr Hot_fac_playroom (Maybe Bool)
hot_fac_playroom = mkAttr Hot_fac_playroom

---------------------------------------------------------------------------
-- Hot_fac_atm Field
---------------------------------------------------------------------------

data Hot_fac_atm = Hot_fac_atm

instance FieldTag Hot_fac_atm where fieldName _ = "hot_fac_atm"

hot_fac_atm :: Attr Hot_fac_atm (Maybe Bool)
hot_fac_atm = mkAttr Hot_fac_atm

---------------------------------------------------------------------------
-- Hot_fac_power_plant Field
---------------------------------------------------------------------------

data Hot_fac_power_plant = Hot_fac_power_plant

instance FieldTag Hot_fac_power_plant where
    fieldName _ = "hot_fac_power_plant"

hot_fac_power_plant :: Attr Hot_fac_power_plant (Maybe Bool)
hot_fac_power_plant = mkAttr Hot_fac_power_plant

---------------------------------------------------------------------------
-- Hot_fac_parking Field
---------------------------------------------------------------------------

data Hot_fac_parking = Hot_fac_parking

instance FieldTag Hot_fac_parking where
    fieldName _ = "hot_fac_parking"

hot_fac_parking :: Attr Hot_fac_parking (Maybe Bool)
hot_fac_parking = mkAttr Hot_fac_parking

---------------------------------------------------------------------------
-- Hot_fac_extra Field
---------------------------------------------------------------------------

data Hot_fac_extra = Hot_fac_extra

instance FieldTag Hot_fac_extra where
    fieldName _ = "hot_fac_extra"

hot_fac_extra :: Attr Hot_fac_extra (Maybe String)
hot_fac_extra = mkAttr Hot_fac_extra

---------------------------------------------------------------------------
-- Hot_fac_parking_other Field
---------------------------------------------------------------------------

data Hot_fac_parking_other = Hot_fac_parking_other

instance FieldTag Hot_fac_parking_other where
    fieldName _ = "hot_fac_parking_other"

hot_fac_parking_other :: Attr Hot_fac_parking_other (Maybe String)
hot_fac_parking_other = mkAttr Hot_fac_parking_other

---------------------------------------------------------------------------
-- Hot_time_checkin_min Field
---------------------------------------------------------------------------

data Hot_time_checkin_min = Hot_time_checkin_min

instance FieldTag Hot_time_checkin_min where
    fieldName _ = "hot_time_checkin_min"

hot_time_checkin_min :: Attr Hot_time_checkin_min (Maybe CalendarTime)
hot_time_checkin_min = mkAttr Hot_time_checkin_min

---------------------------------------------------------------------------
-- Hot_time_checkin_max Field
---------------------------------------------------------------------------

data Hot_time_checkin_max = Hot_time_checkin_max

instance FieldTag Hot_time_checkin_max where
    fieldName _ = "hot_time_checkin_max"

hot_time_checkin_max :: Attr Hot_time_checkin_max (Maybe CalendarTime)
hot_time_checkin_max = mkAttr Hot_time_checkin_max

---------------------------------------------------------------------------
-- Hot_time_checkout_min Field
---------------------------------------------------------------------------

data Hot_time_checkout_min = Hot_time_checkout_min

instance FieldTag Hot_time_checkout_min where
    fieldName _ = "hot_time_checkout_min"

hot_time_checkout_min :: Attr Hot_time_checkout_min (Maybe CalendarTime)
hot_time_checkout_min = mkAttr Hot_time_checkout_min

---------------------------------------------------------------------------
-- Hot_time_checkout_max Field
---------------------------------------------------------------------------

data Hot_time_checkout_max = Hot_time_checkout_max

instance FieldTag Hot_time_checkout_max where
    fieldName _ = "hot_time_checkout_max"

hot_time_checkout_max :: Attr Hot_time_checkout_max (Maybe CalendarTime)
hot_time_checkout_max = mkAttr Hot_time_checkout_max

---------------------------------------------------------------------------
-- Hot_pets Field
---------------------------------------------------------------------------

data Hot_pets = Hot_pets

instance FieldTag Hot_pets where fieldName _ = "hot_pets"

hot_pets :: Attr Hot_pets (Maybe Bool)
hot_pets = mkAttr Hot_pets

---------------------------------------------------------------------------
-- Hot_pets_info Field
---------------------------------------------------------------------------

data Hot_pets_info = Hot_pets_info

instance FieldTag Hot_pets_info where
    fieldName _ = "hot_pets_info"

hot_pets_info :: Attr Hot_pets_info (Maybe String)
hot_pets_info = mkAttr Hot_pets_info

---------------------------------------------------------------------------
-- Hot_pax_complete_info Field
---------------------------------------------------------------------------

data Hot_pax_complete_info = Hot_pax_complete_info

instance FieldTag Hot_pax_complete_info where
    fieldName _ = "hot_pax_complete_info"

hot_pax_complete_info :: Attr Hot_pax_complete_info (Maybe Bool)
hot_pax_complete_info = mkAttr Hot_pax_complete_info

---------------------------------------------------------------------------
-- Hot_pax_adults_info Field
---------------------------------------------------------------------------

data Hot_pax_adults_info = Hot_pax_adults_info

instance FieldTag Hot_pax_adults_info where
    fieldName _ = "hot_pax_adults_info"

hot_pax_adults_info :: Attr Hot_pax_adults_info (Maybe Bool)
hot_pax_adults_info = mkAttr Hot_pax_adults_info

---------------------------------------------------------------------------
-- Hot_pax_children_info Field
---------------------------------------------------------------------------

data Hot_pax_children_info = Hot_pax_children_info

instance FieldTag Hot_pax_children_info where
    fieldName _ = "hot_pax_children_info"

hot_pax_children_info :: Attr Hot_pax_children_info (Maybe Bool)
hot_pax_children_info = mkAttr Hot_pax_children_info

---------------------------------------------------------------------------
-- Hot_pax_seniors_info Field
---------------------------------------------------------------------------

data Hot_pax_seniors_info = Hot_pax_seniors_info

instance FieldTag Hot_pax_seniors_info where
    fieldName _ = "hot_pax_seniors_info"

hot_pax_seniors_info :: Attr Hot_pax_seniors_info (Maybe Bool)
hot_pax_seniors_info = mkAttr Hot_pax_seniors_info

---------------------------------------------------------------------------
-- Hot_pax_ci Field
---------------------------------------------------------------------------

data Hot_pax_ci = Hot_pax_ci

instance FieldTag Hot_pax_ci where fieldName _ = "hot_pax_ci"

hot_pax_ci :: Attr Hot_pax_ci (Maybe Bool)
hot_pax_ci = mkAttr Hot_pax_ci

---------------------------------------------------------------------------
-- Hot_pax_phone Field
---------------------------------------------------------------------------

data Hot_pax_phone = Hot_pax_phone

instance FieldTag Hot_pax_phone where
    fieldName _ = "hot_pax_phone"

hot_pax_phone :: Attr Hot_pax_phone (Maybe Bool)
hot_pax_phone = mkAttr Hot_pax_phone

---------------------------------------------------------------------------
-- Hot_pax_email Field
---------------------------------------------------------------------------

data Hot_pax_email = Hot_pax_email

instance FieldTag Hot_pax_email where
    fieldName _ = "hot_pax_email"

hot_pax_email :: Attr Hot_pax_email (Maybe Bool)
hot_pax_email = mkAttr Hot_pax_email

---------------------------------------------------------------------------
-- Hot_children_max_age Field
---------------------------------------------------------------------------

data Hot_children_max_age = Hot_children_max_age

instance FieldTag Hot_children_max_age where
    fieldName _ = "hot_children_max_age"

hot_children_max_age :: Attr Hot_children_max_age Int
hot_children_max_age = mkAttr Hot_children_max_age

---------------------------------------------------------------------------
-- Hot_children_min_age Field
---------------------------------------------------------------------------

data Hot_children_min_age = Hot_children_min_age

instance FieldTag Hot_children_min_age where
    fieldName _ = "hot_children_min_age"

hot_children_min_age :: Attr Hot_children_min_age Int
hot_children_min_age = mkAttr Hot_children_min_age

---------------------------------------------------------------------------
-- Hot_senior_min_age Field
---------------------------------------------------------------------------

data Hot_senior_min_age = Hot_senior_min_age

instance FieldTag Hot_senior_min_age where
    fieldName _ = "hot_senior_min_age"

hot_senior_min_age :: Attr Hot_senior_min_age Int
hot_senior_min_age = mkAttr Hot_senior_min_age

---------------------------------------------------------------------------
-- Hot_additional_field_1 Field
---------------------------------------------------------------------------

data Hot_additional_field_1 = Hot_additional_field_1

instance FieldTag Hot_additional_field_1 where
    fieldName _ = "hot_additional_field_1"

hot_additional_field_1 :: Attr Hot_additional_field_1 (Maybe String)
hot_additional_field_1 = mkAttr Hot_additional_field_1

---------------------------------------------------------------------------
-- Hot_total_rooms Field
---------------------------------------------------------------------------

data Hot_total_rooms = Hot_total_rooms

instance FieldTag Hot_total_rooms where
    fieldName _ = "hot_total_rooms"

hot_total_rooms :: Attr Hot_total_rooms Int
hot_total_rooms = mkAttr Hot_total_rooms

---------------------------------------------------------------------------
-- Hot_mon_rate_1 Field
---------------------------------------------------------------------------

data Hot_mon_rate_1 = Hot_mon_rate_1

instance FieldTag Hot_mon_rate_1 where
    fieldName _ = "hot_mon_rate_1"

hot_mon_rate_1 :: Attr Hot_mon_rate_1 (Maybe Int)
hot_mon_rate_1 = mkAttr Hot_mon_rate_1

---------------------------------------------------------------------------
-- Hot_mon_source_1 Field
---------------------------------------------------------------------------

data Hot_mon_source_1 = Hot_mon_source_1

instance FieldTag Hot_mon_source_1 where
    fieldName _ = "hot_mon_source_1"

hot_mon_source_1 :: Attr Hot_mon_source_1 (Maybe Int)
hot_mon_source_1 = mkAttr Hot_mon_source_1

---------------------------------------------------------------------------
-- Hot_mon_id_1 Field
---------------------------------------------------------------------------

data Hot_mon_id_1 = Hot_mon_id_1

instance FieldTag Hot_mon_id_1 where fieldName _ = "hot_mon_id_1"

hot_mon_id_1 :: Attr Hot_mon_id_1 Int
hot_mon_id_1 = mkAttr Hot_mon_id_1

---------------------------------------------------------------------------
-- Hot_mon_id_2 Field
---------------------------------------------------------------------------

data Hot_mon_id_2 = Hot_mon_id_2

instance FieldTag Hot_mon_id_2 where fieldName _ = "hot_mon_id_2"

hot_mon_id_2 :: Attr Hot_mon_id_2 (Maybe Int)
hot_mon_id_2 = mkAttr Hot_mon_id_2

---------------------------------------------------------------------------
-- Hot_mon_rate_2 Field
---------------------------------------------------------------------------

data Hot_mon_rate_2 = Hot_mon_rate_2

instance FieldTag Hot_mon_rate_2 where
    fieldName _ = "hot_mon_rate_2"

hot_mon_rate_2 :: Attr Hot_mon_rate_2 (Maybe Int)
hot_mon_rate_2 = mkAttr Hot_mon_rate_2

---------------------------------------------------------------------------
-- Hot_mon_source_2 Field
---------------------------------------------------------------------------

data Hot_mon_source_2 = Hot_mon_source_2

instance FieldTag Hot_mon_source_2 where
    fieldName _ = "hot_mon_source_2"

hot_mon_source_2 :: Attr Hot_mon_source_2 (Maybe Int)
hot_mon_source_2 = mkAttr Hot_mon_source_2

---------------------------------------------------------------------------
-- Hot_skype Field
---------------------------------------------------------------------------

data Hot_skype = Hot_skype

instance FieldTag Hot_skype where fieldName _ = "hot_skype"

hot_skype :: Attr Hot_skype (Maybe String)
hot_skype = mkAttr Hot_skype

---------------------------------------------------------------------------
-- Hot_facebook Field
---------------------------------------------------------------------------

data Hot_facebook = Hot_facebook

instance FieldTag Hot_facebook where fieldName _ = "hot_facebook"

hot_facebook :: Attr Hot_facebook (Maybe String)
hot_facebook = mkAttr Hot_facebook

---------------------------------------------------------------------------
-- Hot_twitter Field
---------------------------------------------------------------------------

data Hot_twitter = Hot_twitter

instance FieldTag Hot_twitter where fieldName _ = "hot_twitter"

hot_twitter :: Attr Hot_twitter (Maybe String)
hot_twitter = mkAttr Hot_twitter

---------------------------------------------------------------------------
-- Hot_google_plus Field
---------------------------------------------------------------------------

data Hot_google_plus = Hot_google_plus

instance FieldTag Hot_google_plus where
    fieldName _ = "hot_google_plus"

hot_google_plus :: Attr Hot_google_plus (Maybe String)
hot_google_plus = mkAttr Hot_google_plus

---------------------------------------------------------------------------
-- Hot_observation Field
---------------------------------------------------------------------------

data Hot_observation = Hot_observation

instance FieldTag Hot_observation where
    fieldName _ = "hot_observation"

hot_observation :: Attr Hot_observation (Maybe String)
hot_observation = mkAttr Hot_observation

---------------------------------------------------------------------------
-- Hot_cdn_id Field
---------------------------------------------------------------------------

data Hot_cdn_id = Hot_cdn_id

instance FieldTag Hot_cdn_id where fieldName _ = "hot_cdn_id"

hot_cdn_id :: Attr Hot_cdn_id (Maybe Int)
hot_cdn_id = mkAttr Hot_cdn_id

---------------------------------------------------------------------------
-- Hot_status_reg Field
---------------------------------------------------------------------------

data Hot_status_reg = Hot_status_reg

instance FieldTag Hot_status_reg where
    fieldName _ = "hot_status_reg"

hot_status_reg :: Attr Hot_status_reg String
hot_status_reg = mkAttr Hot_status_reg

---------------------------------------------------------------------------
-- Hot_updated_by Field
---------------------------------------------------------------------------

data Hot_updated_by = Hot_updated_by

instance FieldTag Hot_updated_by where
    fieldName _ = "hot_updated_by"

hot_updated_by :: Attr Hot_updated_by Int
hot_updated_by = mkAttr Hot_updated_by

---------------------------------------------------------------------------
-- Hot_updated Field
---------------------------------------------------------------------------

data Hot_updated = Hot_updated

instance FieldTag Hot_updated where fieldName _ = "hot_updated"

hot_updated :: Attr Hot_updated (Maybe CalendarTime)
hot_updated = mkAttr Hot_updated

---------------------------------------------------------------------------
-- Hot_created Field
---------------------------------------------------------------------------

data Hot_created = Hot_created

instance FieldTag Hot_created where fieldName _ = "hot_created"

hot_created :: Attr Hot_created (Maybe CalendarTime)
hot_created = mkAttr Hot_created
