{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack64 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.HOTELCRAWLING where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type HOTELCRAWLING  =
    (RecCons Hc_id Expr (Maybe Int)
     (RecCons Hc_name Expr (Maybe String)
      (RecCons Hc_description Expr (Maybe String)
       (RecCons Hc_price Expr String
        (RecCons Hc_website Expr (Maybe String)
         (RecCons Hc_email Expr (Maybe String)
          (RecCons Hc_cst Expr (Maybe Int)
           (RecCons Hc_tha_number Expr (Maybe Int)
            (RecCons Hc_idpage Expr (Maybe Int)
             (RecCons Hc_address Expr (Maybe String)
              (RecCons Hc_country Expr String
               (RecCons Hc_city Expr String
                (RecCons Hc_county Expr (Maybe String)
                 (RecCons Hc_canton Expr (Maybe String)
                  (RecCons Hc_district Expr (Maybe String)
                   (RecCons Hc_region Expr (Maybe String)
                    (RecCons Hc_municipio Expr (Maybe String)
                     (RecCons Hc_departamento Expr (Maybe String)
                      (RecCons Hc_pobox Expr (Maybe String)
                       (RecCons Hc_phone Expr (Maybe String)
                        (RecCons Hc_fax Expr (Maybe String)
                         (RecCons Hc_facilities Expr (Maybe String)
                          (RecCons Hc_languages Expr (Maybe String)
                           (RecCons Hc_cards Expr (Maybe String) RecNil))))))))))))))))))))))))

type HOTELCRAWLING _result =
    (RecCons Hc_id ((Maybe Int))
     (RecCons Hc_name ((Maybe String))
      (RecCons Hc_description ((Maybe String))
       (RecCons Hc_price (String)
        (RecCons Hc_website ((Maybe String))
         (RecCons Hc_email ((Maybe String))
          (RecCons Hc_cst ((Maybe Int))
           (RecCons Hc_tha_number ((Maybe Int))
            (RecCons Hc_idpage ((Maybe Int))
             (RecCons Hc_address ((Maybe String))
              (RecCons Hc_country (String)
               (RecCons Hc_city (String)
                (RecCons Hc_county ((Maybe String))
                 (RecCons Hc_canton ((Maybe String))
                  (RecCons Hc_district ((Maybe String))
                   (RecCons Hc_region ((Maybe String))
                    (RecCons Hc_municipio ((Maybe String))
                     (RecCons Hc_departamento ((Maybe String))
                      (RecCons Hc_pobox ((Maybe String))
                       (RecCons Hc_phone ((Maybe String))
                        (RecCons Hc_fax ((Maybe String))
                         (RecCons Hc_facilities ((Maybe String))
                          (RecCons Hc_languages ((Maybe String))
                           (RecCons Hc_cards ((Maybe String)) RecNil))))))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
hOTELCRAWLING :: Table HOTELCRAWLING
hOTELCRAWLING = baseTable "HOTELCRAWLING" $
                hdbMakeEntry Hc_id #
                hdbMakeEntry Hc_name #
                hdbMakeEntry Hc_description #
                hdbMakeEntry Hc_price #
                hdbMakeEntry Hc_website #
                hdbMakeEntry Hc_email #
                hdbMakeEntry Hc_cst #
                hdbMakeEntry Hc_tha_number #
                hdbMakeEntry Hc_idpage #
                hdbMakeEntry Hc_address #
                hdbMakeEntry Hc_country #
                hdbMakeEntry Hc_city #
                hdbMakeEntry Hc_county #
                hdbMakeEntry Hc_canton #
                hdbMakeEntry Hc_district #
                hdbMakeEntry Hc_region #
                hdbMakeEntry Hc_municipio #
                hdbMakeEntry Hc_departamento #
                hdbMakeEntry Hc_pobox #
                hdbMakeEntry Hc_phone #
                hdbMakeEntry Hc_fax #
                hdbMakeEntry Hc_facilities #
                hdbMakeEntry Hc_languages #
                hdbMakeEntry Hc_cards

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Hc_id Field
---------------------------------------------------------------------------

data Hc_id = Hc_id

instance FieldTag Hc_id where fieldName _ = "hc_id"

hc_id :: Attr Hc_id (Maybe Int)
hc_id = mkAttr Hc_id

---------------------------------------------------------------------------
-- Hc_name Field
---------------------------------------------------------------------------

data Hc_name = Hc_name

instance FieldTag Hc_name where fieldName _ = "hc_name"

hc_name :: Attr Hc_name (Maybe String)
hc_name = mkAttr Hc_name

---------------------------------------------------------------------------
-- Hc_description Field
---------------------------------------------------------------------------

data Hc_description = Hc_description

instance FieldTag Hc_description where
    fieldName _ = "hc_description"

hc_description :: Attr Hc_description (Maybe String)
hc_description = mkAttr Hc_description

---------------------------------------------------------------------------
-- Hc_price Field
---------------------------------------------------------------------------

data Hc_price = Hc_price

instance FieldTag Hc_price where fieldName _ = "hc_price"

hc_price :: Attr Hc_price String
hc_price = mkAttr Hc_price

---------------------------------------------------------------------------
-- Hc_website Field
---------------------------------------------------------------------------

data Hc_website = Hc_website

instance FieldTag Hc_website where fieldName _ = "hc_website"

hc_website :: Attr Hc_website (Maybe String)
hc_website = mkAttr Hc_website

---------------------------------------------------------------------------
-- Hc_email Field
---------------------------------------------------------------------------

data Hc_email = Hc_email

instance FieldTag Hc_email where fieldName _ = "hc_email"

hc_email :: Attr Hc_email (Maybe String)
hc_email = mkAttr Hc_email

---------------------------------------------------------------------------
-- Hc_cst Field
---------------------------------------------------------------------------

data Hc_cst = Hc_cst

instance FieldTag Hc_cst where fieldName _ = "hc_cst"

hc_cst :: Attr Hc_cst (Maybe Int)
hc_cst = mkAttr Hc_cst

---------------------------------------------------------------------------
-- Hc_tha_number Field
---------------------------------------------------------------------------

data Hc_tha_number = Hc_tha_number

instance FieldTag Hc_tha_number where
    fieldName _ = "hc_tha_number"

hc_tha_number :: Attr Hc_tha_number (Maybe Int)
hc_tha_number = mkAttr Hc_tha_number

---------------------------------------------------------------------------
-- Hc_idpage Field
---------------------------------------------------------------------------

data Hc_idpage = Hc_idpage

instance FieldTag Hc_idpage where fieldName _ = "hc_idpage"

hc_idpage :: Attr Hc_idpage (Maybe Int)
hc_idpage = mkAttr Hc_idpage

---------------------------------------------------------------------------
-- Hc_address Field
---------------------------------------------------------------------------

data Hc_address = Hc_address

instance FieldTag Hc_address where fieldName _ = "hc_address"

hc_address :: Attr Hc_address (Maybe String)
hc_address = mkAttr Hc_address

---------------------------------------------------------------------------
-- Hc_country Field
---------------------------------------------------------------------------

data Hc_country = Hc_country

instance FieldTag Hc_country where fieldName _ = "hc_country"

hc_country :: Attr Hc_country String
hc_country = mkAttr Hc_country

---------------------------------------------------------------------------
-- Hc_city Field
---------------------------------------------------------------------------

data Hc_city = Hc_city

instance FieldTag Hc_city where fieldName _ = "hc_city"

hc_city :: Attr Hc_city String
hc_city = mkAttr Hc_city

---------------------------------------------------------------------------
-- Hc_county Field
---------------------------------------------------------------------------

data Hc_county = Hc_county

instance FieldTag Hc_county where fieldName _ = "hc_county"

hc_county :: Attr Hc_county (Maybe String)
hc_county = mkAttr Hc_county

---------------------------------------------------------------------------
-- Hc_canton Field
---------------------------------------------------------------------------

data Hc_canton = Hc_canton

instance FieldTag Hc_canton where fieldName _ = "hc_canton"

hc_canton :: Attr Hc_canton (Maybe String)
hc_canton = mkAttr Hc_canton

---------------------------------------------------------------------------
-- Hc_district Field
---------------------------------------------------------------------------

data Hc_district = Hc_district

instance FieldTag Hc_district where fieldName _ = "hc_district"

hc_district :: Attr Hc_district (Maybe String)
hc_district = mkAttr Hc_district

---------------------------------------------------------------------------
-- Hc_region Field
---------------------------------------------------------------------------

data Hc_region = Hc_region

instance FieldTag Hc_region where fieldName _ = "hc_region"

hc_region :: Attr Hc_region (Maybe String)
hc_region = mkAttr Hc_region

---------------------------------------------------------------------------
-- Hc_municipio Field
---------------------------------------------------------------------------

data Hc_municipio = Hc_municipio

instance FieldTag Hc_municipio where fieldName _ = "hc_municipio"

hc_municipio :: Attr Hc_municipio (Maybe String)
hc_municipio = mkAttr Hc_municipio

---------------------------------------------------------------------------
-- Hc_departamento Field
---------------------------------------------------------------------------

data Hc_departamento = Hc_departamento

instance FieldTag Hc_departamento where
    fieldName _ = "hc_departamento"

hc_departamento :: Attr Hc_departamento (Maybe String)
hc_departamento = mkAttr Hc_departamento

---------------------------------------------------------------------------
-- Hc_pobox Field
---------------------------------------------------------------------------

data Hc_pobox = Hc_pobox

instance FieldTag Hc_pobox where fieldName _ = "hc_pobox"

hc_pobox :: Attr Hc_pobox (Maybe String)
hc_pobox = mkAttr Hc_pobox

---------------------------------------------------------------------------
-- Hc_phone Field
---------------------------------------------------------------------------

data Hc_phone = Hc_phone

instance FieldTag Hc_phone where fieldName _ = "hc_phone"

hc_phone :: Attr Hc_phone (Maybe String)
hc_phone = mkAttr Hc_phone

---------------------------------------------------------------------------
-- Hc_fax Field
---------------------------------------------------------------------------

data Hc_fax = Hc_fax

instance FieldTag Hc_fax where fieldName _ = "hc_fax"

hc_fax :: Attr Hc_fax (Maybe String)
hc_fax = mkAttr Hc_fax

---------------------------------------------------------------------------
-- Hc_facilities Field
---------------------------------------------------------------------------

data Hc_facilities = Hc_facilities

instance FieldTag Hc_facilities where
    fieldName _ = "hc_facilities"

hc_facilities :: Attr Hc_facilities (Maybe String)
hc_facilities = mkAttr Hc_facilities

---------------------------------------------------------------------------
-- Hc_languages Field
---------------------------------------------------------------------------

data Hc_languages = Hc_languages

instance FieldTag Hc_languages where fieldName _ = "hc_languages"

hc_languages :: Attr Hc_languages (Maybe String)
hc_languages = mkAttr Hc_languages

---------------------------------------------------------------------------
-- Hc_cards Field
---------------------------------------------------------------------------

data Hc_cards = Hc_cards

instance FieldTag Hc_cards where fieldName _ = "hc_cards"

hc_cards :: Attr Hc_cards (Maybe String)
hc_cards = mkAttr Hc_cards
