{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack46 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.LDS where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type LDS  =
    (RecCons Lds_id Expr (Maybe Int)
     (RecCons Lds_des_id Expr Int
      (RecCons Lds_lug_id Expr Int
       (RecCons Lds_updated_by Expr Int
        (RecCons Lds_updated Expr (Maybe CalendarTime)
         (RecCons Lds_created Expr (Maybe CalendarTime) RecNil))))))

type LDS _result =
    (RecCons Lds_id ((Maybe Int))
     (RecCons Lds_des_id (Int)
      (RecCons Lds_lug_id (Int)
       (RecCons Lds_updated_by (Int)
        (RecCons Lds_updated ((Maybe CalendarTime))
         (RecCons Lds_created ((Maybe CalendarTime)) RecNil))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
lDS :: Table LDS
lDS = baseTable "LDS" $
      hdbMakeEntry Lds_id #
      hdbMakeEntry Lds_des_id #
      hdbMakeEntry Lds_lug_id #
      hdbMakeEntry Lds_updated_by #
      hdbMakeEntry Lds_updated #
      hdbMakeEntry Lds_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Lds_id Field
---------------------------------------------------------------------------

data Lds_id = Lds_id

instance FieldTag Lds_id where fieldName _ = "lds_id"

lds_id :: Attr Lds_id (Maybe Int)
lds_id = mkAttr Lds_id

---------------------------------------------------------------------------
-- Lds_des_id Field
---------------------------------------------------------------------------

data Lds_des_id = Lds_des_id

instance FieldTag Lds_des_id where fieldName _ = "lds_des_id"

lds_des_id :: Attr Lds_des_id Int
lds_des_id = mkAttr Lds_des_id

---------------------------------------------------------------------------
-- Lds_lug_id Field
---------------------------------------------------------------------------

data Lds_lug_id = Lds_lug_id

instance FieldTag Lds_lug_id where fieldName _ = "lds_lug_id"

lds_lug_id :: Attr Lds_lug_id Int
lds_lug_id = mkAttr Lds_lug_id

---------------------------------------------------------------------------
-- Lds_updated_by Field
---------------------------------------------------------------------------

data Lds_updated_by = Lds_updated_by

instance FieldTag Lds_updated_by where
    fieldName _ = "lds_updated_by"

lds_updated_by :: Attr Lds_updated_by Int
lds_updated_by = mkAttr Lds_updated_by

---------------------------------------------------------------------------
-- Lds_updated Field
---------------------------------------------------------------------------

data Lds_updated = Lds_updated

instance FieldTag Lds_updated where fieldName _ = "lds_updated"

lds_updated :: Attr Lds_updated (Maybe CalendarTime)
lds_updated = mkAttr Lds_updated

---------------------------------------------------------------------------
-- Lds_created Field
---------------------------------------------------------------------------

data Lds_created = Lds_created

instance FieldTag Lds_created where fieldName _ = "lds_created"

lds_created :: Attr Lds_created (Maybe CalendarTime)
lds_created = mkAttr Lds_created
