{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack54 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.LGC where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type LGC  =
    (RecCons Lgc_id Expr (Maybe Int)
     (RecCons Lgc_model_persistence Expr String
      (RecCons Lgc_method Expr String
       (RecCons Lgc_row_id Expr (Maybe String)
        (RecCons Lgc_hot_id Expr (Maybe Int)
         (RecCons Lgc_old_value Expr (Maybe String)
          (RecCons Lgc_new_value Expr (Maybe String)
           (RecCons Lgc_time Expr (Maybe CalendarTime)
            (RecCons Lgc_seen Expr Bool
             (RecCons Lgc_url Expr (Maybe String)
              (RecCons Lgc_status_reg Expr String
               (RecCons Lgc_updated_by Expr Int
                (RecCons Lgc_updated Expr (Maybe CalendarTime)
                 (RecCons Lgc_created Expr (Maybe CalendarTime) RecNil))))))))))))))

type LGC _result =
    (RecCons Lgc_id ((Maybe Int))
     (RecCons Lgc_model_persistence (String)
      (RecCons Lgc_method (String)
       (RecCons Lgc_row_id ((Maybe String))
        (RecCons Lgc_hot_id ((Maybe Int))
         (RecCons Lgc_old_value ((Maybe String))
          (RecCons Lgc_new_value ((Maybe String))
           (RecCons Lgc_time ((Maybe CalendarTime))
            (RecCons Lgc_seen (Bool)
             (RecCons Lgc_url ((Maybe String))
              (RecCons Lgc_status_reg (String)
               (RecCons Lgc_updated_by (Int)
                (RecCons Lgc_updated ((Maybe CalendarTime))
                 (RecCons Lgc_created ((Maybe CalendarTime)) RecNil))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
lGC :: Table LGC
lGC = baseTable "LGC" $
      hdbMakeEntry Lgc_id #
      hdbMakeEntry Lgc_model_persistence #
      hdbMakeEntry Lgc_method #
      hdbMakeEntry Lgc_row_id #
      hdbMakeEntry Lgc_hot_id #
      hdbMakeEntry Lgc_old_value #
      hdbMakeEntry Lgc_new_value #
      hdbMakeEntry Lgc_time #
      hdbMakeEntry Lgc_seen #
      hdbMakeEntry Lgc_url #
      hdbMakeEntry Lgc_status_reg #
      hdbMakeEntry Lgc_updated_by #
      hdbMakeEntry Lgc_updated #
      hdbMakeEntry Lgc_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Lgc_id Field
---------------------------------------------------------------------------

data Lgc_id = Lgc_id

instance FieldTag Lgc_id where fieldName _ = "lgc_id"

lgc_id :: Attr Lgc_id (Maybe Int)
lgc_id = mkAttr Lgc_id

---------------------------------------------------------------------------
-- Lgc_model_persistence Field
---------------------------------------------------------------------------

data Lgc_model_persistence = Lgc_model_persistence

instance FieldTag Lgc_model_persistence where
    fieldName _ = "lgc_model_persistence"

lgc_model_persistence :: Attr Lgc_model_persistence String
lgc_model_persistence = mkAttr Lgc_model_persistence

---------------------------------------------------------------------------
-- Lgc_method Field
---------------------------------------------------------------------------

data Lgc_method = Lgc_method

instance FieldTag Lgc_method where fieldName _ = "lgc_method"

lgc_method :: Attr Lgc_method String
lgc_method = mkAttr Lgc_method

---------------------------------------------------------------------------
-- Lgc_row_id Field
---------------------------------------------------------------------------

data Lgc_row_id = Lgc_row_id

instance FieldTag Lgc_row_id where fieldName _ = "lgc_row_id"

lgc_row_id :: Attr Lgc_row_id (Maybe String)
lgc_row_id = mkAttr Lgc_row_id

---------------------------------------------------------------------------
-- Lgc_hot_id Field
---------------------------------------------------------------------------

data Lgc_hot_id = Lgc_hot_id

instance FieldTag Lgc_hot_id where fieldName _ = "lgc_hot_id"

lgc_hot_id :: Attr Lgc_hot_id (Maybe Int)
lgc_hot_id = mkAttr Lgc_hot_id

---------------------------------------------------------------------------
-- Lgc_old_value Field
---------------------------------------------------------------------------

data Lgc_old_value = Lgc_old_value

instance FieldTag Lgc_old_value where
    fieldName _ = "lgc_old_value"

lgc_old_value :: Attr Lgc_old_value (Maybe String)
lgc_old_value = mkAttr Lgc_old_value

---------------------------------------------------------------------------
-- Lgc_new_value Field
---------------------------------------------------------------------------

data Lgc_new_value = Lgc_new_value

instance FieldTag Lgc_new_value where
    fieldName _ = "lgc_new_value"

lgc_new_value :: Attr Lgc_new_value (Maybe String)
lgc_new_value = mkAttr Lgc_new_value

---------------------------------------------------------------------------
-- Lgc_time Field
---------------------------------------------------------------------------

data Lgc_time = Lgc_time

instance FieldTag Lgc_time where fieldName _ = "lgc_time"

lgc_time :: Attr Lgc_time (Maybe CalendarTime)
lgc_time = mkAttr Lgc_time

---------------------------------------------------------------------------
-- Lgc_seen Field
---------------------------------------------------------------------------

data Lgc_seen = Lgc_seen

instance FieldTag Lgc_seen where fieldName _ = "lgc_seen"

lgc_seen :: Attr Lgc_seen Bool
lgc_seen = mkAttr Lgc_seen

---------------------------------------------------------------------------
-- Lgc_url Field
---------------------------------------------------------------------------

data Lgc_url = Lgc_url

instance FieldTag Lgc_url where fieldName _ = "lgc_url"

lgc_url :: Attr Lgc_url (Maybe String)
lgc_url = mkAttr Lgc_url

---------------------------------------------------------------------------
-- Lgc_status_reg Field
---------------------------------------------------------------------------

data Lgc_status_reg = Lgc_status_reg

instance FieldTag Lgc_status_reg where
    fieldName _ = "lgc_status_reg"

lgc_status_reg :: Attr Lgc_status_reg String
lgc_status_reg = mkAttr Lgc_status_reg

---------------------------------------------------------------------------
-- Lgc_updated_by Field
---------------------------------------------------------------------------

data Lgc_updated_by = Lgc_updated_by

instance FieldTag Lgc_updated_by where
    fieldName _ = "lgc_updated_by"

lgc_updated_by :: Attr Lgc_updated_by Int
lgc_updated_by = mkAttr Lgc_updated_by

---------------------------------------------------------------------------
-- Lgc_updated Field
---------------------------------------------------------------------------

data Lgc_updated = Lgc_updated

instance FieldTag Lgc_updated where fieldName _ = "lgc_updated"

lgc_updated :: Attr Lgc_updated (Maybe CalendarTime)
lgc_updated = mkAttr Lgc_updated

---------------------------------------------------------------------------
-- Lgc_created Field
---------------------------------------------------------------------------

data Lgc_created = Lgc_created

instance FieldTag Lgc_created where fieldName _ = "lgc_created"

lgc_created :: Attr Lgc_created (Maybe CalendarTime)
lgc_created = mkAttr Lgc_created
