{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.LUG where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type LUG  =
    (RecCons Lug_id Expr (Maybe Int)
     (RecCons Lug_edo_id Expr Int
      (RecCons Lug_name Expr String
       (RecCons Lug_approval Expr String
        (RecCons Lug_status_reg Expr String
         (RecCons Lug_updated_by Expr Int
          (RecCons Lug_updated Expr (Maybe CalendarTime)
           (RecCons Lug_created Expr (Maybe CalendarTime) RecNil))))))))

type LUG _result =
    (RecCons Lug_id ((Maybe Int))
     (RecCons Lug_edo_id (Int)
      (RecCons Lug_name (String)
       (RecCons Lug_approval (String)
        (RecCons Lug_status_reg (String)
         (RecCons Lug_updated_by (Int)
          (RecCons Lug_updated ((Maybe CalendarTime))
           (RecCons Lug_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
lUG :: Table LUG
lUG = baseTable "LUG" $
      hdbMakeEntry Lug_id #
      hdbMakeEntry Lug_edo_id #
      hdbMakeEntry Lug_name #
      hdbMakeEntry Lug_approval #
      hdbMakeEntry Lug_status_reg #
      hdbMakeEntry Lug_updated_by #
      hdbMakeEntry Lug_updated #
      hdbMakeEntry Lug_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Lug_id Field
---------------------------------------------------------------------------

data Lug_id = Lug_id

instance FieldTag Lug_id where fieldName _ = "lug_id"

lug_id :: Attr Lug_id (Maybe Int)
lug_id = mkAttr Lug_id

---------------------------------------------------------------------------
-- Lug_edo_id Field
---------------------------------------------------------------------------

data Lug_edo_id = Lug_edo_id

instance FieldTag Lug_edo_id where fieldName _ = "lug_edo_id"

lug_edo_id :: Attr Lug_edo_id Int
lug_edo_id = mkAttr Lug_edo_id

---------------------------------------------------------------------------
-- Lug_name Field
---------------------------------------------------------------------------

data Lug_name = Lug_name

instance FieldTag Lug_name where fieldName _ = "lug_name"

lug_name :: Attr Lug_name String
lug_name = mkAttr Lug_name

---------------------------------------------------------------------------
-- Lug_approval Field
---------------------------------------------------------------------------

data Lug_approval = Lug_approval

instance FieldTag Lug_approval where fieldName _ = "lug_approval"

lug_approval :: Attr Lug_approval String
lug_approval = mkAttr Lug_approval

---------------------------------------------------------------------------
-- Lug_status_reg Field
---------------------------------------------------------------------------

data Lug_status_reg = Lug_status_reg

instance FieldTag Lug_status_reg where
    fieldName _ = "lug_status_reg"

lug_status_reg :: Attr Lug_status_reg String
lug_status_reg = mkAttr Lug_status_reg

---------------------------------------------------------------------------
-- Lug_updated_by Field
---------------------------------------------------------------------------

data Lug_updated_by = Lug_updated_by

instance FieldTag Lug_updated_by where
    fieldName _ = "lug_updated_by"

lug_updated_by :: Attr Lug_updated_by Int
lug_updated_by = mkAttr Lug_updated_by

---------------------------------------------------------------------------
-- Lug_updated Field
---------------------------------------------------------------------------

data Lug_updated = Lug_updated

instance FieldTag Lug_updated where fieldName _ = "lug_updated"

lug_updated :: Attr Lug_updated (Maybe CalendarTime)
lug_updated = mkAttr Lug_updated

---------------------------------------------------------------------------
-- Lug_created Field
---------------------------------------------------------------------------

data Lug_created = Lug_created

instance FieldTag Lug_created where fieldName _ = "lug_created"

lug_created :: Attr Lug_created (Maybe CalendarTime)
lug_created = mkAttr Lug_created
