{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.MON where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type MON  =
    (RecCons Mon_id Expr (Maybe Int)
     (RecCons Mon_name Expr String
      (RecCons Mon_sym Expr String
       (RecCons Mon_iso Expr String
        (RecCons Mon_status_reg Expr String
         (RecCons Mon_updated_by Expr Int
          (RecCons Mon_updated Expr (Maybe CalendarTime)
           (RecCons Mon_created Expr (Maybe CalendarTime) RecNil))))))))

type MON _result =
    (RecCons Mon_id ((Maybe Int))
     (RecCons Mon_name (String)
      (RecCons Mon_sym (String)
       (RecCons Mon_iso (String)
        (RecCons Mon_status_reg (String)
         (RecCons Mon_updated_by (Int)
          (RecCons Mon_updated ((Maybe CalendarTime))
           (RecCons Mon_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
mON :: Table MON
mON = baseTable "MON" $
      hdbMakeEntry Mon_id #
      hdbMakeEntry Mon_name #
      hdbMakeEntry Mon_sym #
      hdbMakeEntry Mon_iso #
      hdbMakeEntry Mon_status_reg #
      hdbMakeEntry Mon_updated_by #
      hdbMakeEntry Mon_updated #
      hdbMakeEntry Mon_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Mon_id Field
---------------------------------------------------------------------------

data Mon_id = Mon_id

instance FieldTag Mon_id where fieldName _ = "mon_id"

mon_id :: Attr Mon_id (Maybe Int)
mon_id = mkAttr Mon_id

---------------------------------------------------------------------------
-- Mon_name Field
---------------------------------------------------------------------------

data Mon_name = Mon_name

instance FieldTag Mon_name where fieldName _ = "mon_name"

mon_name :: Attr Mon_name String
mon_name = mkAttr Mon_name

---------------------------------------------------------------------------
-- Mon_sym Field
---------------------------------------------------------------------------

data Mon_sym = Mon_sym

instance FieldTag Mon_sym where fieldName _ = "mon_sym"

mon_sym :: Attr Mon_sym String
mon_sym = mkAttr Mon_sym

---------------------------------------------------------------------------
-- Mon_iso Field
---------------------------------------------------------------------------

data Mon_iso = Mon_iso

instance FieldTag Mon_iso where fieldName _ = "mon_iso"

mon_iso :: Attr Mon_iso String
mon_iso = mkAttr Mon_iso

---------------------------------------------------------------------------
-- Mon_status_reg Field
---------------------------------------------------------------------------

data Mon_status_reg = Mon_status_reg

instance FieldTag Mon_status_reg where
    fieldName _ = "mon_status_reg"

mon_status_reg :: Attr Mon_status_reg String
mon_status_reg = mkAttr Mon_status_reg

---------------------------------------------------------------------------
-- Mon_updated_by Field
---------------------------------------------------------------------------

data Mon_updated_by = Mon_updated_by

instance FieldTag Mon_updated_by where
    fieldName _ = "mon_updated_by"

mon_updated_by :: Attr Mon_updated_by Int
mon_updated_by = mkAttr Mon_updated_by

---------------------------------------------------------------------------
-- Mon_updated Field
---------------------------------------------------------------------------

data Mon_updated = Mon_updated

instance FieldTag Mon_updated where fieldName _ = "mon_updated"

mon_updated :: Attr Mon_updated (Maybe CalendarTime)
mon_updated = mkAttr Mon_updated

---------------------------------------------------------------------------
-- Mon_created Field
---------------------------------------------------------------------------

data Mon_created = Mon_created

instance FieldTag Mon_created where fieldName _ = "mon_created"

mon_created :: Attr Mon_created (Maybe CalendarTime)
mon_created = mkAttr Mon_created
