{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack51 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.MSJ where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type MSJ  =
    (RecCons Msj_id Expr (Maybe Int)
     (RecCons Msj_sender Expr Int
      (RecCons Msj_subject Expr String
       (RecCons Msj_text Expr String
        (RecCons Msj_seen Expr Bool
         (RecCons Msj_hot_id Expr Int
          (RecCons Msj_usr_id Expr Int
           (RecCons Msj_updated_by Expr Int
            (RecCons Msj_updated Expr (Maybe CalendarTime)
             (RecCons Msj_created Expr (Maybe CalendarTime)
              (RecCons Msj_status_reg Expr String RecNil)))))))))))

type MSJ _result =
    (RecCons Msj_id ((Maybe Int))
     (RecCons Msj_sender (Int)
      (RecCons Msj_subject (String)
       (RecCons Msj_text (String)
        (RecCons Msj_seen (Bool)
         (RecCons Msj_hot_id (Int)
          (RecCons Msj_usr_id (Int)
           (RecCons Msj_updated_by (Int)
            (RecCons Msj_updated ((Maybe CalendarTime))
             (RecCons Msj_created ((Maybe CalendarTime))
              (RecCons Msj_status_reg (String) RecNil)))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
mSJ :: Table MSJ
mSJ = baseTable "MSJ" $
      hdbMakeEntry Msj_id #
      hdbMakeEntry Msj_sender #
      hdbMakeEntry Msj_subject #
      hdbMakeEntry Msj_text #
      hdbMakeEntry Msj_seen #
      hdbMakeEntry Msj_hot_id #
      hdbMakeEntry Msj_usr_id #
      hdbMakeEntry Msj_updated_by #
      hdbMakeEntry Msj_updated #
      hdbMakeEntry Msj_created #
      hdbMakeEntry Msj_status_reg

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Msj_id Field
---------------------------------------------------------------------------

data Msj_id = Msj_id

instance FieldTag Msj_id where fieldName _ = "msj_id"

msj_id :: Attr Msj_id (Maybe Int)
msj_id = mkAttr Msj_id

---------------------------------------------------------------------------
-- Msj_sender Field
---------------------------------------------------------------------------

data Msj_sender = Msj_sender

instance FieldTag Msj_sender where fieldName _ = "msj_sender"

msj_sender :: Attr Msj_sender Int
msj_sender = mkAttr Msj_sender

---------------------------------------------------------------------------
-- Msj_subject Field
---------------------------------------------------------------------------

data Msj_subject = Msj_subject

instance FieldTag Msj_subject where fieldName _ = "msj_subject"

msj_subject :: Attr Msj_subject String
msj_subject = mkAttr Msj_subject

---------------------------------------------------------------------------
-- Msj_text Field
---------------------------------------------------------------------------

data Msj_text = Msj_text

instance FieldTag Msj_text where fieldName _ = "msj_text"

msj_text :: Attr Msj_text String
msj_text = mkAttr Msj_text

---------------------------------------------------------------------------
-- Msj_seen Field
---------------------------------------------------------------------------

data Msj_seen = Msj_seen

instance FieldTag Msj_seen where fieldName _ = "msj_seen"

msj_seen :: Attr Msj_seen Bool
msj_seen = mkAttr Msj_seen

---------------------------------------------------------------------------
-- Msj_hot_id Field
---------------------------------------------------------------------------

data Msj_hot_id = Msj_hot_id

instance FieldTag Msj_hot_id where fieldName _ = "msj_hot_id"

msj_hot_id :: Attr Msj_hot_id Int
msj_hot_id = mkAttr Msj_hot_id

---------------------------------------------------------------------------
-- Msj_usr_id Field
---------------------------------------------------------------------------

data Msj_usr_id = Msj_usr_id

instance FieldTag Msj_usr_id where fieldName _ = "msj_usr_id"

msj_usr_id :: Attr Msj_usr_id Int
msj_usr_id = mkAttr Msj_usr_id

---------------------------------------------------------------------------
-- Msj_updated_by Field
---------------------------------------------------------------------------

data Msj_updated_by = Msj_updated_by

instance FieldTag Msj_updated_by where
    fieldName _ = "msj_updated_by"

msj_updated_by :: Attr Msj_updated_by Int
msj_updated_by = mkAttr Msj_updated_by

---------------------------------------------------------------------------
-- Msj_updated Field
---------------------------------------------------------------------------

data Msj_updated = Msj_updated

instance FieldTag Msj_updated where fieldName _ = "msj_updated"

msj_updated :: Attr Msj_updated (Maybe CalendarTime)
msj_updated = mkAttr Msj_updated

---------------------------------------------------------------------------
-- Msj_created Field
---------------------------------------------------------------------------

data Msj_created = Msj_created

instance FieldTag Msj_created where fieldName _ = "msj_created"

msj_created :: Attr Msj_created (Maybe CalendarTime)
msj_created = mkAttr Msj_created

---------------------------------------------------------------------------
-- Msj_status_reg Field
---------------------------------------------------------------------------

data Msj_status_reg = Msj_status_reg

instance FieldTag Msj_status_reg where
    fieldName _ = "msj_status_reg"

msj_status_reg :: Attr Msj_status_reg String
msj_status_reg = mkAttr Msj_status_reg
