{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack62 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PAG where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PAG  =
    (RecCons Pag_id Expr (Maybe Int)
     (RecCons Pag_date Expr CalendarTime
      (RecCons Pag_sender_type Expr String
       (RecCons Pag_reciever_type Expr String
        (RecCons Pag_sender Expr (Maybe Int)
         (RecCons Pag_reciever Expr (Maybe Int)
          (RecCons Pag_cba_sender Expr (Maybe Int)
           (RecCons Pag_cba_reciever Expr (Maybe Int)
            (RecCons Pag_amount Expr Integer
             (RecCons Pag_mon_id Expr Int
              (RecCons Pag_cost Expr Integer
               (RecCons Pag_type Expr String
                (RecCons Pag_ppi Expr (Maybe String)
                 (RecCons Pag_res_id Expr (Maybe Int)
                  (RecCons Pag_voucher Expr (Maybe String)
                   (RecCons Pag_status Expr String
                    (RecCons Pag_obs Expr (Maybe String)
                     (RecCons Pag_attachment Expr (Maybe String)
                      (RecCons Pag_status_reg Expr String
                       (RecCons Pag_updated_by Expr Int
                        (RecCons Pag_updated Expr (Maybe CalendarTime)
                         (RecCons Pag_created Expr (Maybe CalendarTime) RecNil))))))))))))))))))))))

type PAG _result =
    (RecCons Pag_id ((Maybe Int))
     (RecCons Pag_date (CalendarTime)
      (RecCons Pag_sender_type (String)
       (RecCons Pag_reciever_type (String)
        (RecCons Pag_sender ((Maybe Int))
         (RecCons Pag_reciever ((Maybe Int))
          (RecCons Pag_cba_sender ((Maybe Int))
           (RecCons Pag_cba_reciever ((Maybe Int))
            (RecCons Pag_amount (Integer)
             (RecCons Pag_mon_id (Int)
              (RecCons Pag_cost (Integer)
               (RecCons Pag_type (String)
                (RecCons Pag_ppi ((Maybe String))
                 (RecCons Pag_res_id ((Maybe Int))
                  (RecCons Pag_voucher ((Maybe String))
                   (RecCons Pag_status (String)
                    (RecCons Pag_obs ((Maybe String))
                     (RecCons Pag_attachment ((Maybe String))
                      (RecCons Pag_status_reg (String)
                       (RecCons Pag_updated_by (Int)
                        (RecCons Pag_updated ((Maybe CalendarTime))
                         (RecCons Pag_created ((Maybe CalendarTime)) RecNil))))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pAG :: Table PAG
pAG = baseTable "PAG" $
      hdbMakeEntry Pag_id #
      hdbMakeEntry Pag_date #
      hdbMakeEntry Pag_sender_type #
      hdbMakeEntry Pag_reciever_type #
      hdbMakeEntry Pag_sender #
      hdbMakeEntry Pag_reciever #
      hdbMakeEntry Pag_cba_sender #
      hdbMakeEntry Pag_cba_reciever #
      hdbMakeEntry Pag_amount #
      hdbMakeEntry Pag_mon_id #
      hdbMakeEntry Pag_cost #
      hdbMakeEntry Pag_type #
      hdbMakeEntry Pag_ppi #
      hdbMakeEntry Pag_res_id #
      hdbMakeEntry Pag_voucher #
      hdbMakeEntry Pag_status #
      hdbMakeEntry Pag_obs #
      hdbMakeEntry Pag_attachment #
      hdbMakeEntry Pag_status_reg #
      hdbMakeEntry Pag_updated_by #
      hdbMakeEntry Pag_updated #
      hdbMakeEntry Pag_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Pag_id Field
---------------------------------------------------------------------------

data Pag_id = Pag_id

instance FieldTag Pag_id where fieldName _ = "pag_id"

pag_id :: Attr Pag_id (Maybe Int)
pag_id = mkAttr Pag_id

---------------------------------------------------------------------------
-- Pag_date Field
---------------------------------------------------------------------------

data Pag_date = Pag_date

instance FieldTag Pag_date where fieldName _ = "pag_date"

pag_date :: Attr Pag_date CalendarTime
pag_date = mkAttr Pag_date

---------------------------------------------------------------------------
-- Pag_sender_type Field
---------------------------------------------------------------------------

data Pag_sender_type = Pag_sender_type

instance FieldTag Pag_sender_type where
    fieldName _ = "pag_sender_type"

pag_sender_type :: Attr Pag_sender_type String
pag_sender_type = mkAttr Pag_sender_type

---------------------------------------------------------------------------
-- Pag_reciever_type Field
---------------------------------------------------------------------------

data Pag_reciever_type = Pag_reciever_type

instance FieldTag Pag_reciever_type where
    fieldName _ = "pag_reciever_type"

pag_reciever_type :: Attr Pag_reciever_type String
pag_reciever_type = mkAttr Pag_reciever_type

---------------------------------------------------------------------------
-- Pag_sender Field
---------------------------------------------------------------------------

data Pag_sender = Pag_sender

instance FieldTag Pag_sender where fieldName _ = "pag_sender"

pag_sender :: Attr Pag_sender (Maybe Int)
pag_sender = mkAttr Pag_sender

---------------------------------------------------------------------------
-- Pag_reciever Field
---------------------------------------------------------------------------

data Pag_reciever = Pag_reciever

instance FieldTag Pag_reciever where fieldName _ = "pag_reciever"

pag_reciever :: Attr Pag_reciever (Maybe Int)
pag_reciever = mkAttr Pag_reciever

---------------------------------------------------------------------------
-- Pag_cba_sender Field
---------------------------------------------------------------------------

data Pag_cba_sender = Pag_cba_sender

instance FieldTag Pag_cba_sender where
    fieldName _ = "pag_cba_sender"

pag_cba_sender :: Attr Pag_cba_sender (Maybe Int)
pag_cba_sender = mkAttr Pag_cba_sender

---------------------------------------------------------------------------
-- Pag_cba_reciever Field
---------------------------------------------------------------------------

data Pag_cba_reciever = Pag_cba_reciever

instance FieldTag Pag_cba_reciever where
    fieldName _ = "pag_cba_reciever"

pag_cba_reciever :: Attr Pag_cba_reciever (Maybe Int)
pag_cba_reciever = mkAttr Pag_cba_reciever

---------------------------------------------------------------------------
-- Pag_amount Field
---------------------------------------------------------------------------

data Pag_amount = Pag_amount

instance FieldTag Pag_amount where fieldName _ = "pag_amount"

pag_amount :: Attr Pag_amount Integer
pag_amount = mkAttr Pag_amount

---------------------------------------------------------------------------
-- Pag_mon_id Field
---------------------------------------------------------------------------

data Pag_mon_id = Pag_mon_id

instance FieldTag Pag_mon_id where fieldName _ = "pag_mon_id"

pag_mon_id :: Attr Pag_mon_id Int
pag_mon_id = mkAttr Pag_mon_id

---------------------------------------------------------------------------
-- Pag_cost Field
---------------------------------------------------------------------------

data Pag_cost = Pag_cost

instance FieldTag Pag_cost where fieldName _ = "pag_cost"

pag_cost :: Attr Pag_cost Integer
pag_cost = mkAttr Pag_cost

---------------------------------------------------------------------------
-- Pag_type Field
---------------------------------------------------------------------------

data Pag_type = Pag_type

instance FieldTag Pag_type where fieldName _ = "pag_type"

pag_type :: Attr Pag_type String
pag_type = mkAttr Pag_type

---------------------------------------------------------------------------
-- Pag_ppi Field
---------------------------------------------------------------------------

data Pag_ppi = Pag_ppi

instance FieldTag Pag_ppi where fieldName _ = "pag_ppi"

pag_ppi :: Attr Pag_ppi (Maybe String)
pag_ppi = mkAttr Pag_ppi

---------------------------------------------------------------------------
-- Pag_res_id Field
---------------------------------------------------------------------------

data Pag_res_id = Pag_res_id

instance FieldTag Pag_res_id where fieldName _ = "pag_res_id"

pag_res_id :: Attr Pag_res_id (Maybe Int)
pag_res_id = mkAttr Pag_res_id

---------------------------------------------------------------------------
-- Pag_voucher Field
---------------------------------------------------------------------------

data Pag_voucher = Pag_voucher

instance FieldTag Pag_voucher where fieldName _ = "pag_voucher"

pag_voucher :: Attr Pag_voucher (Maybe String)
pag_voucher = mkAttr Pag_voucher

---------------------------------------------------------------------------
-- Pag_status Field
---------------------------------------------------------------------------

data Pag_status = Pag_status

instance FieldTag Pag_status where fieldName _ = "pag_status"

pag_status :: Attr Pag_status String
pag_status = mkAttr Pag_status

---------------------------------------------------------------------------
-- Pag_obs Field
---------------------------------------------------------------------------

data Pag_obs = Pag_obs

instance FieldTag Pag_obs where fieldName _ = "pag_obs"

pag_obs :: Attr Pag_obs (Maybe String)
pag_obs = mkAttr Pag_obs

---------------------------------------------------------------------------
-- Pag_attachment Field
---------------------------------------------------------------------------

data Pag_attachment = Pag_attachment

instance FieldTag Pag_attachment where
    fieldName _ = "pag_attachment"

pag_attachment :: Attr Pag_attachment (Maybe String)
pag_attachment = mkAttr Pag_attachment

---------------------------------------------------------------------------
-- Pag_status_reg Field
---------------------------------------------------------------------------

data Pag_status_reg = Pag_status_reg

instance FieldTag Pag_status_reg where
    fieldName _ = "pag_status_reg"

pag_status_reg :: Attr Pag_status_reg String
pag_status_reg = mkAttr Pag_status_reg

---------------------------------------------------------------------------
-- Pag_updated_by Field
---------------------------------------------------------------------------

data Pag_updated_by = Pag_updated_by

instance FieldTag Pag_updated_by where
    fieldName _ = "pag_updated_by"

pag_updated_by :: Attr Pag_updated_by Int
pag_updated_by = mkAttr Pag_updated_by

---------------------------------------------------------------------------
-- Pag_updated Field
---------------------------------------------------------------------------

data Pag_updated = Pag_updated

instance FieldTag Pag_updated where fieldName _ = "pag_updated"

pag_updated :: Attr Pag_updated (Maybe CalendarTime)
pag_updated = mkAttr Pag_updated

---------------------------------------------------------------------------
-- Pag_created Field
---------------------------------------------------------------------------

data Pag_created = Pag_created

instance FieldTag Pag_created where fieldName _ = "pag_created"

pag_created :: Attr Pag_created (Maybe CalendarTime)
pag_created = mkAttr Pag_created
