{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack49 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PAI where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PAI  =
    (RecCons Pai_id Expr (Maybe Int)
     (RecCons Pai_name Expr String
      (RecCons Pai_long_name Expr String
       (RecCons Pai_code Expr (Maybe String)
        (RecCons Pai_calling_code Expr (Maybe String)
         (RecCons Pai_status_reg Expr String
          (RecCons Pai_updated_by Expr Int
           (RecCons Pai_updated Expr (Maybe CalendarTime)
            (RecCons Pai_created Expr (Maybe CalendarTime) RecNil)))))))))

type PAI _result =
    (RecCons Pai_id ((Maybe Int))
     (RecCons Pai_name (String)
      (RecCons Pai_long_name (String)
       (RecCons Pai_code ((Maybe String))
        (RecCons Pai_calling_code ((Maybe String))
         (RecCons Pai_status_reg (String)
          (RecCons Pai_updated_by (Int)
           (RecCons Pai_updated ((Maybe CalendarTime))
            (RecCons Pai_created ((Maybe CalendarTime)) RecNil)))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pAI :: Table PAI
pAI = baseTable "PAI" $
      hdbMakeEntry Pai_id #
      hdbMakeEntry Pai_name #
      hdbMakeEntry Pai_long_name #
      hdbMakeEntry Pai_code #
      hdbMakeEntry Pai_calling_code #
      hdbMakeEntry Pai_status_reg #
      hdbMakeEntry Pai_updated_by #
      hdbMakeEntry Pai_updated #
      hdbMakeEntry Pai_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Pai_id Field
---------------------------------------------------------------------------

data Pai_id = Pai_id

instance FieldTag Pai_id where fieldName _ = "pai_id"

pai_id :: Attr Pai_id (Maybe Int)
pai_id = mkAttr Pai_id

---------------------------------------------------------------------------
-- Pai_name Field
---------------------------------------------------------------------------

data Pai_name = Pai_name

instance FieldTag Pai_name where fieldName _ = "pai_name"

pai_name :: Attr Pai_name String
pai_name = mkAttr Pai_name

---------------------------------------------------------------------------
-- Pai_long_name Field
---------------------------------------------------------------------------

data Pai_long_name = Pai_long_name

instance FieldTag Pai_long_name where
    fieldName _ = "pai_long_name"

pai_long_name :: Attr Pai_long_name String
pai_long_name = mkAttr Pai_long_name

---------------------------------------------------------------------------
-- Pai_code Field
---------------------------------------------------------------------------

data Pai_code = Pai_code

instance FieldTag Pai_code where fieldName _ = "pai_code"

pai_code :: Attr Pai_code (Maybe String)
pai_code = mkAttr Pai_code

---------------------------------------------------------------------------
-- Pai_calling_code Field
---------------------------------------------------------------------------

data Pai_calling_code = Pai_calling_code

instance FieldTag Pai_calling_code where
    fieldName _ = "pai_calling_code"

pai_calling_code :: Attr Pai_calling_code (Maybe String)
pai_calling_code = mkAttr Pai_calling_code

---------------------------------------------------------------------------
-- Pai_status_reg Field
---------------------------------------------------------------------------

data Pai_status_reg = Pai_status_reg

instance FieldTag Pai_status_reg where
    fieldName _ = "pai_status_reg"

pai_status_reg :: Attr Pai_status_reg String
pai_status_reg = mkAttr Pai_status_reg

---------------------------------------------------------------------------
-- Pai_updated_by Field
---------------------------------------------------------------------------

data Pai_updated_by = Pai_updated_by

instance FieldTag Pai_updated_by where
    fieldName _ = "pai_updated_by"

pai_updated_by :: Attr Pai_updated_by Int
pai_updated_by = mkAttr Pai_updated_by

---------------------------------------------------------------------------
-- Pai_updated Field
---------------------------------------------------------------------------

data Pai_updated = Pai_updated

instance FieldTag Pai_updated where fieldName _ = "pai_updated"

pai_updated :: Attr Pai_updated (Maybe CalendarTime)
pai_updated = mkAttr Pai_updated

---------------------------------------------------------------------------
-- Pai_created Field
---------------------------------------------------------------------------

data Pai_created = Pai_created

instance FieldTag Pai_created where fieldName _ = "pai_created"

pai_created :: Attr Pai_created (Maybe CalendarTime)
pai_created = mkAttr Pai_created
