{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PER where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PER  =
    (RecCons Per_id Expr (Maybe Int)
     (RecCons Per_name Expr String
      (RecCons Per_permissions Expr String
       (RecCons Per_hot_id Expr (Maybe Int)
        (RecCons Per_status_reg Expr String
         (RecCons Per_updated_by Expr Int
          (RecCons Per_updated Expr (Maybe CalendarTime)
           (RecCons Per_created Expr (Maybe CalendarTime) RecNil))))))))

type PER _result =
    (RecCons Per_id ((Maybe Int))
     (RecCons Per_name (String)
      (RecCons Per_permissions (String)
       (RecCons Per_hot_id ((Maybe Int))
        (RecCons Per_status_reg (String)
         (RecCons Per_updated_by (Int)
          (RecCons Per_updated ((Maybe CalendarTime))
           (RecCons Per_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pER :: Table PER
pER = baseTable "PER" $
      hdbMakeEntry Per_id #
      hdbMakeEntry Per_name #
      hdbMakeEntry Per_permissions #
      hdbMakeEntry Per_hot_id #
      hdbMakeEntry Per_status_reg #
      hdbMakeEntry Per_updated_by #
      hdbMakeEntry Per_updated #
      hdbMakeEntry Per_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Per_id Field
---------------------------------------------------------------------------

data Per_id = Per_id

instance FieldTag Per_id where fieldName _ = "per_id"

per_id :: Attr Per_id (Maybe Int)
per_id = mkAttr Per_id

---------------------------------------------------------------------------
-- Per_name Field
---------------------------------------------------------------------------

data Per_name = Per_name

instance FieldTag Per_name where fieldName _ = "per_name"

per_name :: Attr Per_name String
per_name = mkAttr Per_name

---------------------------------------------------------------------------
-- Per_permissions Field
---------------------------------------------------------------------------

data Per_permissions = Per_permissions

instance FieldTag Per_permissions where
    fieldName _ = "per_permissions"

per_permissions :: Attr Per_permissions String
per_permissions = mkAttr Per_permissions

---------------------------------------------------------------------------
-- Per_hot_id Field
---------------------------------------------------------------------------

data Per_hot_id = Per_hot_id

instance FieldTag Per_hot_id where fieldName _ = "per_hot_id"

per_hot_id :: Attr Per_hot_id (Maybe Int)
per_hot_id = mkAttr Per_hot_id

---------------------------------------------------------------------------
-- Per_status_reg Field
---------------------------------------------------------------------------

data Per_status_reg = Per_status_reg

instance FieldTag Per_status_reg where
    fieldName _ = "per_status_reg"

per_status_reg :: Attr Per_status_reg String
per_status_reg = mkAttr Per_status_reg

---------------------------------------------------------------------------
-- Per_updated_by Field
---------------------------------------------------------------------------

data Per_updated_by = Per_updated_by

instance FieldTag Per_updated_by where
    fieldName _ = "per_updated_by"

per_updated_by :: Attr Per_updated_by Int
per_updated_by = mkAttr Per_updated_by

---------------------------------------------------------------------------
-- Per_updated Field
---------------------------------------------------------------------------

data Per_updated = Per_updated

instance FieldTag Per_updated where fieldName _ = "per_updated"

per_updated :: Attr Per_updated (Maybe CalendarTime)
per_updated = mkAttr Per_updated

---------------------------------------------------------------------------
-- Per_created Field
---------------------------------------------------------------------------

data Per_created = Per_created

instance FieldTag Per_created where fieldName _ = "per_created"

per_created :: Attr Per_created (Maybe CalendarTime)
per_created = mkAttr Per_created
