{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack51 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PLA where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PLA  =
    (RecCons Pla_id Expr (Maybe Int)
     (RecCons Pla_name Expr String
      (RecCons Pla_hot_id Expr Int
       (RecCons Pla_type Expr String
        (RecCons Pla_desc Expr String
         (RecCons Pla_child Expr Int
          (RecCons Pla_senior Expr Int
           (RecCons Pla_status_reg Expr String
            (RecCons Pla_updated_by Expr Int
             (RecCons Pla_updated Expr (Maybe CalendarTime)
              (RecCons Pla_created Expr (Maybe CalendarTime) RecNil)))))))))))

type PLA _result =
    (RecCons Pla_id ((Maybe Int))
     (RecCons Pla_name (String)
      (RecCons Pla_hot_id (Int)
       (RecCons Pla_type (String)
        (RecCons Pla_desc (String)
         (RecCons Pla_child (Int)
          (RecCons Pla_senior (Int)
           (RecCons Pla_status_reg (String)
            (RecCons Pla_updated_by (Int)
             (RecCons Pla_updated ((Maybe CalendarTime))
              (RecCons Pla_created ((Maybe CalendarTime)) RecNil)))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pLA :: Table PLA
pLA = baseTable "PLA" $
      hdbMakeEntry Pla_id #
      hdbMakeEntry Pla_name #
      hdbMakeEntry Pla_hot_id #
      hdbMakeEntry Pla_type #
      hdbMakeEntry Pla_desc #
      hdbMakeEntry Pla_child #
      hdbMakeEntry Pla_senior #
      hdbMakeEntry Pla_status_reg #
      hdbMakeEntry Pla_updated_by #
      hdbMakeEntry Pla_updated #
      hdbMakeEntry Pla_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Pla_id Field
---------------------------------------------------------------------------

data Pla_id = Pla_id

instance FieldTag Pla_id where fieldName _ = "pla_id"

pla_id :: Attr Pla_id (Maybe Int)
pla_id = mkAttr Pla_id

---------------------------------------------------------------------------
-- Pla_name Field
---------------------------------------------------------------------------

data Pla_name = Pla_name

instance FieldTag Pla_name where fieldName _ = "pla_name"

pla_name :: Attr Pla_name String
pla_name = mkAttr Pla_name

---------------------------------------------------------------------------
-- Pla_hot_id Field
---------------------------------------------------------------------------

data Pla_hot_id = Pla_hot_id

instance FieldTag Pla_hot_id where fieldName _ = "pla_hot_id"

pla_hot_id :: Attr Pla_hot_id Int
pla_hot_id = mkAttr Pla_hot_id

---------------------------------------------------------------------------
-- Pla_type Field
---------------------------------------------------------------------------

data Pla_type = Pla_type

instance FieldTag Pla_type where fieldName _ = "pla_type"

pla_type :: Attr Pla_type String
pla_type = mkAttr Pla_type

---------------------------------------------------------------------------
-- Pla_desc Field
---------------------------------------------------------------------------

data Pla_desc = Pla_desc

instance FieldTag Pla_desc where fieldName _ = "pla_desc"

pla_desc :: Attr Pla_desc String
pla_desc = mkAttr Pla_desc

---------------------------------------------------------------------------
-- Pla_child Field
---------------------------------------------------------------------------

data Pla_child = Pla_child

instance FieldTag Pla_child where fieldName _ = "pla_child"

pla_child :: Attr Pla_child Int
pla_child = mkAttr Pla_child

---------------------------------------------------------------------------
-- Pla_senior Field
---------------------------------------------------------------------------

data Pla_senior = Pla_senior

instance FieldTag Pla_senior where fieldName _ = "pla_senior"

pla_senior :: Attr Pla_senior Int
pla_senior = mkAttr Pla_senior

---------------------------------------------------------------------------
-- Pla_status_reg Field
---------------------------------------------------------------------------

data Pla_status_reg = Pla_status_reg

instance FieldTag Pla_status_reg where
    fieldName _ = "pla_status_reg"

pla_status_reg :: Attr Pla_status_reg String
pla_status_reg = mkAttr Pla_status_reg

---------------------------------------------------------------------------
-- Pla_updated_by Field
---------------------------------------------------------------------------

data Pla_updated_by = Pla_updated_by

instance FieldTag Pla_updated_by where
    fieldName _ = "pla_updated_by"

pla_updated_by :: Attr Pla_updated_by Int
pla_updated_by = mkAttr Pla_updated_by

---------------------------------------------------------------------------
-- Pla_updated Field
---------------------------------------------------------------------------

data Pla_updated = Pla_updated

instance FieldTag Pla_updated where fieldName _ = "pla_updated"

pla_updated :: Attr Pla_updated (Maybe CalendarTime)
pla_updated = mkAttr Pla_updated

---------------------------------------------------------------------------
-- Pla_created Field
---------------------------------------------------------------------------

data Pla_created = Pla_created

instance FieldTag Pla_created where fieldName _ = "pla_created"

pla_created :: Attr Pla_created (Maybe CalendarTime)
pla_created = mkAttr Pla_created
