{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack50 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PLC where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PLC  =
    (RecCons Plc_id Expr (Maybe Int)
     (RecCons Plc_name Expr String
      (RecCons Plc_mon_id Expr Int
       (RecCons Plc_amount Expr Integer
        (RecCons Plc_beg_date Expr (Maybe CalendarTime)
         (RecCons Plc_exp_date Expr (Maybe CalendarTime)
          (RecCons Plc_status_reg Expr String
           (RecCons Plc_updated_by Expr Int
            (RecCons Plc_updated Expr (Maybe CalendarTime)
             (RecCons Plc_created Expr (Maybe CalendarTime) RecNil))))))))))

type PLC _result =
    (RecCons Plc_id ((Maybe Int))
     (RecCons Plc_name (String)
      (RecCons Plc_mon_id (Int)
       (RecCons Plc_amount (Integer)
        (RecCons Plc_beg_date ((Maybe CalendarTime))
         (RecCons Plc_exp_date ((Maybe CalendarTime))
          (RecCons Plc_status_reg (String)
           (RecCons Plc_updated_by (Int)
            (RecCons Plc_updated ((Maybe CalendarTime))
             (RecCons Plc_created ((Maybe CalendarTime)) RecNil))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pLC :: Table PLC
pLC = baseTable "PLC" $
      hdbMakeEntry Plc_id #
      hdbMakeEntry Plc_name #
      hdbMakeEntry Plc_mon_id #
      hdbMakeEntry Plc_amount #
      hdbMakeEntry Plc_beg_date #
      hdbMakeEntry Plc_exp_date #
      hdbMakeEntry Plc_status_reg #
      hdbMakeEntry Plc_updated_by #
      hdbMakeEntry Plc_updated #
      hdbMakeEntry Plc_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Plc_id Field
---------------------------------------------------------------------------

data Plc_id = Plc_id

instance FieldTag Plc_id where fieldName _ = "plc_id"

plc_id :: Attr Plc_id (Maybe Int)
plc_id = mkAttr Plc_id

---------------------------------------------------------------------------
-- Plc_name Field
---------------------------------------------------------------------------

data Plc_name = Plc_name

instance FieldTag Plc_name where fieldName _ = "plc_name"

plc_name :: Attr Plc_name String
plc_name = mkAttr Plc_name

---------------------------------------------------------------------------
-- Plc_mon_id Field
---------------------------------------------------------------------------

data Plc_mon_id = Plc_mon_id

instance FieldTag Plc_mon_id where fieldName _ = "plc_mon_id"

plc_mon_id :: Attr Plc_mon_id Int
plc_mon_id = mkAttr Plc_mon_id

---------------------------------------------------------------------------
-- Plc_amount Field
---------------------------------------------------------------------------

data Plc_amount = Plc_amount

instance FieldTag Plc_amount where fieldName _ = "plc_amount"

plc_amount :: Attr Plc_amount Integer
plc_amount = mkAttr Plc_amount

---------------------------------------------------------------------------
-- Plc_beg_date Field
---------------------------------------------------------------------------

data Plc_beg_date = Plc_beg_date

instance FieldTag Plc_beg_date where fieldName _ = "plc_beg_date"

plc_beg_date :: Attr Plc_beg_date (Maybe CalendarTime)
plc_beg_date = mkAttr Plc_beg_date

---------------------------------------------------------------------------
-- Plc_exp_date Field
---------------------------------------------------------------------------

data Plc_exp_date = Plc_exp_date

instance FieldTag Plc_exp_date where fieldName _ = "plc_exp_date"

plc_exp_date :: Attr Plc_exp_date (Maybe CalendarTime)
plc_exp_date = mkAttr Plc_exp_date

---------------------------------------------------------------------------
-- Plc_status_reg Field
---------------------------------------------------------------------------

data Plc_status_reg = Plc_status_reg

instance FieldTag Plc_status_reg where
    fieldName _ = "plc_status_reg"

plc_status_reg :: Attr Plc_status_reg String
plc_status_reg = mkAttr Plc_status_reg

---------------------------------------------------------------------------
-- Plc_updated_by Field
---------------------------------------------------------------------------

data Plc_updated_by = Plc_updated_by

instance FieldTag Plc_updated_by where
    fieldName _ = "plc_updated_by"

plc_updated_by :: Attr Plc_updated_by Int
plc_updated_by = mkAttr Plc_updated_by

---------------------------------------------------------------------------
-- Plc_updated Field
---------------------------------------------------------------------------

data Plc_updated = Plc_updated

instance FieldTag Plc_updated where fieldName _ = "plc_updated"

plc_updated :: Attr Plc_updated (Maybe CalendarTime)
plc_updated = mkAttr Plc_updated

---------------------------------------------------------------------------
-- Plc_created Field
---------------------------------------------------------------------------

data Plc_created = Plc_created

instance FieldTag Plc_created where fieldName _ = "plc_created"

plc_created :: Attr Plc_created (Maybe CalendarTime)
plc_created = mkAttr Plc_created
