{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PPI where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PPI  =
    (RecCons Ppi_id Expr (Maybe Int)
     (RecCons Ppi_name Expr String
      (RecCons Ppi_rate Expr Integer
       (RecCons Ppi_status_reg Expr String
        (RecCons Ppi_update_by Expr Int
         (RecCons Ppi_updated Expr (Maybe CalendarTime)
          (RecCons Ppi_created Expr (Maybe CalendarTime) RecNil)))))))

type PPI _result =
    (RecCons Ppi_id ((Maybe Int))
     (RecCons Ppi_name (String)
      (RecCons Ppi_rate (Integer)
       (RecCons Ppi_status_reg (String)
        (RecCons Ppi_update_by (Int)
         (RecCons Ppi_updated ((Maybe CalendarTime))
          (RecCons Ppi_created ((Maybe CalendarTime)) RecNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pPI :: Table PPI
pPI = baseTable "PPI" $
      hdbMakeEntry Ppi_id #
      hdbMakeEntry Ppi_name #
      hdbMakeEntry Ppi_rate #
      hdbMakeEntry Ppi_status_reg #
      hdbMakeEntry Ppi_update_by #
      hdbMakeEntry Ppi_updated #
      hdbMakeEntry Ppi_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ppi_id Field
---------------------------------------------------------------------------

data Ppi_id = Ppi_id

instance FieldTag Ppi_id where fieldName _ = "ppi_id"

ppi_id :: Attr Ppi_id (Maybe Int)
ppi_id = mkAttr Ppi_id

---------------------------------------------------------------------------
-- Ppi_name Field
---------------------------------------------------------------------------

data Ppi_name = Ppi_name

instance FieldTag Ppi_name where fieldName _ = "ppi_name"

ppi_name :: Attr Ppi_name String
ppi_name = mkAttr Ppi_name

---------------------------------------------------------------------------
-- Ppi_rate Field
---------------------------------------------------------------------------

data Ppi_rate = Ppi_rate

instance FieldTag Ppi_rate where fieldName _ = "ppi_rate"

ppi_rate :: Attr Ppi_rate Integer
ppi_rate = mkAttr Ppi_rate

---------------------------------------------------------------------------
-- Ppi_status_reg Field
---------------------------------------------------------------------------

data Ppi_status_reg = Ppi_status_reg

instance FieldTag Ppi_status_reg where
    fieldName _ = "ppi_status_reg"

ppi_status_reg :: Attr Ppi_status_reg String
ppi_status_reg = mkAttr Ppi_status_reg

---------------------------------------------------------------------------
-- Ppi_update_by Field
---------------------------------------------------------------------------

data Ppi_update_by = Ppi_update_by

instance FieldTag Ppi_update_by where
    fieldName _ = "ppi_update_by"

ppi_update_by :: Attr Ppi_update_by Int
ppi_update_by = mkAttr Ppi_update_by

---------------------------------------------------------------------------
-- Ppi_updated Field
---------------------------------------------------------------------------

data Ppi_updated = Ppi_updated

instance FieldTag Ppi_updated where fieldName _ = "ppi_updated"

ppi_updated :: Attr Ppi_updated (Maybe CalendarTime)
ppi_updated = mkAttr Ppi_updated

---------------------------------------------------------------------------
-- Ppi_created Field
---------------------------------------------------------------------------

data Ppi_created = Ppi_created

instance FieldTag Ppi_created where fieldName _ = "ppi_created"

ppi_created :: Attr Ppi_created (Maybe CalendarTime)
ppi_created = mkAttr Ppi_created
