{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack42 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PSI where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PSI  =
    (RecCons Psi_id Expr (Maybe Int)
     (RecCons Psi_value Expr String RecNil))

type PSI _result =
    (RecCons Psi_id ((Maybe Int))
     (RecCons Psi_value (String) RecNil))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pSI :: Table PSI
pSI = baseTable "PSI" $
      hdbMakeEntry Psi_id #
      hdbMakeEntry Psi_value

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Psi_id Field
---------------------------------------------------------------------------

data Psi_id = Psi_id

instance FieldTag Psi_id where fieldName _ = "psi_id"

psi_id :: Attr Psi_id (Maybe Int)
psi_id = mkAttr Psi_id

---------------------------------------------------------------------------
-- Psi_value Field
---------------------------------------------------------------------------

data Psi_value = Psi_value

instance FieldTag Psi_value where fieldName _ = "psi_value"

psi_value :: Attr Psi_value String
psi_value = mkAttr Psi_value
