{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PTP where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PTP  =
    (RecCons Ptp_id Expr (Maybe Int)
     (RecCons Ptp_tpr_id Expr Int
      (RecCons Ptp_pla_id Expr Int
       (RecCons Ptp_active Expr Bool
        (RecCons Ptp_updated_by Expr Int
         (RecCons Ptp_updated Expr (Maybe CalendarTime)
          (RecCons Ptp_created Expr (Maybe CalendarTime) RecNil)))))))

type PTP _result =
    (RecCons Ptp_id ((Maybe Int))
     (RecCons Ptp_tpr_id (Int)
      (RecCons Ptp_pla_id (Int)
       (RecCons Ptp_active (Bool)
        (RecCons Ptp_updated_by (Int)
         (RecCons Ptp_updated ((Maybe CalendarTime))
          (RecCons Ptp_created ((Maybe CalendarTime)) RecNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pTP :: Table PTP
pTP = baseTable "PTP" $
      hdbMakeEntry Ptp_id #
      hdbMakeEntry Ptp_tpr_id #
      hdbMakeEntry Ptp_pla_id #
      hdbMakeEntry Ptp_active #
      hdbMakeEntry Ptp_updated_by #
      hdbMakeEntry Ptp_updated #
      hdbMakeEntry Ptp_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ptp_id Field
---------------------------------------------------------------------------

data Ptp_id = Ptp_id

instance FieldTag Ptp_id where fieldName _ = "ptp_id"

ptp_id :: Attr Ptp_id (Maybe Int)
ptp_id = mkAttr Ptp_id

---------------------------------------------------------------------------
-- Ptp_tpr_id Field
---------------------------------------------------------------------------

data Ptp_tpr_id = Ptp_tpr_id

instance FieldTag Ptp_tpr_id where fieldName _ = "ptp_tpr_id"

ptp_tpr_id :: Attr Ptp_tpr_id Int
ptp_tpr_id = mkAttr Ptp_tpr_id

---------------------------------------------------------------------------
-- Ptp_pla_id Field
---------------------------------------------------------------------------

data Ptp_pla_id = Ptp_pla_id

instance FieldTag Ptp_pla_id where fieldName _ = "ptp_pla_id"

ptp_pla_id :: Attr Ptp_pla_id Int
ptp_pla_id = mkAttr Ptp_pla_id

---------------------------------------------------------------------------
-- Ptp_active Field
---------------------------------------------------------------------------

data Ptp_active = Ptp_active

instance FieldTag Ptp_active where fieldName _ = "ptp_active"

ptp_active :: Attr Ptp_active Bool
ptp_active = mkAttr Ptp_active

---------------------------------------------------------------------------
-- Ptp_updated_by Field
---------------------------------------------------------------------------

data Ptp_updated_by = Ptp_updated_by

instance FieldTag Ptp_updated_by where
    fieldName _ = "ptp_updated_by"

ptp_updated_by :: Attr Ptp_updated_by Int
ptp_updated_by = mkAttr Ptp_updated_by

---------------------------------------------------------------------------
-- Ptp_updated Field
---------------------------------------------------------------------------

data Ptp_updated = Ptp_updated

instance FieldTag Ptp_updated where fieldName _ = "ptp_updated"

ptp_updated :: Attr Ptp_updated (Maybe CalendarTime)
ptp_updated = mkAttr Ptp_updated

---------------------------------------------------------------------------
-- Ptp_created Field
---------------------------------------------------------------------------

data Ptp_created = Ptp_created

instance FieldTag Ptp_created where fieldName _ = "ptp_created"

ptp_created :: Attr Ptp_created (Maybe CalendarTime)
ptp_created = mkAttr Ptp_created
