{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.PUR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type PUR  =
    (RecCons Pur_id Expr (Maybe Int)
     (RecCons Pur_usr_id Expr Int
      (RecCons Pur_hot_id Expr Int
       (RecCons Pur_per_id Expr Int
        (RecCons Pur_status_reg Expr String
         (RecCons Pur_updated_by Expr Int
          (RecCons Pur_updated Expr (Maybe CalendarTime)
           (RecCons Pur_created Expr (Maybe CalendarTime) RecNil))))))))

type PUR _result =
    (RecCons Pur_id ((Maybe Int))
     (RecCons Pur_usr_id (Int)
      (RecCons Pur_hot_id (Int)
       (RecCons Pur_per_id (Int)
        (RecCons Pur_status_reg (String)
         (RecCons Pur_updated_by (Int)
          (RecCons Pur_updated ((Maybe CalendarTime))
           (RecCons Pur_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
pUR :: Table PUR
pUR = baseTable "PUR" $
      hdbMakeEntry Pur_id #
      hdbMakeEntry Pur_usr_id #
      hdbMakeEntry Pur_hot_id #
      hdbMakeEntry Pur_per_id #
      hdbMakeEntry Pur_status_reg #
      hdbMakeEntry Pur_updated_by #
      hdbMakeEntry Pur_updated #
      hdbMakeEntry Pur_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Pur_id Field
---------------------------------------------------------------------------

data Pur_id = Pur_id

instance FieldTag Pur_id where fieldName _ = "pur_id"

pur_id :: Attr Pur_id (Maybe Int)
pur_id = mkAttr Pur_id

---------------------------------------------------------------------------
-- Pur_usr_id Field
---------------------------------------------------------------------------

data Pur_usr_id = Pur_usr_id

instance FieldTag Pur_usr_id where fieldName _ = "pur_usr_id"

pur_usr_id :: Attr Pur_usr_id Int
pur_usr_id = mkAttr Pur_usr_id

---------------------------------------------------------------------------
-- Pur_hot_id Field
---------------------------------------------------------------------------

data Pur_hot_id = Pur_hot_id

instance FieldTag Pur_hot_id where fieldName _ = "pur_hot_id"

pur_hot_id :: Attr Pur_hot_id Int
pur_hot_id = mkAttr Pur_hot_id

---------------------------------------------------------------------------
-- Pur_per_id Field
---------------------------------------------------------------------------

data Pur_per_id = Pur_per_id

instance FieldTag Pur_per_id where fieldName _ = "pur_per_id"

pur_per_id :: Attr Pur_per_id Int
pur_per_id = mkAttr Pur_per_id

---------------------------------------------------------------------------
-- Pur_status_reg Field
---------------------------------------------------------------------------

data Pur_status_reg = Pur_status_reg

instance FieldTag Pur_status_reg where
    fieldName _ = "pur_status_reg"

pur_status_reg :: Attr Pur_status_reg String
pur_status_reg = mkAttr Pur_status_reg

---------------------------------------------------------------------------
-- Pur_updated_by Field
---------------------------------------------------------------------------

data Pur_updated_by = Pur_updated_by

instance FieldTag Pur_updated_by where
    fieldName _ = "pur_updated_by"

pur_updated_by :: Attr Pur_updated_by Int
pur_updated_by = mkAttr Pur_updated_by

---------------------------------------------------------------------------
-- Pur_updated Field
---------------------------------------------------------------------------

data Pur_updated = Pur_updated

instance FieldTag Pur_updated where fieldName _ = "pur_updated"

pur_updated :: Attr Pur_updated (Maybe CalendarTime)
pur_updated = mkAttr Pur_updated

---------------------------------------------------------------------------
-- Pur_created Field
---------------------------------------------------------------------------

data Pur_created = Pur_created

instance FieldTag Pur_created where fieldName _ = "pur_created"

pur_created :: Attr Pur_created (Maybe CalendarTime)
pur_created = mkAttr Pur_created
