{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack83 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.RES where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type RES  =
    (RecCons Res_id Expr (Maybe Int)
     (RecCons Res_id_public Expr String
      (RecCons Res_hot_id Expr Int
       (RecCons Res_cli_id Expr (Maybe Int)
        (RecCons Res_channel Expr String
         (RecCons Res_in Expr (Maybe CalendarTime)
          (RecCons Res_out Expr (Maybe CalendarTime)
           (RecCons Res_sta_prev Expr String
            (RecCons Res_status Expr String
             (RecCons Res_status_obs Expr String
              (RecCons Res_pax_info Expr (Maybe String)
               (RecCons Res_pax_obs Expr (Maybe String)
                (RecCons Res_hot_obs Expr (Maybe String)
                 (RecCons Res_mon_id Expr Int
                  (RecCons Res_cost Expr Double
                   (RecCons Res_cost_calc Expr Double
                    (RecCons Res_cost_hab Expr Double
                     (RecCons Res_cost_ext Expr Double
                      (RecCons Res_fee Expr Double
                       (RecCons Res_debt Expr Double
                        (RecCons Res_adults Expr Int
                         (RecCons Res_children Expr Int
                          (RecCons Res_seniors Expr Int
                           (RecCons Res_additional_field_1_value Expr (Maybe String)
                            (RecCons Res_canc_reason Expr String
                             (RecCons Res_inv_name Expr String
                              (RecCons Res_inv_id Expr String
                               (RecCons Res_inv_city Expr String
                                (RecCons Res_inv_address Expr String
                                 (RecCons Res_inv_ship_ser Expr String
                                  (RecCons Res_paid_amount Expr Double
                                   (RecCons Res_send_payment_email Expr Bool
                                    (RecCons Res_send_confirmed_email Expr Bool
                                     (RecCons Res_paid_status Expr String
                                      (RecCons Res_status_time Expr (Maybe CalendarTime)
                                       (RecCons Res_lock_time Expr (Maybe CalendarTime)
                                        (RecCons Res_voucher Expr (Maybe String)
                                         (RecCons Res_pin Expr (Maybe Int)
                                          (RecCons Res_status_reg Expr String
                                           (RecCons Res_updated_by Expr Int
                                            (RecCons Res_updated Expr (Maybe CalendarTime)
                                             (RecCons Res_created_by Expr Int
                                              (RecCons Res_created Expr (Maybe CalendarTime) RecNil)))))))))))))))))))))))))))))))))))))))))))

type RES _result =
    (RecCons Res_id ((Maybe Int))
     (RecCons Res_id_public (String)
      (RecCons Res_hot_id (Int)
       (RecCons Res_cli_id ((Maybe Int))
        (RecCons Res_channel (String)
         (RecCons Res_in ((Maybe CalendarTime))
          (RecCons Res_out ((Maybe CalendarTime))
           (RecCons Res_sta_prev (String)
            (RecCons Res_status (String)
             (RecCons Res_status_obs (String)
              (RecCons Res_pax_info ((Maybe String))
               (RecCons Res_pax_obs ((Maybe String))
                (RecCons Res_hot_obs ((Maybe String))
                 (RecCons Res_mon_id (Int)
                  (RecCons Res_cost (Double)
                   (RecCons Res_cost_calc (Double)
                    (RecCons Res_cost_hab (Double)
                     (RecCons Res_cost_ext (Double)
                      (RecCons Res_fee (Double)
                       (RecCons Res_debt (Double)
                        (RecCons Res_adults (Int)
                         (RecCons Res_children (Int)
                          (RecCons Res_seniors (Int)
                           (RecCons Res_additional_field_1_value ((Maybe String))
                            (RecCons Res_canc_reason (String)
                             (RecCons Res_inv_name (String)
                              (RecCons Res_inv_id (String)
                               (RecCons Res_inv_city (String)
                                (RecCons Res_inv_address (String)
                                 (RecCons Res_inv_ship_ser (String)
                                  (RecCons Res_paid_amount (Double)
                                   (RecCons Res_send_payment_email (Bool)
                                    (RecCons Res_send_confirmed_email (Bool)
                                     (RecCons Res_paid_status (String)
                                      (RecCons Res_status_time ((Maybe CalendarTime))
                                       (RecCons Res_lock_time ((Maybe CalendarTime))
                                        (RecCons Res_voucher ((Maybe String))
                                         (RecCons Res_pin ((Maybe Int))
                                          (RecCons Res_status_reg (String)
                                           (RecCons Res_updated_by (Int)
                                            (RecCons Res_updated ((Maybe CalendarTime))
                                             (RecCons Res_created_by (Int)
                                              (RecCons Res_created ((Maybe CalendarTime)) RecNil)))))))))))))))))))))))))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
rES :: Table RES
rES = baseTable "RES" $
      hdbMakeEntry Res_id #
      hdbMakeEntry Res_id_public #
      hdbMakeEntry Res_hot_id #
      hdbMakeEntry Res_cli_id #
      hdbMakeEntry Res_channel #
      hdbMakeEntry Res_in #
      hdbMakeEntry Res_out #
      hdbMakeEntry Res_sta_prev #
      hdbMakeEntry Res_status #
      hdbMakeEntry Res_status_obs #
      hdbMakeEntry Res_pax_info #
      hdbMakeEntry Res_pax_obs #
      hdbMakeEntry Res_hot_obs #
      hdbMakeEntry Res_mon_id #
      hdbMakeEntry Res_cost #
      hdbMakeEntry Res_cost_calc #
      hdbMakeEntry Res_cost_hab #
      hdbMakeEntry Res_cost_ext #
      hdbMakeEntry Res_fee #
      hdbMakeEntry Res_debt #
      hdbMakeEntry Res_adults #
      hdbMakeEntry Res_children #
      hdbMakeEntry Res_seniors #
      hdbMakeEntry Res_additional_field_1_value #
      hdbMakeEntry Res_canc_reason #
      hdbMakeEntry Res_inv_name #
      hdbMakeEntry Res_inv_id #
      hdbMakeEntry Res_inv_city #
      hdbMakeEntry Res_inv_address #
      hdbMakeEntry Res_inv_ship_ser #
      hdbMakeEntry Res_paid_amount #
      hdbMakeEntry Res_send_payment_email #
      hdbMakeEntry Res_send_confirmed_email #
      hdbMakeEntry Res_paid_status #
      hdbMakeEntry Res_status_time #
      hdbMakeEntry Res_lock_time #
      hdbMakeEntry Res_voucher #
      hdbMakeEntry Res_pin #
      hdbMakeEntry Res_status_reg #
      hdbMakeEntry Res_updated_by #
      hdbMakeEntry Res_updated #
      hdbMakeEntry Res_created_by #
      hdbMakeEntry Res_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Res_id Field
---------------------------------------------------------------------------

data Res_id = Res_id

instance FieldTag Res_id where fieldName _ = "res_id"

res_id :: Attr Res_id (Maybe Int)
res_id = mkAttr Res_id

---------------------------------------------------------------------------
-- Res_id_public Field
---------------------------------------------------------------------------

data Res_id_public = Res_id_public

instance FieldTag Res_id_public where
    fieldName _ = "res_id_public"

res_id_public :: Attr Res_id_public String
res_id_public = mkAttr Res_id_public

---------------------------------------------------------------------------
-- Res_hot_id Field
---------------------------------------------------------------------------

data Res_hot_id = Res_hot_id

instance FieldTag Res_hot_id where fieldName _ = "res_hot_id"

res_hot_id :: Attr Res_hot_id Int
res_hot_id = mkAttr Res_hot_id

---------------------------------------------------------------------------
-- Res_cli_id Field
---------------------------------------------------------------------------

data Res_cli_id = Res_cli_id

instance FieldTag Res_cli_id where fieldName _ = "res_cli_id"

res_cli_id :: Attr Res_cli_id (Maybe Int)
res_cli_id = mkAttr Res_cli_id

---------------------------------------------------------------------------
-- Res_channel Field
---------------------------------------------------------------------------

data Res_channel = Res_channel

instance FieldTag Res_channel where fieldName _ = "res_channel"

res_channel :: Attr Res_channel String
res_channel = mkAttr Res_channel

---------------------------------------------------------------------------
-- Res_in Field
---------------------------------------------------------------------------

data Res_in = Res_in

instance FieldTag Res_in where fieldName _ = "res_in"

res_in :: Attr Res_in (Maybe CalendarTime)
res_in = mkAttr Res_in

---------------------------------------------------------------------------
-- Res_out Field
---------------------------------------------------------------------------

data Res_out = Res_out

instance FieldTag Res_out where fieldName _ = "res_out"

res_out :: Attr Res_out (Maybe CalendarTime)
res_out = mkAttr Res_out

---------------------------------------------------------------------------
-- Res_sta_prev Field
---------------------------------------------------------------------------

data Res_sta_prev = Res_sta_prev

instance FieldTag Res_sta_prev where fieldName _ = "res_sta_prev"

res_sta_prev :: Attr Res_sta_prev String
res_sta_prev = mkAttr Res_sta_prev

---------------------------------------------------------------------------
-- Res_status Field
---------------------------------------------------------------------------

data Res_status = Res_status

instance FieldTag Res_status where fieldName _ = "res_status"

res_status :: Attr Res_status String
res_status = mkAttr Res_status

---------------------------------------------------------------------------
-- Res_status_obs Field
---------------------------------------------------------------------------

data Res_status_obs = Res_status_obs

instance FieldTag Res_status_obs where
    fieldName _ = "res_status_obs"

res_status_obs :: Attr Res_status_obs String
res_status_obs = mkAttr Res_status_obs

---------------------------------------------------------------------------
-- Res_pax_info Field
---------------------------------------------------------------------------

data Res_pax_info = Res_pax_info

instance FieldTag Res_pax_info where fieldName _ = "res_pax_info"

res_pax_info :: Attr Res_pax_info (Maybe String)
res_pax_info = mkAttr Res_pax_info

---------------------------------------------------------------------------
-- Res_pax_obs Field
---------------------------------------------------------------------------

data Res_pax_obs = Res_pax_obs

instance FieldTag Res_pax_obs where fieldName _ = "res_pax_obs"

res_pax_obs :: Attr Res_pax_obs (Maybe String)
res_pax_obs = mkAttr Res_pax_obs

---------------------------------------------------------------------------
-- Res_hot_obs Field
---------------------------------------------------------------------------

data Res_hot_obs = Res_hot_obs

instance FieldTag Res_hot_obs where fieldName _ = "res_hot_obs"

res_hot_obs :: Attr Res_hot_obs (Maybe String)
res_hot_obs = mkAttr Res_hot_obs

---------------------------------------------------------------------------
-- Res_mon_id Field
---------------------------------------------------------------------------

data Res_mon_id = Res_mon_id

instance FieldTag Res_mon_id where fieldName _ = "res_mon_id"

res_mon_id :: Attr Res_mon_id Int
res_mon_id = mkAttr Res_mon_id

---------------------------------------------------------------------------
-- Res_cost Field
---------------------------------------------------------------------------

data Res_cost = Res_cost

instance FieldTag Res_cost where fieldName _ = "res_cost"

res_cost :: Attr Res_cost Double
res_cost = mkAttr Res_cost

---------------------------------------------------------------------------
-- Res_cost_calc Field
---------------------------------------------------------------------------

data Res_cost_calc = Res_cost_calc

instance FieldTag Res_cost_calc where
    fieldName _ = "res_cost_calc"

res_cost_calc :: Attr Res_cost_calc Double
res_cost_calc = mkAttr Res_cost_calc

---------------------------------------------------------------------------
-- Res_cost_hab Field
---------------------------------------------------------------------------

data Res_cost_hab = Res_cost_hab

instance FieldTag Res_cost_hab where fieldName _ = "res_cost_hab"

res_cost_hab :: Attr Res_cost_hab Double
res_cost_hab = mkAttr Res_cost_hab

---------------------------------------------------------------------------
-- Res_cost_ext Field
---------------------------------------------------------------------------

data Res_cost_ext = Res_cost_ext

instance FieldTag Res_cost_ext where fieldName _ = "res_cost_ext"

res_cost_ext :: Attr Res_cost_ext Double
res_cost_ext = mkAttr Res_cost_ext

---------------------------------------------------------------------------
-- Res_fee Field
---------------------------------------------------------------------------

data Res_fee = Res_fee

instance FieldTag Res_fee where fieldName _ = "res_fee"

res_fee :: Attr Res_fee Double
res_fee = mkAttr Res_fee

---------------------------------------------------------------------------
-- Res_debt Field
---------------------------------------------------------------------------

data Res_debt = Res_debt

instance FieldTag Res_debt where fieldName _ = "res_debt"

res_debt :: Attr Res_debt Double
res_debt = mkAttr Res_debt

---------------------------------------------------------------------------
-- Res_adults Field
---------------------------------------------------------------------------

data Res_adults = Res_adults

instance FieldTag Res_adults where fieldName _ = "res_adults"

res_adults :: Attr Res_adults Int
res_adults = mkAttr Res_adults

---------------------------------------------------------------------------
-- Res_children Field
---------------------------------------------------------------------------

data Res_children = Res_children

instance FieldTag Res_children where fieldName _ = "res_children"

res_children :: Attr Res_children Int
res_children = mkAttr Res_children

---------------------------------------------------------------------------
-- Res_seniors Field
---------------------------------------------------------------------------

data Res_seniors = Res_seniors

instance FieldTag Res_seniors where fieldName _ = "res_seniors"

res_seniors :: Attr Res_seniors Int
res_seniors = mkAttr Res_seniors

---------------------------------------------------------------------------
-- Res_additional_field_1_value Field
---------------------------------------------------------------------------

data Res_additional_field_1_value = Res_additional_field_1_value

instance FieldTag Res_additional_field_1_value where
    fieldName _ = "res_additional_field_1_value"

res_additional_field_1_value :: Attr Res_additional_field_1_value (Maybe String)
res_additional_field_1_value = mkAttr Res_additional_field_1_value

---------------------------------------------------------------------------
-- Res_canc_reason Field
---------------------------------------------------------------------------

data Res_canc_reason = Res_canc_reason

instance FieldTag Res_canc_reason where
    fieldName _ = "res_canc_reason"

res_canc_reason :: Attr Res_canc_reason String
res_canc_reason = mkAttr Res_canc_reason

---------------------------------------------------------------------------
-- Res_inv_name Field
---------------------------------------------------------------------------

data Res_inv_name = Res_inv_name

instance FieldTag Res_inv_name where fieldName _ = "res_inv_name"

res_inv_name :: Attr Res_inv_name String
res_inv_name = mkAttr Res_inv_name

---------------------------------------------------------------------------
-- Res_inv_id Field
---------------------------------------------------------------------------

data Res_inv_id = Res_inv_id

instance FieldTag Res_inv_id where fieldName _ = "res_inv_id"

res_inv_id :: Attr Res_inv_id String
res_inv_id = mkAttr Res_inv_id

---------------------------------------------------------------------------
-- Res_inv_city Field
---------------------------------------------------------------------------

data Res_inv_city = Res_inv_city

instance FieldTag Res_inv_city where fieldName _ = "res_inv_city"

res_inv_city :: Attr Res_inv_city String
res_inv_city = mkAttr Res_inv_city

---------------------------------------------------------------------------
-- Res_inv_address Field
---------------------------------------------------------------------------

data Res_inv_address = Res_inv_address

instance FieldTag Res_inv_address where
    fieldName _ = "res_inv_address"

res_inv_address :: Attr Res_inv_address String
res_inv_address = mkAttr Res_inv_address

---------------------------------------------------------------------------
-- Res_inv_ship_ser Field
---------------------------------------------------------------------------

data Res_inv_ship_ser = Res_inv_ship_ser

instance FieldTag Res_inv_ship_ser where
    fieldName _ = "res_inv_ship_ser"

res_inv_ship_ser :: Attr Res_inv_ship_ser String
res_inv_ship_ser = mkAttr Res_inv_ship_ser

---------------------------------------------------------------------------
-- Res_paid_amount Field
---------------------------------------------------------------------------

data Res_paid_amount = Res_paid_amount

instance FieldTag Res_paid_amount where
    fieldName _ = "res_paid_amount"

res_paid_amount :: Attr Res_paid_amount Double
res_paid_amount = mkAttr Res_paid_amount

---------------------------------------------------------------------------
-- Res_send_payment_email Field
---------------------------------------------------------------------------

data Res_send_payment_email = Res_send_payment_email

instance FieldTag Res_send_payment_email where
    fieldName _ = "res_send_payment_email"

res_send_payment_email :: Attr Res_send_payment_email Bool
res_send_payment_email = mkAttr Res_send_payment_email

---------------------------------------------------------------------------
-- Res_send_confirmed_email Field
---------------------------------------------------------------------------

data Res_send_confirmed_email = Res_send_confirmed_email

instance FieldTag Res_send_confirmed_email where
    fieldName _ = "res_send_confirmed_email"

res_send_confirmed_email :: Attr Res_send_confirmed_email Bool
res_send_confirmed_email = mkAttr Res_send_confirmed_email

---------------------------------------------------------------------------
-- Res_paid_status Field
---------------------------------------------------------------------------

data Res_paid_status = Res_paid_status

instance FieldTag Res_paid_status where
    fieldName _ = "res_paid_status"

res_paid_status :: Attr Res_paid_status String
res_paid_status = mkAttr Res_paid_status

---------------------------------------------------------------------------
-- Res_status_time Field
---------------------------------------------------------------------------

data Res_status_time = Res_status_time

instance FieldTag Res_status_time where
    fieldName _ = "res_status_time"

res_status_time :: Attr Res_status_time (Maybe CalendarTime)
res_status_time = mkAttr Res_status_time

---------------------------------------------------------------------------
-- Res_lock_time Field
---------------------------------------------------------------------------

data Res_lock_time = Res_lock_time

instance FieldTag Res_lock_time where
    fieldName _ = "res_lock_time"

res_lock_time :: Attr Res_lock_time (Maybe CalendarTime)
res_lock_time = mkAttr Res_lock_time

---------------------------------------------------------------------------
-- Res_voucher Field
---------------------------------------------------------------------------

data Res_voucher = Res_voucher

instance FieldTag Res_voucher where fieldName _ = "res_voucher"

res_voucher :: Attr Res_voucher (Maybe String)
res_voucher = mkAttr Res_voucher

---------------------------------------------------------------------------
-- Res_pin Field
---------------------------------------------------------------------------

data Res_pin = Res_pin

instance FieldTag Res_pin where fieldName _ = "res_pin"

res_pin :: Attr Res_pin (Maybe Int)
res_pin = mkAttr Res_pin

---------------------------------------------------------------------------
-- Res_status_reg Field
---------------------------------------------------------------------------

data Res_status_reg = Res_status_reg

instance FieldTag Res_status_reg where
    fieldName _ = "res_status_reg"

res_status_reg :: Attr Res_status_reg String
res_status_reg = mkAttr Res_status_reg

---------------------------------------------------------------------------
-- Res_updated_by Field
---------------------------------------------------------------------------

data Res_updated_by = Res_updated_by

instance FieldTag Res_updated_by where
    fieldName _ = "res_updated_by"

res_updated_by :: Attr Res_updated_by Int
res_updated_by = mkAttr Res_updated_by

---------------------------------------------------------------------------
-- Res_updated Field
---------------------------------------------------------------------------

data Res_updated = Res_updated

instance FieldTag Res_updated where fieldName _ = "res_updated"

res_updated :: Attr Res_updated (Maybe CalendarTime)
res_updated = mkAttr Res_updated

---------------------------------------------------------------------------
-- Res_created_by Field
---------------------------------------------------------------------------

data Res_created_by = Res_created_by

instance FieldTag Res_created_by where
    fieldName _ = "res_created_by"

res_created_by :: Attr Res_created_by Int
res_created_by = mkAttr Res_created_by

---------------------------------------------------------------------------
-- Res_created Field
---------------------------------------------------------------------------

data Res_created = Res_created

instance FieldTag Res_created where fieldName _ = "res_created"

res_created :: Attr Res_created (Maybe CalendarTime)
res_created = mkAttr Res_created
