{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack50 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.ROL where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type ROL  =
    (RecCons Rol_id Expr (Maybe Int)
     (RecCons Rol_usr_id Expr Int
      (RecCons Rol_context Expr String
       (RecCons Rol_name Expr String
        (RecCons Rol_table Expr String
         (RecCons Rol_registry Expr Int
          (RecCons Rol_status_reg Expr String
           (RecCons Rol_updated_by Expr Int
            (RecCons Rol_updated Expr (Maybe CalendarTime)
             (RecCons Rol_created Expr (Maybe CalendarTime) RecNil))))))))))

type ROL _result =
    (RecCons Rol_id ((Maybe Int))
     (RecCons Rol_usr_id (Int)
      (RecCons Rol_context (String)
       (RecCons Rol_name (String)
        (RecCons Rol_table (String)
         (RecCons Rol_registry (Int)
          (RecCons Rol_status_reg (String)
           (RecCons Rol_updated_by (Int)
            (RecCons Rol_updated ((Maybe CalendarTime))
             (RecCons Rol_created ((Maybe CalendarTime)) RecNil))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
rOL :: Table ROL
rOL = baseTable "ROL" $
      hdbMakeEntry Rol_id #
      hdbMakeEntry Rol_usr_id #
      hdbMakeEntry Rol_context #
      hdbMakeEntry Rol_name #
      hdbMakeEntry Rol_table #
      hdbMakeEntry Rol_registry #
      hdbMakeEntry Rol_status_reg #
      hdbMakeEntry Rol_updated_by #
      hdbMakeEntry Rol_updated #
      hdbMakeEntry Rol_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Rol_id Field
---------------------------------------------------------------------------

data Rol_id = Rol_id

instance FieldTag Rol_id where fieldName _ = "rol_id"

rol_id :: Attr Rol_id (Maybe Int)
rol_id = mkAttr Rol_id

---------------------------------------------------------------------------
-- Rol_usr_id Field
---------------------------------------------------------------------------

data Rol_usr_id = Rol_usr_id

instance FieldTag Rol_usr_id where fieldName _ = "rol_usr_id"

rol_usr_id :: Attr Rol_usr_id Int
rol_usr_id = mkAttr Rol_usr_id

---------------------------------------------------------------------------
-- Rol_context Field
---------------------------------------------------------------------------

data Rol_context = Rol_context

instance FieldTag Rol_context where fieldName _ = "rol_context"

rol_context :: Attr Rol_context String
rol_context = mkAttr Rol_context

---------------------------------------------------------------------------
-- Rol_name Field
---------------------------------------------------------------------------

data Rol_name = Rol_name

instance FieldTag Rol_name where fieldName _ = "rol_name"

rol_name :: Attr Rol_name String
rol_name = mkAttr Rol_name

---------------------------------------------------------------------------
-- Rol_table Field
---------------------------------------------------------------------------

data Rol_table = Rol_table

instance FieldTag Rol_table where fieldName _ = "rol_table"

rol_table :: Attr Rol_table String
rol_table = mkAttr Rol_table

---------------------------------------------------------------------------
-- Rol_registry Field
---------------------------------------------------------------------------

data Rol_registry = Rol_registry

instance FieldTag Rol_registry where fieldName _ = "rol_registry"

rol_registry :: Attr Rol_registry Int
rol_registry = mkAttr Rol_registry

---------------------------------------------------------------------------
-- Rol_status_reg Field
---------------------------------------------------------------------------

data Rol_status_reg = Rol_status_reg

instance FieldTag Rol_status_reg where
    fieldName _ = "rol_status_reg"

rol_status_reg :: Attr Rol_status_reg String
rol_status_reg = mkAttr Rol_status_reg

---------------------------------------------------------------------------
-- Rol_updated_by Field
---------------------------------------------------------------------------

data Rol_updated_by = Rol_updated_by

instance FieldTag Rol_updated_by where
    fieldName _ = "rol_updated_by"

rol_updated_by :: Attr Rol_updated_by Int
rol_updated_by = mkAttr Rol_updated_by

---------------------------------------------------------------------------
-- Rol_updated Field
---------------------------------------------------------------------------

data Rol_updated = Rol_updated

instance FieldTag Rol_updated where fieldName _ = "rol_updated"

rol_updated :: Attr Rol_updated (Maybe CalendarTime)
rol_updated = mkAttr Rol_updated

---------------------------------------------------------------------------
-- Rol_created Field
---------------------------------------------------------------------------

data Rol_created = Rol_created

instance FieldTag Rol_created where fieldName _ = "rol_created"

rol_created :: Attr Rol_created (Maybe CalendarTime)
rol_created = mkAttr Rol_created
