{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.SER where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type SER  =
    (RecCons Ser_id Expr (Maybe Int)
     (RecCons Ser_name Expr String
      (RecCons Ser_desc Expr String
       (RecCons Ser_amount Expr Integer
        (RecCons Ser_status_reg Expr String
         (RecCons Ser_updated_by Expr Int
          (RecCons Ser_updated Expr (Maybe CalendarTime)
           (RecCons Ser_created Expr (Maybe CalendarTime) RecNil))))))))

type SER _result =
    (RecCons Ser_id ((Maybe Int))
     (RecCons Ser_name (String)
      (RecCons Ser_desc (String)
       (RecCons Ser_amount (Integer)
        (RecCons Ser_status_reg (String)
         (RecCons Ser_updated_by (Int)
          (RecCons Ser_updated ((Maybe CalendarTime))
           (RecCons Ser_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
sER :: Table SER
sER = baseTable "SER" $
      hdbMakeEntry Ser_id #
      hdbMakeEntry Ser_name #
      hdbMakeEntry Ser_desc #
      hdbMakeEntry Ser_amount #
      hdbMakeEntry Ser_status_reg #
      hdbMakeEntry Ser_updated_by #
      hdbMakeEntry Ser_updated #
      hdbMakeEntry Ser_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ser_id Field
---------------------------------------------------------------------------

data Ser_id = Ser_id

instance FieldTag Ser_id where fieldName _ = "ser_id"

ser_id :: Attr Ser_id (Maybe Int)
ser_id = mkAttr Ser_id

---------------------------------------------------------------------------
-- Ser_name Field
---------------------------------------------------------------------------

data Ser_name = Ser_name

instance FieldTag Ser_name where fieldName _ = "ser_name"

ser_name :: Attr Ser_name String
ser_name = mkAttr Ser_name

---------------------------------------------------------------------------
-- Ser_desc Field
---------------------------------------------------------------------------

data Ser_desc = Ser_desc

instance FieldTag Ser_desc where fieldName _ = "ser_desc"

ser_desc :: Attr Ser_desc String
ser_desc = mkAttr Ser_desc

---------------------------------------------------------------------------
-- Ser_amount Field
---------------------------------------------------------------------------

data Ser_amount = Ser_amount

instance FieldTag Ser_amount where fieldName _ = "ser_amount"

ser_amount :: Attr Ser_amount Integer
ser_amount = mkAttr Ser_amount

---------------------------------------------------------------------------
-- Ser_status_reg Field
---------------------------------------------------------------------------

data Ser_status_reg = Ser_status_reg

instance FieldTag Ser_status_reg where
    fieldName _ = "ser_status_reg"

ser_status_reg :: Attr Ser_status_reg String
ser_status_reg = mkAttr Ser_status_reg

---------------------------------------------------------------------------
-- Ser_updated_by Field
---------------------------------------------------------------------------

data Ser_updated_by = Ser_updated_by

instance FieldTag Ser_updated_by where
    fieldName _ = "ser_updated_by"

ser_updated_by :: Attr Ser_updated_by Int
ser_updated_by = mkAttr Ser_updated_by

---------------------------------------------------------------------------
-- Ser_updated Field
---------------------------------------------------------------------------

data Ser_updated = Ser_updated

instance FieldTag Ser_updated where fieldName _ = "ser_updated"

ser_updated :: Attr Ser_updated (Maybe CalendarTime)
ser_updated = mkAttr Ser_updated

---------------------------------------------------------------------------
-- Ser_created Field
---------------------------------------------------------------------------

data Ser_created = Ser_created

instance FieldTag Ser_created where fieldName _ = "ser_created"

ser_created :: Attr Ser_created (Maybe CalendarTime)
ser_created = mkAttr Ser_created
