{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack51 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.SES where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type SES  =
    (RecCons Ses_id Expr (Maybe Int)
     (RecCons Ses_ref_type Expr String
      (RecCons Ses_ref_id Expr Int
       (RecCons Ses_psi_id Expr (Maybe Int)
        (RecCons Ses_cookie Expr Bool
         (RecCons Ses_ip Expr Int
          (RecCons Ses_hostname Expr String
           (RecCons Ses_user_agent Expr String
            (RecCons Ses_prev Expr (Maybe Int)
             (RecCons Ses_updated Expr (Maybe CalendarTime)
              (RecCons Ses_created Expr (Maybe CalendarTime) RecNil)))))))))))

type SES _result =
    (RecCons Ses_id ((Maybe Int))
     (RecCons Ses_ref_type (String)
      (RecCons Ses_ref_id (Int)
       (RecCons Ses_psi_id ((Maybe Int))
        (RecCons Ses_cookie (Bool)
         (RecCons Ses_ip (Int)
          (RecCons Ses_hostname (String)
           (RecCons Ses_user_agent (String)
            (RecCons Ses_prev ((Maybe Int))
             (RecCons Ses_updated ((Maybe CalendarTime))
              (RecCons Ses_created ((Maybe CalendarTime)) RecNil)))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
sES :: Table SES
sES = baseTable "SES" $
      hdbMakeEntry Ses_id #
      hdbMakeEntry Ses_ref_type #
      hdbMakeEntry Ses_ref_id #
      hdbMakeEntry Ses_psi_id #
      hdbMakeEntry Ses_cookie #
      hdbMakeEntry Ses_ip #
      hdbMakeEntry Ses_hostname #
      hdbMakeEntry Ses_user_agent #
      hdbMakeEntry Ses_prev #
      hdbMakeEntry Ses_updated #
      hdbMakeEntry Ses_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Ses_id Field
---------------------------------------------------------------------------

data Ses_id = Ses_id

instance FieldTag Ses_id where fieldName _ = "ses_id"

ses_id :: Attr Ses_id (Maybe Int)
ses_id = mkAttr Ses_id

---------------------------------------------------------------------------
-- Ses_ref_type Field
---------------------------------------------------------------------------

data Ses_ref_type = Ses_ref_type

instance FieldTag Ses_ref_type where fieldName _ = "ses_ref_type"

ses_ref_type :: Attr Ses_ref_type String
ses_ref_type = mkAttr Ses_ref_type

---------------------------------------------------------------------------
-- Ses_ref_id Field
---------------------------------------------------------------------------

data Ses_ref_id = Ses_ref_id

instance FieldTag Ses_ref_id where fieldName _ = "ses_ref_id"

ses_ref_id :: Attr Ses_ref_id Int
ses_ref_id = mkAttr Ses_ref_id

---------------------------------------------------------------------------
-- Ses_psi_id Field
---------------------------------------------------------------------------

data Ses_psi_id = Ses_psi_id

instance FieldTag Ses_psi_id where fieldName _ = "ses_psi_id"

ses_psi_id :: Attr Ses_psi_id (Maybe Int)
ses_psi_id = mkAttr Ses_psi_id

---------------------------------------------------------------------------
-- Ses_cookie Field
---------------------------------------------------------------------------

data Ses_cookie = Ses_cookie

instance FieldTag Ses_cookie where fieldName _ = "ses_cookie"

ses_cookie :: Attr Ses_cookie Bool
ses_cookie = mkAttr Ses_cookie

---------------------------------------------------------------------------
-- Ses_ip Field
---------------------------------------------------------------------------

data Ses_ip = Ses_ip

instance FieldTag Ses_ip where fieldName _ = "ses_ip"

ses_ip :: Attr Ses_ip Int
ses_ip = mkAttr Ses_ip

---------------------------------------------------------------------------
-- Ses_hostname Field
---------------------------------------------------------------------------

data Ses_hostname = Ses_hostname

instance FieldTag Ses_hostname where fieldName _ = "ses_hostname"

ses_hostname :: Attr Ses_hostname String
ses_hostname = mkAttr Ses_hostname

---------------------------------------------------------------------------
-- Ses_user_agent Field
---------------------------------------------------------------------------

data Ses_user_agent = Ses_user_agent

instance FieldTag Ses_user_agent where
    fieldName _ = "ses_user_agent"

ses_user_agent :: Attr Ses_user_agent String
ses_user_agent = mkAttr Ses_user_agent

---------------------------------------------------------------------------
-- Ses_prev Field
---------------------------------------------------------------------------

data Ses_prev = Ses_prev

instance FieldTag Ses_prev where fieldName _ = "ses_prev"

ses_prev :: Attr Ses_prev (Maybe Int)
ses_prev = mkAttr Ses_prev

---------------------------------------------------------------------------
-- Ses_updated Field
---------------------------------------------------------------------------

data Ses_updated = Ses_updated

instance FieldTag Ses_updated where fieldName _ = "ses_updated"

ses_updated :: Attr Ses_updated (Maybe CalendarTime)
ses_updated = mkAttr Ses_updated

---------------------------------------------------------------------------
-- Ses_created Field
---------------------------------------------------------------------------

data Ses_created = Ses_created

instance FieldTag Ses_created where fieldName _ = "ses_created"

ses_created :: Attr Ses_created (Maybe CalendarTime)
ses_created = mkAttr Ses_created
