{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack47 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.SPL where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type SPL  =
    (RecCons Spl_id Expr (Maybe Int)
     (RecCons Spl_plc_id Expr Int
      (RecCons Spl_ser_id Expr Int
       (RecCons Spl_status_reg Expr String
        (RecCons Spl_updated_by Expr Int
         (RecCons Spl_updated Expr (Maybe CalendarTime)
          (RecCons Spl_created Expr (Maybe CalendarTime) RecNil)))))))

type SPL _result =
    (RecCons Spl_id ((Maybe Int))
     (RecCons Spl_plc_id (Int)
      (RecCons Spl_ser_id (Int)
       (RecCons Spl_status_reg (String)
        (RecCons Spl_updated_by (Int)
         (RecCons Spl_updated ((Maybe CalendarTime))
          (RecCons Spl_created ((Maybe CalendarTime)) RecNil)))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
sPL :: Table SPL
sPL = baseTable "SPL" $
      hdbMakeEntry Spl_id #
      hdbMakeEntry Spl_plc_id #
      hdbMakeEntry Spl_ser_id #
      hdbMakeEntry Spl_status_reg #
      hdbMakeEntry Spl_updated_by #
      hdbMakeEntry Spl_updated #
      hdbMakeEntry Spl_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Spl_id Field
---------------------------------------------------------------------------

data Spl_id = Spl_id

instance FieldTag Spl_id where fieldName _ = "spl_id"

spl_id :: Attr Spl_id (Maybe Int)
spl_id = mkAttr Spl_id

---------------------------------------------------------------------------
-- Spl_plc_id Field
---------------------------------------------------------------------------

data Spl_plc_id = Spl_plc_id

instance FieldTag Spl_plc_id where fieldName _ = "spl_plc_id"

spl_plc_id :: Attr Spl_plc_id Int
spl_plc_id = mkAttr Spl_plc_id

---------------------------------------------------------------------------
-- Spl_ser_id Field
---------------------------------------------------------------------------

data Spl_ser_id = Spl_ser_id

instance FieldTag Spl_ser_id where fieldName _ = "spl_ser_id"

spl_ser_id :: Attr Spl_ser_id Int
spl_ser_id = mkAttr Spl_ser_id

---------------------------------------------------------------------------
-- Spl_status_reg Field
---------------------------------------------------------------------------

data Spl_status_reg = Spl_status_reg

instance FieldTag Spl_status_reg where
    fieldName _ = "spl_status_reg"

spl_status_reg :: Attr Spl_status_reg String
spl_status_reg = mkAttr Spl_status_reg

---------------------------------------------------------------------------
-- Spl_updated_by Field
---------------------------------------------------------------------------

data Spl_updated_by = Spl_updated_by

instance FieldTag Spl_updated_by where
    fieldName _ = "spl_updated_by"

spl_updated_by :: Attr Spl_updated_by Int
spl_updated_by = mkAttr Spl_updated_by

---------------------------------------------------------------------------
-- Spl_updated Field
---------------------------------------------------------------------------

data Spl_updated = Spl_updated

instance FieldTag Spl_updated where fieldName _ = "spl_updated"

spl_updated :: Attr Spl_updated (Maybe CalendarTime)
spl_updated = mkAttr Spl_updated

---------------------------------------------------------------------------
-- Spl_created Field
---------------------------------------------------------------------------

data Spl_created = Spl_created

instance FieldTag Spl_created where fieldName _ = "spl_created"

spl_created :: Attr Spl_created (Maybe CalendarTime)
spl_created = mkAttr Spl_created
