{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack46 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.SUS where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type SUS  =
    (RecCons Sus_id Expr (Maybe Int)
     (RecCons Sus_email Expr String
      (RecCons Sus_status_reg Expr String
       (RecCons Sus_updated_by Expr Int
        (RecCons Sus_updated Expr (Maybe CalendarTime)
         (RecCons Sus_created Expr (Maybe CalendarTime) RecNil))))))

type SUS _result =
    (RecCons Sus_id ((Maybe Int))
     (RecCons Sus_email (String)
      (RecCons Sus_status_reg (String)
       (RecCons Sus_updated_by (Int)
        (RecCons Sus_updated ((Maybe CalendarTime))
         (RecCons Sus_created ((Maybe CalendarTime)) RecNil))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
sUS :: Table SUS
sUS = baseTable "SUS" $
      hdbMakeEntry Sus_id #
      hdbMakeEntry Sus_email #
      hdbMakeEntry Sus_status_reg #
      hdbMakeEntry Sus_updated_by #
      hdbMakeEntry Sus_updated #
      hdbMakeEntry Sus_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Sus_id Field
---------------------------------------------------------------------------

data Sus_id = Sus_id

instance FieldTag Sus_id where fieldName _ = "sus_id"

sus_id :: Attr Sus_id (Maybe Int)
sus_id = mkAttr Sus_id

---------------------------------------------------------------------------
-- Sus_email Field
---------------------------------------------------------------------------

data Sus_email = Sus_email

instance FieldTag Sus_email where fieldName _ = "sus_email"

sus_email :: Attr Sus_email String
sus_email = mkAttr Sus_email

---------------------------------------------------------------------------
-- Sus_status_reg Field
---------------------------------------------------------------------------

data Sus_status_reg = Sus_status_reg

instance FieldTag Sus_status_reg where
    fieldName _ = "sus_status_reg"

sus_status_reg :: Attr Sus_status_reg String
sus_status_reg = mkAttr Sus_status_reg

---------------------------------------------------------------------------
-- Sus_updated_by Field
---------------------------------------------------------------------------

data Sus_updated_by = Sus_updated_by

instance FieldTag Sus_updated_by where
    fieldName _ = "sus_updated_by"

sus_updated_by :: Attr Sus_updated_by Int
sus_updated_by = mkAttr Sus_updated_by

---------------------------------------------------------------------------
-- Sus_updated Field
---------------------------------------------------------------------------

data Sus_updated = Sus_updated

instance FieldTag Sus_updated where fieldName _ = "sus_updated"

sus_updated :: Attr Sus_updated (Maybe CalendarTime)
sus_updated = mkAttr Sus_updated

---------------------------------------------------------------------------
-- Sus_created Field
---------------------------------------------------------------------------

data Sus_created = Sus_created

instance FieldTag Sus_created where fieldName _ = "sus_created"

sus_created :: Attr Sus_created (Maybe CalendarTime)
sus_created = mkAttr Sus_created
