{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack61 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.TAR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type TAR  =
    (RecCons Tar_id Expr (Maybe Int)
     (RecCons Tar_hot_id Expr Int
      (RecCons Tar_mon_id Expr Int
       (RecCons Tar_tpr_id Expr Int
        (RecCons Tar_pla_id Expr Int
         (RecCons Tar_tha_id Expr (Maybe Int)
          (RecCons Tar_amount1 Expr Double
           (RecCons Tar_amount2 Expr Double
            (RecCons Tar_amount3 Expr Double
             (RecCons Tar_amount4 Expr Double
              (RecCons Tar_amount5 Expr Double
               (RecCons Tar_amount6 Expr Double
                (RecCons Tar_amount7 Expr Double
                 (RecCons Tar_amount8 Expr Double
                  (RecCons Tar_amount9 Expr Double
                   (RecCons Tar_amount10 Expr Double
                    (RecCons Tar_day_next_gap Expr Int
                     (RecCons Tar_active Expr Bool
                      (RecCons Tar_updated_by Expr Int
                       (RecCons Tar_updated Expr (Maybe CalendarTime)
                        (RecCons Tar_created Expr (Maybe CalendarTime) RecNil)))))))))))))))))))))

type TAR _result =
    (RecCons Tar_id ((Maybe Int))
     (RecCons Tar_hot_id (Int)
      (RecCons Tar_mon_id (Int)
       (RecCons Tar_tpr_id (Int)
        (RecCons Tar_pla_id (Int)
         (RecCons Tar_tha_id ((Maybe Int))
          (RecCons Tar_amount1 (Double)
           (RecCons Tar_amount2 (Double)
            (RecCons Tar_amount3 (Double)
             (RecCons Tar_amount4 (Double)
              (RecCons Tar_amount5 (Double)
               (RecCons Tar_amount6 (Double)
                (RecCons Tar_amount7 (Double)
                 (RecCons Tar_amount8 (Double)
                  (RecCons Tar_amount9 (Double)
                   (RecCons Tar_amount10 (Double)
                    (RecCons Tar_day_next_gap (Int)
                     (RecCons Tar_active (Bool)
                      (RecCons Tar_updated_by (Int)
                       (RecCons Tar_updated ((Maybe CalendarTime))
                        (RecCons Tar_created ((Maybe CalendarTime)) RecNil)))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
tAR :: Table TAR
tAR = baseTable "TAR" $
      hdbMakeEntry Tar_id #
      hdbMakeEntry Tar_hot_id #
      hdbMakeEntry Tar_mon_id #
      hdbMakeEntry Tar_tpr_id #
      hdbMakeEntry Tar_pla_id #
      hdbMakeEntry Tar_tha_id #
      hdbMakeEntry Tar_amount1 #
      hdbMakeEntry Tar_amount2 #
      hdbMakeEntry Tar_amount3 #
      hdbMakeEntry Tar_amount4 #
      hdbMakeEntry Tar_amount5 #
      hdbMakeEntry Tar_amount6 #
      hdbMakeEntry Tar_amount7 #
      hdbMakeEntry Tar_amount8 #
      hdbMakeEntry Tar_amount9 #
      hdbMakeEntry Tar_amount10 #
      hdbMakeEntry Tar_day_next_gap #
      hdbMakeEntry Tar_active #
      hdbMakeEntry Tar_updated_by #
      hdbMakeEntry Tar_updated #
      hdbMakeEntry Tar_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Tar_id Field
---------------------------------------------------------------------------

data Tar_id = Tar_id

instance FieldTag Tar_id where fieldName _ = "tar_id"

tar_id :: Attr Tar_id (Maybe Int)
tar_id = mkAttr Tar_id

---------------------------------------------------------------------------
-- Tar_hot_id Field
---------------------------------------------------------------------------

data Tar_hot_id = Tar_hot_id

instance FieldTag Tar_hot_id where fieldName _ = "tar_hot_id"

tar_hot_id :: Attr Tar_hot_id Int
tar_hot_id = mkAttr Tar_hot_id

---------------------------------------------------------------------------
-- Tar_mon_id Field
---------------------------------------------------------------------------

data Tar_mon_id = Tar_mon_id

instance FieldTag Tar_mon_id where fieldName _ = "tar_mon_id"

tar_mon_id :: Attr Tar_mon_id Int
tar_mon_id = mkAttr Tar_mon_id

---------------------------------------------------------------------------
-- Tar_tpr_id Field
---------------------------------------------------------------------------

data Tar_tpr_id = Tar_tpr_id

instance FieldTag Tar_tpr_id where fieldName _ = "tar_tpr_id"

tar_tpr_id :: Attr Tar_tpr_id Int
tar_tpr_id = mkAttr Tar_tpr_id

---------------------------------------------------------------------------
-- Tar_pla_id Field
---------------------------------------------------------------------------

data Tar_pla_id = Tar_pla_id

instance FieldTag Tar_pla_id where fieldName _ = "tar_pla_id"

tar_pla_id :: Attr Tar_pla_id Int
tar_pla_id = mkAttr Tar_pla_id

---------------------------------------------------------------------------
-- Tar_tha_id Field
---------------------------------------------------------------------------

data Tar_tha_id = Tar_tha_id

instance FieldTag Tar_tha_id where fieldName _ = "tar_tha_id"

tar_tha_id :: Attr Tar_tha_id (Maybe Int)
tar_tha_id = mkAttr Tar_tha_id

---------------------------------------------------------------------------
-- Tar_amount1 Field
---------------------------------------------------------------------------

data Tar_amount1 = Tar_amount1

instance FieldTag Tar_amount1 where fieldName _ = "tar_amount1"

tar_amount1 :: Attr Tar_amount1 Double
tar_amount1 = mkAttr Tar_amount1

---------------------------------------------------------------------------
-- Tar_amount2 Field
---------------------------------------------------------------------------

data Tar_amount2 = Tar_amount2

instance FieldTag Tar_amount2 where fieldName _ = "tar_amount2"

tar_amount2 :: Attr Tar_amount2 Double
tar_amount2 = mkAttr Tar_amount2

---------------------------------------------------------------------------
-- Tar_amount3 Field
---------------------------------------------------------------------------

data Tar_amount3 = Tar_amount3

instance FieldTag Tar_amount3 where fieldName _ = "tar_amount3"

tar_amount3 :: Attr Tar_amount3 Double
tar_amount3 = mkAttr Tar_amount3

---------------------------------------------------------------------------
-- Tar_amount4 Field
---------------------------------------------------------------------------

data Tar_amount4 = Tar_amount4

instance FieldTag Tar_amount4 where fieldName _ = "tar_amount4"

tar_amount4 :: Attr Tar_amount4 Double
tar_amount4 = mkAttr Tar_amount4

---------------------------------------------------------------------------
-- Tar_amount5 Field
---------------------------------------------------------------------------

data Tar_amount5 = Tar_amount5

instance FieldTag Tar_amount5 where fieldName _ = "tar_amount5"

tar_amount5 :: Attr Tar_amount5 Double
tar_amount5 = mkAttr Tar_amount5

---------------------------------------------------------------------------
-- Tar_amount6 Field
---------------------------------------------------------------------------

data Tar_amount6 = Tar_amount6

instance FieldTag Tar_amount6 where fieldName _ = "tar_amount6"

tar_amount6 :: Attr Tar_amount6 Double
tar_amount6 = mkAttr Tar_amount6

---------------------------------------------------------------------------
-- Tar_amount7 Field
---------------------------------------------------------------------------

data Tar_amount7 = Tar_amount7

instance FieldTag Tar_amount7 where fieldName _ = "tar_amount7"

tar_amount7 :: Attr Tar_amount7 Double
tar_amount7 = mkAttr Tar_amount7

---------------------------------------------------------------------------
-- Tar_amount8 Field
---------------------------------------------------------------------------

data Tar_amount8 = Tar_amount8

instance FieldTag Tar_amount8 where fieldName _ = "tar_amount8"

tar_amount8 :: Attr Tar_amount8 Double
tar_amount8 = mkAttr Tar_amount8

---------------------------------------------------------------------------
-- Tar_amount9 Field
---------------------------------------------------------------------------

data Tar_amount9 = Tar_amount9

instance FieldTag Tar_amount9 where fieldName _ = "tar_amount9"

tar_amount9 :: Attr Tar_amount9 Double
tar_amount9 = mkAttr Tar_amount9

---------------------------------------------------------------------------
-- Tar_amount10 Field
---------------------------------------------------------------------------

data Tar_amount10 = Tar_amount10

instance FieldTag Tar_amount10 where fieldName _ = "tar_amount10"

tar_amount10 :: Attr Tar_amount10 Double
tar_amount10 = mkAttr Tar_amount10

---------------------------------------------------------------------------
-- Tar_day_next_gap Field
---------------------------------------------------------------------------

data Tar_day_next_gap = Tar_day_next_gap

instance FieldTag Tar_day_next_gap where
    fieldName _ = "tar_day_next_gap"

tar_day_next_gap :: Attr Tar_day_next_gap Int
tar_day_next_gap = mkAttr Tar_day_next_gap

---------------------------------------------------------------------------
-- Tar_active Field
---------------------------------------------------------------------------

data Tar_active = Tar_active

instance FieldTag Tar_active where fieldName _ = "tar_active"

tar_active :: Attr Tar_active Bool
tar_active = mkAttr Tar_active

---------------------------------------------------------------------------
-- Tar_updated_by Field
---------------------------------------------------------------------------

data Tar_updated_by = Tar_updated_by

instance FieldTag Tar_updated_by where
    fieldName _ = "tar_updated_by"

tar_updated_by :: Attr Tar_updated_by Int
tar_updated_by = mkAttr Tar_updated_by

---------------------------------------------------------------------------
-- Tar_updated Field
---------------------------------------------------------------------------

data Tar_updated = Tar_updated

instance FieldTag Tar_updated where fieldName _ = "tar_updated"

tar_updated :: Attr Tar_updated (Maybe CalendarTime)
tar_updated = mkAttr Tar_updated

---------------------------------------------------------------------------
-- Tar_created Field
---------------------------------------------------------------------------

data Tar_created = Tar_created

instance FieldTag Tar_created where fieldName _ = "tar_created"

tar_created :: Attr Tar_created (Maybe CalendarTime)
tar_created = mkAttr Tar_created
