{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack85 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.THA where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type THA  =
    (RecCons Tha_id Expr (Maybe Int)
     (RecCons Tha_name Expr String
      (RecCons Tha_hot_id Expr Int
       (RecCons Tha_description Expr String
        (RecCons Tha_tot_hab Expr Int
         (RecCons Tha_std_capacity Expr Int
          (RecCons Tha_min_capacity Expr Int
           (RecCons Tha_max_capacity Expr Int
            (RecCons Tha_add_capacity Expr Int
             (RecCons Tha_king_bed Expr Int
              (RecCons Tha_queen_bed Expr Int
               (RecCons Tha_marital_bed Expr Int
                (RecCons Tha_single_bed Expr Int
                 (RecCons Tha_litter_bed Expr Int
                  (RecCons Tha_double_sofa Expr Int
                   (RecCons Tha_single_sofa Expr Int
                    (RecCons Tha_hammock Expr Int
                     (RecCons Tha_fac_wc Expr Bool
                      (RecCons Tha_fac_shower Expr Bool
                       (RecCons Tha_fac_bath Expr Bool
                        (RecCons Tha_fac_hot_water Expr Bool
                         (RecCons Tha_fac_jacuzzi Expr Bool
                          (RecCons Tha_fac_hairdryer Expr Bool
                           (RecCons Tha_fac_aircool Expr Bool
                            (RecCons Tha_fac_heating Expr Bool
                             (RecCons Tha_fac_fan Expr Bool
                              (RecCons Tha_fac_hearth Expr Bool
                               (RecCons Tha_fac_refrigerator Expr Bool
                                (RecCons Tha_fac_minibar Expr Bool
                                 (RecCons Tha_fac_kitchen Expr Bool
                                  (RecCons Tha_fac_daily_clean Expr Bool
                                   (RecCons Tha_fac_tv Expr Bool
                                    (RecCons Tha_fac_tvcable Expr Bool
                                     (RecCons Tha_fac_internet Expr Bool
                                      (RecCons Tha_fac_wifi Expr Bool
                                       (RecCons Tha_fac_phone Expr Bool
                                        (RecCons Tha_fac_smoker Expr Bool
                                         (RecCons Tha_fac_safebox Expr Bool
                                          (RecCons Tha_fac_desk Expr Bool
                                           (RecCons Tha_fac_coffee Expr Bool
                                            (RecCons Tha_other_fac Expr String
                                             (RecCons Tha_status_reg Expr String
                                              (RecCons Tha_updated_by Expr Int
                                               (RecCons Tha_updated Expr (Maybe CalendarTime)
                                                (RecCons Tha_created Expr (Maybe CalendarTime) RecNil)))))))))))))))))))))))))))))))))))))))))))))

type THA _result =
    (RecCons Tha_id ((Maybe Int))
     (RecCons Tha_name (String)
      (RecCons Tha_hot_id (Int)
       (RecCons Tha_description (String)
        (RecCons Tha_tot_hab (Int)
         (RecCons Tha_std_capacity (Int)
          (RecCons Tha_min_capacity (Int)
           (RecCons Tha_max_capacity (Int)
            (RecCons Tha_add_capacity (Int)
             (RecCons Tha_king_bed (Int)
              (RecCons Tha_queen_bed (Int)
               (RecCons Tha_marital_bed (Int)
                (RecCons Tha_single_bed (Int)
                 (RecCons Tha_litter_bed (Int)
                  (RecCons Tha_double_sofa (Int)
                   (RecCons Tha_single_sofa (Int)
                    (RecCons Tha_hammock (Int)
                     (RecCons Tha_fac_wc (Bool)
                      (RecCons Tha_fac_shower (Bool)
                       (RecCons Tha_fac_bath (Bool)
                        (RecCons Tha_fac_hot_water (Bool)
                         (RecCons Tha_fac_jacuzzi (Bool)
                          (RecCons Tha_fac_hairdryer (Bool)
                           (RecCons Tha_fac_aircool (Bool)
                            (RecCons Tha_fac_heating (Bool)
                             (RecCons Tha_fac_fan (Bool)
                              (RecCons Tha_fac_hearth (Bool)
                               (RecCons Tha_fac_refrigerator (Bool)
                                (RecCons Tha_fac_minibar (Bool)
                                 (RecCons Tha_fac_kitchen (Bool)
                                  (RecCons Tha_fac_daily_clean (Bool)
                                   (RecCons Tha_fac_tv (Bool)
                                    (RecCons Tha_fac_tvcable (Bool)
                                     (RecCons Tha_fac_internet (Bool)
                                      (RecCons Tha_fac_wifi (Bool)
                                       (RecCons Tha_fac_phone (Bool)
                                        (RecCons Tha_fac_smoker (Bool)
                                         (RecCons Tha_fac_safebox (Bool)
                                          (RecCons Tha_fac_desk (Bool)
                                           (RecCons Tha_fac_coffee (Bool)
                                            (RecCons Tha_other_fac (String)
                                             (RecCons Tha_status_reg (String)
                                              (RecCons Tha_updated_by (Int)
                                               (RecCons Tha_updated ((Maybe CalendarTime))
                                                (RecCons Tha_created ((Maybe CalendarTime)) RecNil)))))))))))))))))))))))))))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
tHA :: Table THA
tHA = baseTable "THA" $
      hdbMakeEntry Tha_id #
      hdbMakeEntry Tha_name #
      hdbMakeEntry Tha_hot_id #
      hdbMakeEntry Tha_description #
      hdbMakeEntry Tha_tot_hab #
      hdbMakeEntry Tha_std_capacity #
      hdbMakeEntry Tha_min_capacity #
      hdbMakeEntry Tha_max_capacity #
      hdbMakeEntry Tha_add_capacity #
      hdbMakeEntry Tha_king_bed #
      hdbMakeEntry Tha_queen_bed #
      hdbMakeEntry Tha_marital_bed #
      hdbMakeEntry Tha_single_bed #
      hdbMakeEntry Tha_litter_bed #
      hdbMakeEntry Tha_double_sofa #
      hdbMakeEntry Tha_single_sofa #
      hdbMakeEntry Tha_hammock #
      hdbMakeEntry Tha_fac_wc #
      hdbMakeEntry Tha_fac_shower #
      hdbMakeEntry Tha_fac_bath #
      hdbMakeEntry Tha_fac_hot_water #
      hdbMakeEntry Tha_fac_jacuzzi #
      hdbMakeEntry Tha_fac_hairdryer #
      hdbMakeEntry Tha_fac_aircool #
      hdbMakeEntry Tha_fac_heating #
      hdbMakeEntry Tha_fac_fan #
      hdbMakeEntry Tha_fac_hearth #
      hdbMakeEntry Tha_fac_refrigerator #
      hdbMakeEntry Tha_fac_minibar #
      hdbMakeEntry Tha_fac_kitchen #
      hdbMakeEntry Tha_fac_daily_clean #
      hdbMakeEntry Tha_fac_tv #
      hdbMakeEntry Tha_fac_tvcable #
      hdbMakeEntry Tha_fac_internet #
      hdbMakeEntry Tha_fac_wifi #
      hdbMakeEntry Tha_fac_phone #
      hdbMakeEntry Tha_fac_smoker #
      hdbMakeEntry Tha_fac_safebox #
      hdbMakeEntry Tha_fac_desk #
      hdbMakeEntry Tha_fac_coffee #
      hdbMakeEntry Tha_other_fac #
      hdbMakeEntry Tha_status_reg #
      hdbMakeEntry Tha_updated_by #
      hdbMakeEntry Tha_updated #
      hdbMakeEntry Tha_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Tha_id Field
---------------------------------------------------------------------------

data Tha_id = Tha_id

instance FieldTag Tha_id where fieldName _ = "tha_id"

tha_id :: Attr Tha_id (Maybe Int)
tha_id = mkAttr Tha_id

---------------------------------------------------------------------------
-- Tha_name Field
---------------------------------------------------------------------------

data Tha_name = Tha_name

instance FieldTag Tha_name where fieldName _ = "tha_name"

tha_name :: Attr Tha_name String
tha_name = mkAttr Tha_name

---------------------------------------------------------------------------
-- Tha_hot_id Field
---------------------------------------------------------------------------

data Tha_hot_id = Tha_hot_id

instance FieldTag Tha_hot_id where fieldName _ = "tha_hot_id"

tha_hot_id :: Attr Tha_hot_id Int
tha_hot_id = mkAttr Tha_hot_id

---------------------------------------------------------------------------
-- Tha_description Field
---------------------------------------------------------------------------

data Tha_description = Tha_description

instance FieldTag Tha_description where
    fieldName _ = "tha_description"

tha_description :: Attr Tha_description String
tha_description = mkAttr Tha_description

---------------------------------------------------------------------------
-- Tha_tot_hab Field
---------------------------------------------------------------------------

data Tha_tot_hab = Tha_tot_hab

instance FieldTag Tha_tot_hab where fieldName _ = "tha_tot_hab"

tha_tot_hab :: Attr Tha_tot_hab Int
tha_tot_hab = mkAttr Tha_tot_hab

---------------------------------------------------------------------------
-- Tha_std_capacity Field
---------------------------------------------------------------------------

data Tha_std_capacity = Tha_std_capacity

instance FieldTag Tha_std_capacity where
    fieldName _ = "tha_std_capacity"

tha_std_capacity :: Attr Tha_std_capacity Int
tha_std_capacity = mkAttr Tha_std_capacity

---------------------------------------------------------------------------
-- Tha_min_capacity Field
---------------------------------------------------------------------------

data Tha_min_capacity = Tha_min_capacity

instance FieldTag Tha_min_capacity where
    fieldName _ = "tha_min_capacity"

tha_min_capacity :: Attr Tha_min_capacity Int
tha_min_capacity = mkAttr Tha_min_capacity

---------------------------------------------------------------------------
-- Tha_max_capacity Field
---------------------------------------------------------------------------

data Tha_max_capacity = Tha_max_capacity

instance FieldTag Tha_max_capacity where
    fieldName _ = "tha_max_capacity"

tha_max_capacity :: Attr Tha_max_capacity Int
tha_max_capacity = mkAttr Tha_max_capacity

---------------------------------------------------------------------------
-- Tha_add_capacity Field
---------------------------------------------------------------------------

data Tha_add_capacity = Tha_add_capacity

instance FieldTag Tha_add_capacity where
    fieldName _ = "tha_add_capacity"

tha_add_capacity :: Attr Tha_add_capacity Int
tha_add_capacity = mkAttr Tha_add_capacity

---------------------------------------------------------------------------
-- Tha_king_bed Field
---------------------------------------------------------------------------

data Tha_king_bed = Tha_king_bed

instance FieldTag Tha_king_bed where fieldName _ = "tha_king_bed"

tha_king_bed :: Attr Tha_king_bed Int
tha_king_bed = mkAttr Tha_king_bed

---------------------------------------------------------------------------
-- Tha_queen_bed Field
---------------------------------------------------------------------------

data Tha_queen_bed = Tha_queen_bed

instance FieldTag Tha_queen_bed where
    fieldName _ = "tha_queen_bed"

tha_queen_bed :: Attr Tha_queen_bed Int
tha_queen_bed = mkAttr Tha_queen_bed

---------------------------------------------------------------------------
-- Tha_marital_bed Field
---------------------------------------------------------------------------

data Tha_marital_bed = Tha_marital_bed

instance FieldTag Tha_marital_bed where
    fieldName _ = "tha_marital_bed"

tha_marital_bed :: Attr Tha_marital_bed Int
tha_marital_bed = mkAttr Tha_marital_bed

---------------------------------------------------------------------------
-- Tha_single_bed Field
---------------------------------------------------------------------------

data Tha_single_bed = Tha_single_bed

instance FieldTag Tha_single_bed where
    fieldName _ = "tha_single_bed"

tha_single_bed :: Attr Tha_single_bed Int
tha_single_bed = mkAttr Tha_single_bed

---------------------------------------------------------------------------
-- Tha_litter_bed Field
---------------------------------------------------------------------------

data Tha_litter_bed = Tha_litter_bed

instance FieldTag Tha_litter_bed where
    fieldName _ = "tha_litter_bed"

tha_litter_bed :: Attr Tha_litter_bed Int
tha_litter_bed = mkAttr Tha_litter_bed

---------------------------------------------------------------------------
-- Tha_double_sofa Field
---------------------------------------------------------------------------

data Tha_double_sofa = Tha_double_sofa

instance FieldTag Tha_double_sofa where
    fieldName _ = "tha_double_sofa"

tha_double_sofa :: Attr Tha_double_sofa Int
tha_double_sofa = mkAttr Tha_double_sofa

---------------------------------------------------------------------------
-- Tha_single_sofa Field
---------------------------------------------------------------------------

data Tha_single_sofa = Tha_single_sofa

instance FieldTag Tha_single_sofa where
    fieldName _ = "tha_single_sofa"

tha_single_sofa :: Attr Tha_single_sofa Int
tha_single_sofa = mkAttr Tha_single_sofa

---------------------------------------------------------------------------
-- Tha_hammock Field
---------------------------------------------------------------------------

data Tha_hammock = Tha_hammock

instance FieldTag Tha_hammock where fieldName _ = "tha_hammock"

tha_hammock :: Attr Tha_hammock Int
tha_hammock = mkAttr Tha_hammock

---------------------------------------------------------------------------
-- Tha_fac_wc Field
---------------------------------------------------------------------------

data Tha_fac_wc = Tha_fac_wc

instance FieldTag Tha_fac_wc where fieldName _ = "tha_fac_wc"

tha_fac_wc :: Attr Tha_fac_wc Bool
tha_fac_wc = mkAttr Tha_fac_wc

---------------------------------------------------------------------------
-- Tha_fac_shower Field
---------------------------------------------------------------------------

data Tha_fac_shower = Tha_fac_shower

instance FieldTag Tha_fac_shower where
    fieldName _ = "tha_fac_shower"

tha_fac_shower :: Attr Tha_fac_shower Bool
tha_fac_shower = mkAttr Tha_fac_shower

---------------------------------------------------------------------------
-- Tha_fac_bath Field
---------------------------------------------------------------------------

data Tha_fac_bath = Tha_fac_bath

instance FieldTag Tha_fac_bath where fieldName _ = "tha_fac_bath"

tha_fac_bath :: Attr Tha_fac_bath Bool
tha_fac_bath = mkAttr Tha_fac_bath

---------------------------------------------------------------------------
-- Tha_fac_hot_water Field
---------------------------------------------------------------------------

data Tha_fac_hot_water = Tha_fac_hot_water

instance FieldTag Tha_fac_hot_water where
    fieldName _ = "tha_fac_hot_water"

tha_fac_hot_water :: Attr Tha_fac_hot_water Bool
tha_fac_hot_water = mkAttr Tha_fac_hot_water

---------------------------------------------------------------------------
-- Tha_fac_jacuzzi Field
---------------------------------------------------------------------------

data Tha_fac_jacuzzi = Tha_fac_jacuzzi

instance FieldTag Tha_fac_jacuzzi where
    fieldName _ = "tha_fac_jacuzzi"

tha_fac_jacuzzi :: Attr Tha_fac_jacuzzi Bool
tha_fac_jacuzzi = mkAttr Tha_fac_jacuzzi

---------------------------------------------------------------------------
-- Tha_fac_hairdryer Field
---------------------------------------------------------------------------

data Tha_fac_hairdryer = Tha_fac_hairdryer

instance FieldTag Tha_fac_hairdryer where
    fieldName _ = "tha_fac_hairdryer"

tha_fac_hairdryer :: Attr Tha_fac_hairdryer Bool
tha_fac_hairdryer = mkAttr Tha_fac_hairdryer

---------------------------------------------------------------------------
-- Tha_fac_aircool Field
---------------------------------------------------------------------------

data Tha_fac_aircool = Tha_fac_aircool

instance FieldTag Tha_fac_aircool where
    fieldName _ = "tha_fac_aircool"

tha_fac_aircool :: Attr Tha_fac_aircool Bool
tha_fac_aircool = mkAttr Tha_fac_aircool

---------------------------------------------------------------------------
-- Tha_fac_heating Field
---------------------------------------------------------------------------

data Tha_fac_heating = Tha_fac_heating

instance FieldTag Tha_fac_heating where
    fieldName _ = "tha_fac_heating"

tha_fac_heating :: Attr Tha_fac_heating Bool
tha_fac_heating = mkAttr Tha_fac_heating

---------------------------------------------------------------------------
-- Tha_fac_fan Field
---------------------------------------------------------------------------

data Tha_fac_fan = Tha_fac_fan

instance FieldTag Tha_fac_fan where fieldName _ = "tha_fac_fan"

tha_fac_fan :: Attr Tha_fac_fan Bool
tha_fac_fan = mkAttr Tha_fac_fan

---------------------------------------------------------------------------
-- Tha_fac_hearth Field
---------------------------------------------------------------------------

data Tha_fac_hearth = Tha_fac_hearth

instance FieldTag Tha_fac_hearth where
    fieldName _ = "tha_fac_hearth"

tha_fac_hearth :: Attr Tha_fac_hearth Bool
tha_fac_hearth = mkAttr Tha_fac_hearth

---------------------------------------------------------------------------
-- Tha_fac_refrigerator Field
---------------------------------------------------------------------------

data Tha_fac_refrigerator = Tha_fac_refrigerator

instance FieldTag Tha_fac_refrigerator where
    fieldName _ = "tha_fac_refrigerator"

tha_fac_refrigerator :: Attr Tha_fac_refrigerator Bool
tha_fac_refrigerator = mkAttr Tha_fac_refrigerator

---------------------------------------------------------------------------
-- Tha_fac_minibar Field
---------------------------------------------------------------------------

data Tha_fac_minibar = Tha_fac_minibar

instance FieldTag Tha_fac_minibar where
    fieldName _ = "tha_fac_minibar"

tha_fac_minibar :: Attr Tha_fac_minibar Bool
tha_fac_minibar = mkAttr Tha_fac_minibar

---------------------------------------------------------------------------
-- Tha_fac_kitchen Field
---------------------------------------------------------------------------

data Tha_fac_kitchen = Tha_fac_kitchen

instance FieldTag Tha_fac_kitchen where
    fieldName _ = "tha_fac_kitchen"

tha_fac_kitchen :: Attr Tha_fac_kitchen Bool
tha_fac_kitchen = mkAttr Tha_fac_kitchen

---------------------------------------------------------------------------
-- Tha_fac_daily_clean Field
---------------------------------------------------------------------------

data Tha_fac_daily_clean = Tha_fac_daily_clean

instance FieldTag Tha_fac_daily_clean where
    fieldName _ = "tha_fac_daily_clean"

tha_fac_daily_clean :: Attr Tha_fac_daily_clean Bool
tha_fac_daily_clean = mkAttr Tha_fac_daily_clean

---------------------------------------------------------------------------
-- Tha_fac_tv Field
---------------------------------------------------------------------------

data Tha_fac_tv = Tha_fac_tv

instance FieldTag Tha_fac_tv where fieldName _ = "tha_fac_tv"

tha_fac_tv :: Attr Tha_fac_tv Bool
tha_fac_tv = mkAttr Tha_fac_tv

---------------------------------------------------------------------------
-- Tha_fac_tvcable Field
---------------------------------------------------------------------------

data Tha_fac_tvcable = Tha_fac_tvcable

instance FieldTag Tha_fac_tvcable where
    fieldName _ = "tha_fac_tvcable"

tha_fac_tvcable :: Attr Tha_fac_tvcable Bool
tha_fac_tvcable = mkAttr Tha_fac_tvcable

---------------------------------------------------------------------------
-- Tha_fac_internet Field
---------------------------------------------------------------------------

data Tha_fac_internet = Tha_fac_internet

instance FieldTag Tha_fac_internet where
    fieldName _ = "tha_fac_internet"

tha_fac_internet :: Attr Tha_fac_internet Bool
tha_fac_internet = mkAttr Tha_fac_internet

---------------------------------------------------------------------------
-- Tha_fac_wifi Field
---------------------------------------------------------------------------

data Tha_fac_wifi = Tha_fac_wifi

instance FieldTag Tha_fac_wifi where fieldName _ = "tha_fac_wifi"

tha_fac_wifi :: Attr Tha_fac_wifi Bool
tha_fac_wifi = mkAttr Tha_fac_wifi

---------------------------------------------------------------------------
-- Tha_fac_phone Field
---------------------------------------------------------------------------

data Tha_fac_phone = Tha_fac_phone

instance FieldTag Tha_fac_phone where
    fieldName _ = "tha_fac_phone"

tha_fac_phone :: Attr Tha_fac_phone Bool
tha_fac_phone = mkAttr Tha_fac_phone

---------------------------------------------------------------------------
-- Tha_fac_smoker Field
---------------------------------------------------------------------------

data Tha_fac_smoker = Tha_fac_smoker

instance FieldTag Tha_fac_smoker where
    fieldName _ = "tha_fac_smoker"

tha_fac_smoker :: Attr Tha_fac_smoker Bool
tha_fac_smoker = mkAttr Tha_fac_smoker

---------------------------------------------------------------------------
-- Tha_fac_safebox Field
---------------------------------------------------------------------------

data Tha_fac_safebox = Tha_fac_safebox

instance FieldTag Tha_fac_safebox where
    fieldName _ = "tha_fac_safebox"

tha_fac_safebox :: Attr Tha_fac_safebox Bool
tha_fac_safebox = mkAttr Tha_fac_safebox

---------------------------------------------------------------------------
-- Tha_fac_desk Field
---------------------------------------------------------------------------

data Tha_fac_desk = Tha_fac_desk

instance FieldTag Tha_fac_desk where fieldName _ = "tha_fac_desk"

tha_fac_desk :: Attr Tha_fac_desk Bool
tha_fac_desk = mkAttr Tha_fac_desk

---------------------------------------------------------------------------
-- Tha_fac_coffee Field
---------------------------------------------------------------------------

data Tha_fac_coffee = Tha_fac_coffee

instance FieldTag Tha_fac_coffee where
    fieldName _ = "tha_fac_coffee"

tha_fac_coffee :: Attr Tha_fac_coffee Bool
tha_fac_coffee = mkAttr Tha_fac_coffee

---------------------------------------------------------------------------
-- Tha_other_fac Field
---------------------------------------------------------------------------

data Tha_other_fac = Tha_other_fac

instance FieldTag Tha_other_fac where
    fieldName _ = "tha_other_fac"

tha_other_fac :: Attr Tha_other_fac String
tha_other_fac = mkAttr Tha_other_fac

---------------------------------------------------------------------------
-- Tha_status_reg Field
---------------------------------------------------------------------------

data Tha_status_reg = Tha_status_reg

instance FieldTag Tha_status_reg where
    fieldName _ = "tha_status_reg"

tha_status_reg :: Attr Tha_status_reg String
tha_status_reg = mkAttr Tha_status_reg

---------------------------------------------------------------------------
-- Tha_updated_by Field
---------------------------------------------------------------------------

data Tha_updated_by = Tha_updated_by

instance FieldTag Tha_updated_by where
    fieldName _ = "tha_updated_by"

tha_updated_by :: Attr Tha_updated_by Int
tha_updated_by = mkAttr Tha_updated_by

---------------------------------------------------------------------------
-- Tha_updated Field
---------------------------------------------------------------------------

data Tha_updated = Tha_updated

instance FieldTag Tha_updated where fieldName _ = "tha_updated"

tha_updated :: Attr Tha_updated (Maybe CalendarTime)
tha_updated = mkAttr Tha_updated

---------------------------------------------------------------------------
-- Tha_created Field
---------------------------------------------------------------------------

data Tha_created = Tha_created

instance FieldTag Tha_created where fieldName _ = "tha_created"

tha_created :: Attr Tha_created (Maybe CalendarTime)
tha_created = mkAttr Tha_created
