{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack63 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.TPR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type TPR  =
    (RecCons Tpr_id Expr (Maybe Int)
     (RecCons Tpr_name Expr String
      (RecCons Tpr_year Expr Int
       (RecCons Tpr_description Expr String
        (RecCons Tpr_hot_id Expr Int
         (RecCons Tpr_restriction Expr String
          (RecCons Tpr_min_nights Expr (Maybe Int)
           (RecCons Tpr_data_5 Expr String
            (RecCons Tpr_data_6 Expr String
             (RecCons Tpr_data_7 Expr String
              (RecCons Tpr_data_8 Expr String
               (RecCons Tpr_data_9 Expr String
                (RecCons Tpr_data_10 Expr String
                 (RecCons Tpr_data_11 Expr String
                  (RecCons Tpr_data_12 Expr String
                   (RecCons Tpr_data_1 Expr String
                    (RecCons Tpr_data_2 Expr String
                     (RecCons Tpr_data_3 Expr String
                      (RecCons Tpr_data_4 Expr String
                       (RecCons Tpr_status_reg Expr String
                        (RecCons Tpr_updated_by Expr Int
                         (RecCons Tpr_updated Expr (Maybe CalendarTime)
                          (RecCons Tpr_created Expr (Maybe CalendarTime) RecNil)))))))))))))))))))))))

type TPR _result =
    (RecCons Tpr_id ((Maybe Int))
     (RecCons Tpr_name (String)
      (RecCons Tpr_year (Int)
       (RecCons Tpr_description (String)
        (RecCons Tpr_hot_id (Int)
         (RecCons Tpr_restriction (String)
          (RecCons Tpr_min_nights ((Maybe Int))
           (RecCons Tpr_data_5 (String)
            (RecCons Tpr_data_6 (String)
             (RecCons Tpr_data_7 (String)
              (RecCons Tpr_data_8 (String)
               (RecCons Tpr_data_9 (String)
                (RecCons Tpr_data_10 (String)
                 (RecCons Tpr_data_11 (String)
                  (RecCons Tpr_data_12 (String)
                   (RecCons Tpr_data_1 (String)
                    (RecCons Tpr_data_2 (String)
                     (RecCons Tpr_data_3 (String)
                      (RecCons Tpr_data_4 (String)
                       (RecCons Tpr_status_reg (String)
                        (RecCons Tpr_updated_by (Int)
                         (RecCons Tpr_updated ((Maybe CalendarTime))
                          (RecCons Tpr_created ((Maybe CalendarTime)) RecNil)))))))))))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
tPR :: Table TPR
tPR = baseTable "TPR" $
      hdbMakeEntry Tpr_id #
      hdbMakeEntry Tpr_name #
      hdbMakeEntry Tpr_year #
      hdbMakeEntry Tpr_description #
      hdbMakeEntry Tpr_hot_id #
      hdbMakeEntry Tpr_restriction #
      hdbMakeEntry Tpr_min_nights #
      hdbMakeEntry Tpr_data_5 #
      hdbMakeEntry Tpr_data_6 #
      hdbMakeEntry Tpr_data_7 #
      hdbMakeEntry Tpr_data_8 #
      hdbMakeEntry Tpr_data_9 #
      hdbMakeEntry Tpr_data_10 #
      hdbMakeEntry Tpr_data_11 #
      hdbMakeEntry Tpr_data_12 #
      hdbMakeEntry Tpr_data_1 #
      hdbMakeEntry Tpr_data_2 #
      hdbMakeEntry Tpr_data_3 #
      hdbMakeEntry Tpr_data_4 #
      hdbMakeEntry Tpr_status_reg #
      hdbMakeEntry Tpr_updated_by #
      hdbMakeEntry Tpr_updated #
      hdbMakeEntry Tpr_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Tpr_id Field
---------------------------------------------------------------------------

data Tpr_id = Tpr_id

instance FieldTag Tpr_id where fieldName _ = "tpr_id"

tpr_id :: Attr Tpr_id (Maybe Int)
tpr_id = mkAttr Tpr_id

---------------------------------------------------------------------------
-- Tpr_name Field
---------------------------------------------------------------------------

data Tpr_name = Tpr_name

instance FieldTag Tpr_name where fieldName _ = "tpr_name"

tpr_name :: Attr Tpr_name String
tpr_name = mkAttr Tpr_name

---------------------------------------------------------------------------
-- Tpr_year Field
---------------------------------------------------------------------------

data Tpr_year = Tpr_year

instance FieldTag Tpr_year where fieldName _ = "tpr_year"

tpr_year :: Attr Tpr_year Int
tpr_year = mkAttr Tpr_year

---------------------------------------------------------------------------
-- Tpr_description Field
---------------------------------------------------------------------------

data Tpr_description = Tpr_description

instance FieldTag Tpr_description where
    fieldName _ = "tpr_description"

tpr_description :: Attr Tpr_description String
tpr_description = mkAttr Tpr_description

---------------------------------------------------------------------------
-- Tpr_hot_id Field
---------------------------------------------------------------------------

data Tpr_hot_id = Tpr_hot_id

instance FieldTag Tpr_hot_id where fieldName _ = "tpr_hot_id"

tpr_hot_id :: Attr Tpr_hot_id Int
tpr_hot_id = mkAttr Tpr_hot_id

---------------------------------------------------------------------------
-- Tpr_restriction Field
---------------------------------------------------------------------------

data Tpr_restriction = Tpr_restriction

instance FieldTag Tpr_restriction where
    fieldName _ = "tpr_restriction"

tpr_restriction :: Attr Tpr_restriction String
tpr_restriction = mkAttr Tpr_restriction

---------------------------------------------------------------------------
-- Tpr_min_nights Field
---------------------------------------------------------------------------

data Tpr_min_nights = Tpr_min_nights

instance FieldTag Tpr_min_nights where
    fieldName _ = "tpr_min_nights"

tpr_min_nights :: Attr Tpr_min_nights (Maybe Int)
tpr_min_nights = mkAttr Tpr_min_nights

---------------------------------------------------------------------------
-- Tpr_data_5 Field
---------------------------------------------------------------------------

data Tpr_data_5 = Tpr_data_5

instance FieldTag Tpr_data_5 where fieldName _ = "tpr_data_5"

tpr_data_5 :: Attr Tpr_data_5 String
tpr_data_5 = mkAttr Tpr_data_5

---------------------------------------------------------------------------
-- Tpr_data_6 Field
---------------------------------------------------------------------------

data Tpr_data_6 = Tpr_data_6

instance FieldTag Tpr_data_6 where fieldName _ = "tpr_data_6"

tpr_data_6 :: Attr Tpr_data_6 String
tpr_data_6 = mkAttr Tpr_data_6

---------------------------------------------------------------------------
-- Tpr_data_7 Field
---------------------------------------------------------------------------

data Tpr_data_7 = Tpr_data_7

instance FieldTag Tpr_data_7 where fieldName _ = "tpr_data_7"

tpr_data_7 :: Attr Tpr_data_7 String
tpr_data_7 = mkAttr Tpr_data_7

---------------------------------------------------------------------------
-- Tpr_data_8 Field
---------------------------------------------------------------------------

data Tpr_data_8 = Tpr_data_8

instance FieldTag Tpr_data_8 where fieldName _ = "tpr_data_8"

tpr_data_8 :: Attr Tpr_data_8 String
tpr_data_8 = mkAttr Tpr_data_8

---------------------------------------------------------------------------
-- Tpr_data_9 Field
---------------------------------------------------------------------------

data Tpr_data_9 = Tpr_data_9

instance FieldTag Tpr_data_9 where fieldName _ = "tpr_data_9"

tpr_data_9 :: Attr Tpr_data_9 String
tpr_data_9 = mkAttr Tpr_data_9

---------------------------------------------------------------------------
-- Tpr_data_10 Field
---------------------------------------------------------------------------

data Tpr_data_10 = Tpr_data_10

instance FieldTag Tpr_data_10 where fieldName _ = "tpr_data_10"

tpr_data_10 :: Attr Tpr_data_10 String
tpr_data_10 = mkAttr Tpr_data_10

---------------------------------------------------------------------------
-- Tpr_data_11 Field
---------------------------------------------------------------------------

data Tpr_data_11 = Tpr_data_11

instance FieldTag Tpr_data_11 where fieldName _ = "tpr_data_11"

tpr_data_11 :: Attr Tpr_data_11 String
tpr_data_11 = mkAttr Tpr_data_11

---------------------------------------------------------------------------
-- Tpr_data_12 Field
---------------------------------------------------------------------------

data Tpr_data_12 = Tpr_data_12

instance FieldTag Tpr_data_12 where fieldName _ = "tpr_data_12"

tpr_data_12 :: Attr Tpr_data_12 String
tpr_data_12 = mkAttr Tpr_data_12

---------------------------------------------------------------------------
-- Tpr_data_1 Field
---------------------------------------------------------------------------

data Tpr_data_1 = Tpr_data_1

instance FieldTag Tpr_data_1 where fieldName _ = "tpr_data_1"

tpr_data_1 :: Attr Tpr_data_1 String
tpr_data_1 = mkAttr Tpr_data_1

---------------------------------------------------------------------------
-- Tpr_data_2 Field
---------------------------------------------------------------------------

data Tpr_data_2 = Tpr_data_2

instance FieldTag Tpr_data_2 where fieldName _ = "tpr_data_2"

tpr_data_2 :: Attr Tpr_data_2 String
tpr_data_2 = mkAttr Tpr_data_2

---------------------------------------------------------------------------
-- Tpr_data_3 Field
---------------------------------------------------------------------------

data Tpr_data_3 = Tpr_data_3

instance FieldTag Tpr_data_3 where fieldName _ = "tpr_data_3"

tpr_data_3 :: Attr Tpr_data_3 String
tpr_data_3 = mkAttr Tpr_data_3

---------------------------------------------------------------------------
-- Tpr_data_4 Field
---------------------------------------------------------------------------

data Tpr_data_4 = Tpr_data_4

instance FieldTag Tpr_data_4 where fieldName _ = "tpr_data_4"

tpr_data_4 :: Attr Tpr_data_4 String
tpr_data_4 = mkAttr Tpr_data_4

---------------------------------------------------------------------------
-- Tpr_status_reg Field
---------------------------------------------------------------------------

data Tpr_status_reg = Tpr_status_reg

instance FieldTag Tpr_status_reg where
    fieldName _ = "tpr_status_reg"

tpr_status_reg :: Attr Tpr_status_reg String
tpr_status_reg = mkAttr Tpr_status_reg

---------------------------------------------------------------------------
-- Tpr_updated_by Field
---------------------------------------------------------------------------

data Tpr_updated_by = Tpr_updated_by

instance FieldTag Tpr_updated_by where
    fieldName _ = "tpr_updated_by"

tpr_updated_by :: Attr Tpr_updated_by Int
tpr_updated_by = mkAttr Tpr_updated_by

---------------------------------------------------------------------------
-- Tpr_updated Field
---------------------------------------------------------------------------

data Tpr_updated = Tpr_updated

instance FieldTag Tpr_updated where fieldName _ = "tpr_updated"

tpr_updated :: Attr Tpr_updated (Maybe CalendarTime)
tpr_updated = mkAttr Tpr_updated

---------------------------------------------------------------------------
-- Tpr_created Field
---------------------------------------------------------------------------

data Tpr_created = Tpr_created

instance FieldTag Tpr_created where fieldName _ = "tpr_created"

tpr_created :: Attr Tpr_created (Maybe CalendarTime)
tpr_created = mkAttr Tpr_created
