{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack48 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.TRT where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type TRT  =
    (RecCons Trt_id Expr (Maybe Int)
     (RecCons Trt_field_name Expr String
      (RecCons Trt_row_id Expr Int
       (RecCons Trt_lang Expr String
        (RecCons Trt_text Expr String
         (RecCons Trt_updated_by Expr Int
          (RecCons Trt_updated Expr (Maybe CalendarTime)
           (RecCons Trt_created Expr (Maybe CalendarTime) RecNil))))))))

type TRT _result =
    (RecCons Trt_id ((Maybe Int))
     (RecCons Trt_field_name (String)
      (RecCons Trt_row_id (Int)
       (RecCons Trt_lang (String)
        (RecCons Trt_text (String)
         (RecCons Trt_updated_by (Int)
          (RecCons Trt_updated ((Maybe CalendarTime))
           (RecCons Trt_created ((Maybe CalendarTime)) RecNil))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
tRT :: Table TRT
tRT = baseTable "TRT" $
      hdbMakeEntry Trt_id #
      hdbMakeEntry Trt_field_name #
      hdbMakeEntry Trt_row_id #
      hdbMakeEntry Trt_lang #
      hdbMakeEntry Trt_text #
      hdbMakeEntry Trt_updated_by #
      hdbMakeEntry Trt_updated #
      hdbMakeEntry Trt_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Trt_id Field
---------------------------------------------------------------------------

data Trt_id = Trt_id

instance FieldTag Trt_id where fieldName _ = "trt_id"

trt_id :: Attr Trt_id (Maybe Int)
trt_id = mkAttr Trt_id

---------------------------------------------------------------------------
-- Trt_field_name Field
---------------------------------------------------------------------------

data Trt_field_name = Trt_field_name

instance FieldTag Trt_field_name where
    fieldName _ = "trt_field_name"

trt_field_name :: Attr Trt_field_name String
trt_field_name = mkAttr Trt_field_name

---------------------------------------------------------------------------
-- Trt_row_id Field
---------------------------------------------------------------------------

data Trt_row_id = Trt_row_id

instance FieldTag Trt_row_id where fieldName _ = "trt_row_id"

trt_row_id :: Attr Trt_row_id Int
trt_row_id = mkAttr Trt_row_id

---------------------------------------------------------------------------
-- Trt_lang Field
---------------------------------------------------------------------------

data Trt_lang = Trt_lang

instance FieldTag Trt_lang where fieldName _ = "trt_lang"

trt_lang :: Attr Trt_lang String
trt_lang = mkAttr Trt_lang

---------------------------------------------------------------------------
-- Trt_text Field
---------------------------------------------------------------------------

data Trt_text = Trt_text

instance FieldTag Trt_text where fieldName _ = "trt_text"

trt_text :: Attr Trt_text String
trt_text = mkAttr Trt_text

---------------------------------------------------------------------------
-- Trt_updated_by Field
---------------------------------------------------------------------------

data Trt_updated_by = Trt_updated_by

instance FieldTag Trt_updated_by where
    fieldName _ = "trt_updated_by"

trt_updated_by :: Attr Trt_updated_by Int
trt_updated_by = mkAttr Trt_updated_by

---------------------------------------------------------------------------
-- Trt_updated Field
---------------------------------------------------------------------------

data Trt_updated = Trt_updated

instance FieldTag Trt_updated where fieldName _ = "trt_updated"

trt_updated :: Attr Trt_updated (Maybe CalendarTime)
trt_updated = mkAttr Trt_updated

---------------------------------------------------------------------------
-- Trt_created Field
---------------------------------------------------------------------------

data Trt_created = Trt_created

instance FieldTag Trt_created where fieldName _ = "trt_created"

trt_created :: Attr Trt_created (Maybe CalendarTime)
trt_created = mkAttr Trt_created
