{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack55 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database.Definition.USR where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type USR  =
    (RecCons Usr_id Expr (Maybe Int)
     (RecCons Usr_fullname Expr (Maybe String)
      (RecCons Usr_name Expr (Maybe String)
       (RecCons Usr_lastname Expr (Maybe String)
        (RecCons Usr_phone Expr (Maybe String)
         (RecCons Usr_cellphone Expr (Maybe String)
          (RecCons Usr_email Expr String
           (RecCons Usr_password Expr String
            (RecCons Usr_activation_pin Expr String
             (RecCons Usr_valid_hosts Expr String
              (RecCons Usr_session_life Expr Int
               (RecCons Usr_status_reg Expr String
                (RecCons Usr_updated_by Expr Int
                 (RecCons Usr_updated Expr (Maybe CalendarTime)
                  (RecCons Usr_created Expr (Maybe CalendarTime) RecNil)))))))))))))))

type USR _result =
    (RecCons Usr_id ((Maybe Int))
     (RecCons Usr_fullname ((Maybe String))
      (RecCons Usr_name ((Maybe String))
       (RecCons Usr_lastname ((Maybe String))
        (RecCons Usr_phone ((Maybe String))
         (RecCons Usr_cellphone ((Maybe String))
          (RecCons Usr_email (String)
           (RecCons Usr_password (String)
            (RecCons Usr_activation_pin (String)
             (RecCons Usr_valid_hosts (String)
              (RecCons Usr_session_life (Int)
               (RecCons Usr_status_reg (String)
                (RecCons Usr_updated_by (Int)
                 (RecCons Usr_updated ((Maybe CalendarTime))
                  (RecCons Usr_created ((Maybe CalendarTime)) RecNil)))))))))))))))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
uSR :: Table USR
uSR = baseTable "USR" $
      hdbMakeEntry Usr_id #
      hdbMakeEntry Usr_fullname #
      hdbMakeEntry Usr_name #
      hdbMakeEntry Usr_lastname #
      hdbMakeEntry Usr_phone #
      hdbMakeEntry Usr_cellphone #
      hdbMakeEntry Usr_email #
      hdbMakeEntry Usr_password #
      hdbMakeEntry Usr_activation_pin #
      hdbMakeEntry Usr_valid_hosts #
      hdbMakeEntry Usr_session_life #
      hdbMakeEntry Usr_status_reg #
      hdbMakeEntry Usr_updated_by #
      hdbMakeEntry Usr_updated #
      hdbMakeEntry Usr_created

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Usr_id Field
---------------------------------------------------------------------------

data Usr_id = Usr_id

instance FieldTag Usr_id where fieldName _ = "usr_id"

usr_id :: Attr Usr_id (Maybe Int)
usr_id = mkAttr Usr_id

---------------------------------------------------------------------------
-- Usr_fullname Field
---------------------------------------------------------------------------

data Usr_fullname = Usr_fullname

instance FieldTag Usr_fullname where fieldName _ = "usr_fullname"

usr_fullname :: Attr Usr_fullname (Maybe String)
usr_fullname = mkAttr Usr_fullname

---------------------------------------------------------------------------
-- Usr_name Field
---------------------------------------------------------------------------

data Usr_name = Usr_name

instance FieldTag Usr_name where fieldName _ = "usr_name"

usr_name :: Attr Usr_name (Maybe String)
usr_name = mkAttr Usr_name

---------------------------------------------------------------------------
-- Usr_lastname Field
---------------------------------------------------------------------------

data Usr_lastname = Usr_lastname

instance FieldTag Usr_lastname where fieldName _ = "usr_lastname"

usr_lastname :: Attr Usr_lastname (Maybe String)
usr_lastname = mkAttr Usr_lastname

---------------------------------------------------------------------------
-- Usr_phone Field
---------------------------------------------------------------------------

data Usr_phone = Usr_phone

instance FieldTag Usr_phone where fieldName _ = "usr_phone"

usr_phone :: Attr Usr_phone (Maybe String)
usr_phone = mkAttr Usr_phone

---------------------------------------------------------------------------
-- Usr_cellphone Field
---------------------------------------------------------------------------

data Usr_cellphone = Usr_cellphone

instance FieldTag Usr_cellphone where
    fieldName _ = "usr_cellphone"

usr_cellphone :: Attr Usr_cellphone (Maybe String)
usr_cellphone = mkAttr Usr_cellphone

---------------------------------------------------------------------------
-- Usr_email Field
---------------------------------------------------------------------------

data Usr_email = Usr_email

instance FieldTag Usr_email where fieldName _ = "usr_email"

usr_email :: Attr Usr_email String
usr_email = mkAttr Usr_email

---------------------------------------------------------------------------
-- Usr_password Field
---------------------------------------------------------------------------

data Usr_password = Usr_password

instance FieldTag Usr_password where fieldName _ = "usr_password"

usr_password :: Attr Usr_password String
usr_password = mkAttr Usr_password

---------------------------------------------------------------------------
-- Usr_activation_pin Field
---------------------------------------------------------------------------

data Usr_activation_pin = Usr_activation_pin

instance FieldTag Usr_activation_pin where
    fieldName _ = "usr_activation_pin"

usr_activation_pin :: Attr Usr_activation_pin String
usr_activation_pin = mkAttr Usr_activation_pin

---------------------------------------------------------------------------
-- Usr_valid_hosts Field
---------------------------------------------------------------------------

data Usr_valid_hosts = Usr_valid_hosts

instance FieldTag Usr_valid_hosts where
    fieldName _ = "usr_valid_hosts"

usr_valid_hosts :: Attr Usr_valid_hosts String
usr_valid_hosts = mkAttr Usr_valid_hosts

---------------------------------------------------------------------------
-- Usr_session_life Field
---------------------------------------------------------------------------

data Usr_session_life = Usr_session_life

instance FieldTag Usr_session_life where
    fieldName _ = "usr_session_life"

usr_session_life :: Attr Usr_session_life Int
usr_session_life = mkAttr Usr_session_life

---------------------------------------------------------------------------
-- Usr_status_reg Field
---------------------------------------------------------------------------

data Usr_status_reg = Usr_status_reg

instance FieldTag Usr_status_reg where
    fieldName _ = "usr_status_reg"

usr_status_reg :: Attr Usr_status_reg String
usr_status_reg = mkAttr Usr_status_reg

---------------------------------------------------------------------------
-- Usr_updated_by Field
---------------------------------------------------------------------------

data Usr_updated_by = Usr_updated_by

instance FieldTag Usr_updated_by where
    fieldName _ = "usr_updated_by"

usr_updated_by :: Attr Usr_updated_by Int
usr_updated_by = mkAttr Usr_updated_by

---------------------------------------------------------------------------
-- Usr_updated Field
---------------------------------------------------------------------------

data Usr_updated = Usr_updated

instance FieldTag Usr_updated where fieldName _ = "usr_updated"

usr_updated :: Attr Usr_updated (Maybe CalendarTime)
usr_updated = mkAttr Usr_updated

---------------------------------------------------------------------------
-- Usr_created Field
---------------------------------------------------------------------------

data Usr_created = Usr_created

instance FieldTag Usr_created where fieldName _ = "usr_created"

usr_created :: Attr Usr_created (Maybe CalendarTime)
usr_created = mkAttr Usr_created
