{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.9.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Season_Client(get,getInfo) where
import Data.IORef
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (.), (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Hashable
import Data.Int
import Data.Text.Lazy ( Text )
import qualified Data.Text.Lazy as TL
import Data.Typeable ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector

import Thrift
import Thrift.Types ()


import TPR_Types
import Season
seqid = newIORef 0
get (ip,op) arg_hot_id arg_dateFrom arg_dateTo = do
  send_get op arg_hot_id arg_dateFrom arg_dateTo
  recv_get ip
send_get op arg_hot_id arg_dateFrom arg_dateTo = do
  seq <- seqid
  seqn <- readIORef seq
  writeMessageBegin op ("get", M_CALL, seqn)
  write_Get_args op (Get_args{f_Get_args_hot_id=Just arg_hot_id,f_Get_args_dateFrom=Just arg_dateFrom,f_Get_args_dateTo=Just arg_dateTo})
  writeMessageEnd op
  tFlush (getTransport op)
recv_get ip = do
  (fname, mtype, rseqid) <- readMessageBegin ip
  if mtype == M_EXCEPTION then do
    x <- readAppExn ip
    readMessageEnd ip
    throw x
    else return ()
  res <- read_Get_result ip
  readMessageEnd ip
  case f_Get_result_success res of
    Just v -> return v
    Nothing -> do
      throw (AppExn AE_MISSING_RESULT "get failed: unknown result")
getInfo (ip,op) arg_hot_id arg_dateFrom arg_dateTo = do
  send_getInfo op arg_hot_id arg_dateFrom arg_dateTo
  recv_getInfo ip
send_getInfo op arg_hot_id arg_dateFrom arg_dateTo = do
  seq <- seqid
  seqn <- readIORef seq
  writeMessageBegin op ("getInfo", M_CALL, seqn)
  write_GetInfo_args op (GetInfo_args{f_GetInfo_args_hot_id=Just arg_hot_id,f_GetInfo_args_dateFrom=Just arg_dateFrom,f_GetInfo_args_dateTo=Just arg_dateTo})
  writeMessageEnd op
  tFlush (getTransport op)
recv_getInfo ip = do
  (fname, mtype, rseqid) <- readMessageBegin ip
  if mtype == M_EXCEPTION then do
    x <- readAppExn ip
    readMessageEnd ip
    throw x
    else return ()
  res <- read_GetInfo_result ip
  readMessageEnd ip
  case f_GetInfo_result_success res of
    Just v -> return v
    Nothing -> do
      throw (AppExn AE_MISSING_RESULT "getInfo failed: unknown result")
