{-# LANGUAGE DeriveDataTypeable #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.8.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module TPR_Types where
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Int
import Data.Typeable ( Typeable )
import qualified Data.Map as Map
import qualified Data.Set as Set

import Thrift


data Status_reg = Active|Inactive|Stored|Deleted  deriving (Show,Eq, Typeable, Ord)
instance Enum Status_reg where
  fromEnum t = case t of
    Active -> 0
    Inactive -> 1
    Stored -> 2
    Deleted -> 3
  toEnum t = case t of
    0 -> Active
    1 -> Inactive
    2 -> Stored
    3 -> Deleted
    _ -> throw ThriftException
data TPR = TPR{f_TPR_tpr_id :: Maybe Int32,f_TPR_tpr_name :: Maybe Int32,f_TPR_tpr_year :: Maybe Int32,f_TPR_tpr_description :: Maybe Int32,f_TPR_tpr_hot_id :: Maybe Int32,f_TPR_tpr_restriction :: Maybe Int32,f_TPR_tpr_min_nights :: Maybe Int32,f_TPR_tpr_data_5 :: Maybe String,f_TPR_tpr_data_6 :: Maybe String,f_TPR_tpr_data_7 :: Maybe String,f_TPR_tpr_data_8 :: Maybe String,f_TPR_tpr_data_9 :: Maybe String,f_TPR_tpr_data_10 :: Maybe String,f_TPR_tpr_data_11 :: Maybe String,f_TPR_tpr_data_12 :: Maybe String,f_TPR_tpr_data_1 :: Maybe String,f_TPR_tpr_data_2 :: Maybe String,f_TPR_tpr_data_3 :: Maybe String,f_TPR_tpr_data_4 :: Maybe String,f_TPR_tpr_status_reg :: Maybe Status_reg,f_TPR_tpr_updated_by :: Maybe Int32,f_TPR_tpr_updated :: Maybe String,f_TPR_tpr_created :: Maybe String} deriving (Show,Eq,Ord,Typeable)
write_TPR oprot record = do
  writeStructBegin oprot "TPR"
  case f_TPR_tpr_id record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_id",T_I32,1)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_name record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_name",T_I32,2)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_year record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_year",T_I32,3)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_description record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_description",T_I32,4)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_hot_id record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_hot_id",T_I32,5)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_restriction record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_restriction",T_I32,6)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_min_nights record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_min_nights",T_I32,7)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_5 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_5",T_STRING,8)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_6 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_6",T_STRING,9)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_7 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_7",T_STRING,10)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_8 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_8",T_STRING,11)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_9 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_9",T_STRING,12)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_10 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_10",T_STRING,13)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_11 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_11",T_STRING,14)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_12 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_12",T_STRING,15)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_1 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_1",T_STRING,16)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_2 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_2",T_STRING,17)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_3 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_3",T_STRING,18)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_data_4 record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_data_4",T_STRING,19)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_status_reg record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_status_reg",T_I32,20)
    writeI32 oprot (fromIntegral $ fromEnum _v)
    writeFieldEnd oprot}
  case f_TPR_tpr_updated_by record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_updated_by",T_I32,21)
    writeI32 oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_updated record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_updated",T_STRING,22)
    writeString oprot _v
    writeFieldEnd oprot}
  case f_TPR_tpr_created record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("tpr_created",T_STRING,23)
    writeString oprot _v
    writeFieldEnd oprot}
  writeFieldStop oprot
  writeStructEnd oprot
read_TPR_fields iprot record = do
  (_,_t3,_id4) <- readFieldBegin iprot
  if _t3 == T_STOP then return record else
    case _id4 of 
      1 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_id=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      2 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_name=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      3 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_year=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      4 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_description=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      5 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_hot_id=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      6 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_restriction=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      7 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_min_nights=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      8 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_5=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      9 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_6=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      10 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_7=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      11 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_8=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      12 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_9=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      13 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_10=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      14 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_11=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      15 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_12=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      16 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_1=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      17 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_2=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      18 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_3=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      19 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_data_4=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      20 -> if _t3 == T_I32 then do
        s <- (do {i <- readI32 iprot; return $ toEnum $ fromIntegral i})
        read_TPR_fields iprot record{f_TPR_tpr_status_reg=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      21 -> if _t3 == T_I32 then do
        s <- readI32 iprot
        read_TPR_fields iprot record{f_TPR_tpr_updated_by=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      22 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_updated=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      23 -> if _t3 == T_STRING then do
        s <- readString iprot
        read_TPR_fields iprot record{f_TPR_tpr_created=Just s}
        else do
          skip iprot _t3
          read_TPR_fields iprot record
      _ -> do
        skip iprot _t3
        readFieldEnd iprot
        read_TPR_fields iprot record
read_TPR iprot = do
  _ <- readStructBegin iprot
  record <- read_TPR_fields iprot (TPR{f_TPR_tpr_id=Nothing,f_TPR_tpr_name=Nothing,f_TPR_tpr_year=Nothing,f_TPR_tpr_description=Nothing,f_TPR_tpr_hot_id=Nothing,f_TPR_tpr_restriction=Nothing,f_TPR_tpr_min_nights=Nothing,f_TPR_tpr_data_5=Nothing,f_TPR_tpr_data_6=Nothing,f_TPR_tpr_data_7=Nothing,f_TPR_tpr_data_8=Nothing,f_TPR_tpr_data_9=Nothing,f_TPR_tpr_data_10=Nothing,f_TPR_tpr_data_11=Nothing,f_TPR_tpr_data_12=Nothing,f_TPR_tpr_data_1=Nothing,f_TPR_tpr_data_2=Nothing,f_TPR_tpr_data_3=Nothing,f_TPR_tpr_data_4=Nothing,f_TPR_tpr_status_reg=Nothing,f_TPR_tpr_updated_by=Nothing,f_TPR_tpr_updated=Nothing,f_TPR_tpr_created=Nothing})
  readStructEnd iprot
  return record
