<?php
   
/* ----------------------------------------------
 * Calculator client
 *
 * A very simple example of interaction with
 * a calculator server application whose actions
 * are facilitated by thrift.  Both the client
 * and server negotiate on the common interface
 * defined by calculator.thrift
 *
 *@author Ian Chan
 *@date May 10, 2010
 * ----------------------------------------------
 */

// Load up all the thrift stuff
require_once 'Thrift.php';
require_once 'protocol/TBinaryProtocol.php';
require_once 'transport/TSocket.php';
require_once 'transport/TBufferedTransport.php';
 
// Load the package that we autogenerated for this tutorial
require_once 'test_types.php';
 
// Several things might go wrong
try {
    // Create a thrift connection (Boiler plate)
    $socket = new TSocket('localhost', '4390');
    $transport = new TBufferedTransport($socket);
    $protocol = new TBinaryProtocol($transport);
 
    // Create a calculator client
    $work = new Work(array(
        'num1' => 1,
        'num2' => 12345,
        'op' => 1,
        'comment' => "Foo!"
    ));
 
    // Open up the connection
    $transport->open();
    print_r($work);
    $work->write($protocol);
    $transport->flush();
    $work->read($protocol);
    print_r($work);
 
    // And finally, we close the thrift connection
    $transport->close();
 
} catch (ArithmaticException $ae) {
    // performed an illegal operation, like 10/0
    echo "ArithmatixException: ".$ae->msg."\r\n";
 
} catch (MatrixException $mx) {
    // performed an illegal matrix operation
    echo "MatrixException: ".$mx->msg."\r\n";
 
} catch (TException $tx) {
    // a general thrift exception, like no such server
    echo "ThriftException: ".$tx->getMessage()."\r\n";
}